In [18]:
import json

import mysql.connector
from mysql.connector import MySQLConnection

import pyarrow as pa
import pyarrow.feather as feather

In [19]:
credentials = {
  "user": "readonly",
  "password": "c8pAxBUQE1krQAMPPBJH61di",
  "host": "199.192.16.220",
  "port": 3307
}

conn: MySQLConnection = mysql.connector.connect(**credentials)

In [20]:
def get_dms_data(conn: MySQLConnection, guid: str):
    cur = conn.cursor()
    query = """
    SELECT d.dms_data
      FROM app.dms a,
           dms.dms d
     WHERE a.id = d.id
       AND a.guid = %s
    """
    cur.execute(query, [guid])
    columns = cur.description
    rows = [{columns[index][0]: column for index, column in enumerate(value)} for value in cur.fetchall()]
    cur.close()
    return dict(rows[0])['dms_data']

def get_dms_data_to_json(conn: MySQLConnection, guid: str):
    return json.loads(get_dms_data(conn, guid))

def get_dms_data_to_df(conn: MySQLConnection, guid: str):
    return feather.read_feather(pa.BufferReader(get_dms_data(conn, guid)))

In [21]:
survey_guid = '57a1544a-ed69-4886-a901-5dbc5bac868c'
US = 1
DE = 2
gr = US
#gr = DE
panel_df = get_dms_data_to_df(conn, f"{survey_guid}__{gr}__panel")
dcm_df = get_dms_data_to_df(conn, f"{survey_guid}__{gr}__dcm")
definitions = get_dms_data_to_json(conn, f"{survey_guid}__def")

In [26]:
panel_df

,guid,cint_id,time,age,age_url,gender,gender_url,spending,genres__rpg,genres__story,...,competitors__call_of_duty_modern_warfare,competitors__doom_eternal,competitors__bioshock_infinite,competitors__uncharted_4,competitors__plague_tale_innocence,competitors__thief,competitors__dark_souls,competitors__elden_ring,competitors__hellblade_senuas_sacrifice,competitors__silent_hill_2
0,8553090b-ffd7-4b03-ab8a-2cc92a71ce7c,94c52ff2-2bf3-03fc-04d5-1bee96baf16f,1096,34,34,f,f,8,0.50,0.75,...,1.00,1.00,0.75,0.75,1.0,0.75,0.75,0.75,0.75,0.75
1,54b218df-f83e-4bfb-a3f3-47539d9a25a8,92444a54-b564-63c3-8573-7e6f694e78c9,909,33,33,m,m,7,1.00,0.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1409dc50-a280-4199-a4c6-459e6438f543,61047d02-ead9-5066-c525-492f87f0309f,1077,30,30,m,m,8,0.75,0.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,29174677-6612-4963-816d-a3193f220f23,93207c80-ced9-514b-e1a7-480bd4f7141d,851,34,34,m,m,8,0.50,0.50,...,1.00,0.75,0.75,0.75,1.0,0.75,0.50,0.50,0.50,0.50
4,bc54d9c8-008b-47f7-ac42-d194326218b2,bb9bfcbf-5b6d-d025-5a98-c8b04da2b822,1107,28,28,f,f,8,0.75,0.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1290,d4601045-5e33-4340-b7ce-e42d5ebe472b,bf6321d3-9210-87fa-67f6-1548ea49124e,251,33,33,m,m,3,1.00,0.75,...,1.00,1.00,0.75,0.75,1.0,1.00,1.00,0.75,0.75,0.50
1291,75feb2c1-a777-4f46-843d-31c9ae5a741d,2851f623-3e21-48db-5506-c27a22dc9bbf,1179,31,31,f,m,8,0.75,0.75,...,0.75,1.00,0.75,1.00,1.0,0.75,1.00,0.75,0.75,0.50
1292,8925dcc9-21c4-46e6-b19f-90969cca7a5f,37147ffc-5122-fd68-10d9-4b3fd1dff861,1058,30,30,m,m,8,1.00,1.00,...,0.75,0.75,0.75,1.00,1.0,1.00,1.00,1.00,1.00,1.00
1293,460ccc8e-b184-4729-bf0f-b9478fa3897e,ba1c76de-5950-cab1-18fb-423759ecf043,947,32,32,m,m,8,1.00,1.00,...,1.00,1.00,1.00,1.00,1.0,1.00,1.00,1.00,1.00,1.00
1294,d5a437c0-8c89-4247-a537-292b1f7e8703,1c3f9000-e0e7-e222-3a25-a4147296259e,862,27,34,m,m,6,1.00,0.25,...,0.75,0.75,0.50,0.75,0.5,0.75,0.50,1.00,0.75,1.00

In [27]:
dcm_df

,guid,group_id,set_num,card_num,t,f1,f2,score
0,001493d1-a6ec-4fbc-90e7-33e0287d7576,1,1667,11137,none,0,0,0
1,001493d1-a6ec-4fbc-90e7-33e0287d7576,1,1667,11137,olymp,4,19,0
2,001493d1-a6ec-4fbc-90e7-33e0287d7576,1,1667,11137,china,2,13,100
3,001493d1-a6ec-4fbc-90e7-33e0287d7576,1,1667,11138,slav,8,17,0
4,001493d1-a6ec-4fbc-90e7-33e0287d7576,1,1667,11138,none,0,0,0
...,...,...,...,...,...,...,...,...
31075,ffe4bb02-44a7-4ad1-8f8d-98b7e53b944d,1,729,4983,nord,5,19,100
31076,ffe4bb02-44a7-4ad1-8f8d-98b7e53b944d,1,729,4983,china,8,12,0
31077,ffe4bb02-44a7-4ad1-8f8d-98b7e53b944d,1,729,4984,slav,4,9,100
31078,ffe4bb02-44a7-4ad1-8f8d-98b7e53b944d,1,729,4984,none,0,0,0
31079,ffe4bb02-44a7-4ad1-8f8d-98b7e53b944d,1,729,4984,olymp,1,11,0

In [ ]:
definitions

In [25]:
conn.close()