In [1]:
from src.db import DbConnection
from src.server.models.dms_model import DmsModel
from src.project_paths import pp
from src.server.models.dashboard.surveys.survey_constants import sc
from src.runtime_constants import rr
from src.utils.gembase_utils import GembaseUtils

In [2]:
rr.set_env(rr.ENV_DEV)
conn = DbConnection()

In [8]:
conn.close()

In [3]:
SURVEY_DEF = {
sc.THEMES: [{'id': 'adventure', 'name': 'Adventure'}, {'id': 'animals', 'name': 'Animals'}, {'id': 'architecture', 'name': 'Architecture'}, {'id': 'business', 'name': 'Business'}, {'id': 'cars', 'name': 'Cars'}, {'id': 'city', 'name': 'City'}, {'id': 'crime', 'name': 'Crime'}, {'id': 'family', 'name': 'Family'}, {'id': 'fantasy', 'name': 'Fantasy'}, {'id': 'farm', 'name': 'Farm'}, {'id': 'fashion', 'name': 'Fashion'}, {'id': 'food', 'name': 'Food'}, {'id': 'garden', 'name': 'Garden'}, {'id': 'history', 'name': 'History'}, {'id': 'interior', 'name': 'Interior'}, {'id': 'luxury', 'name': 'Luxury'}, {'id': 'military', 'name': 'Military'}, {'id': 'music', 'name': 'Music'}, {'id': 'mystery', 'name': 'Mystery'}, {'id': 'nature', 'name': 'Nature'}, {'id': 'realism', 'name': 'Realism'}, {'id': 'romance', 'name': 'Romance'}, {'id': 'scifi', 'name': 'Sci-fi'}, {'id': 'sport', 'name': 'Sports'}, {'id': 'survival', 'name': 'Survival'}, {'id': 'tech', 'name': 'Technology'}, {'id': 'vehicles', 'name': 'Vehicles'}, {'id': 'weapons', 'name': 'Weapons'}],
sc.TOPICS: [{'id': 'adventure__discover', 'theme': 'adventure', 'name': 'Discover'}, {'id': 'adventure__travel', 'theme': 'adventure', 'name': 'Travel'}, {'id': 'adventure__survive', 'theme': 'adventure', 'name': 'Survive'}, {'id': 'adventure__connect', 'theme': 'adventure', 'name': 'Connect'}, {'id': 'animals__pets', 'theme': 'animals', 'name': 'Pets'}, {'id': 'animals__exotic', 'theme': 'animals', 'name': 'Exotic'}, {'id': 'animals__marine', 'theme': 'animals', 'name': 'Marine'}, {'id': 'animals__prehistoric', 'theme': 'animals', 'name': 'Prehistoric'}, {'id': 'business__finance', 'theme': 'business', 'name': 'Finance'}, {'id': 'business__corporations', 'theme': 'business', 'name': 'Corporations'}, {'id': 'business__real_estate', 'theme': 'business', 'name': 'Real Estate'}, {'id': 'business__startups', 'theme': 'business', 'name': 'Startups'}, {'id': 'cars__sport', 'theme': 'cars', 'name': 'Sport'}, {'id': 'cars__luxury', 'theme': 'cars', 'name': 'Luxury'}, {'id': 'cars__personal', 'theme': 'cars', 'name': 'Personal'}, {'id': 'cars__delivery', 'theme': 'cars', 'name': 'Delivery'}, {'id': 'crime__police', 'theme': 'crime', 'name': 'Police'}, {'id': 'crime__gangs', 'theme': 'crime', 'name': 'Gangs'}, {'id': 'crime__prison', 'theme': 'crime', 'name': 'Prison'}, {'id': 'crime__drugs', 'theme': 'crime', 'name': 'Drugs'}, {'id': 'family__generations', 'theme': 'family', 'name': 'Generations'}, {'id': 'family__kids', 'theme': 'family', 'name': 'Kids'}, {'id': 'family__heritage', 'theme': 'family', 'name': 'Heritage'}, {'id': 'family__origin', 'theme': 'family', 'name': 'Origin'}, {'id': 'fantasy__sword_magic', 'theme': 'fantasy', 'name': 'Sword & magic'}, {'id': 'fantasy__superheroes', 'theme': 'fantasy', 'name': 'Superheroes'}, {'id': 'fantasy__gods_demons', 'theme': 'fantasy', 'name': 'Gods & demons'}, {'id': 'fantasy__fables', 'theme': 'fantasy', 'name': 'Fables'}, {'id': 'fashion__clothes', 'theme': 'fashion', 'name': 'Clothes'}, {'id': 'fashion__accessories', 'theme': 'fashion', 'name': 'Accessories'}, {'id': 'fashion__cosmetics', 'theme': 'fashion', 'name': 'Cosmetics'}, {'id': 'fashion__shoes', 'theme': 'fashion', 'name': 'Shoes'}, {'id': 'food__recipes', 'theme': 'food', 'name': 'Recipes'}, {'id': 'food__sweets', 'theme': 'food', 'name': 'Sweets'}, {'id': 'food__grill', 'theme': 'food', 'name': 'Grill'}, {'id': 'food__healthy', 'theme': 'food', 'name': 'Healthy'}, {'id': 'history__medieval', 'theme': 'history', 'name': 'Medieval'}, {'id': 'history__ancient', 'theme': 'history', 'name': 'Ancient'}, {'id': 'history__industrial', 'theme': 'history', 'name': 'Industrial'}, {'id': 'history__prehistoric', 'theme': 'history', 'name': 'Prehistoric'}, {'id': 'interior__home', 'theme': 'interior', 'name': 'Home'}, {'id': 'interior__style', 'theme': 'interior', 'name': 'Style'}, {'id': 'interior__historic', 'theme': 'interior', 'name': 'Historic'}, {'id': 'interior__corporate', 'theme': 'interior', 'name': 'Corporate'}, {'id': 'luxury__jewellery', 'theme': 'luxury', 'name': 'Jewellery'}, {'id': 'luxury__real_estate', 'theme': 'luxury', 'name': 'Real estate'}, {'id': 'luxury__yachts', 'theme': 'luxury', 'name': 'Yachts'}, {'id': 'luxury__cars', 'theme': 'luxury', 'name': 'Cars'}, {'id': 'military__battles', 'theme': 'military', 'name': 'Battles'}, {'id': 'military__history', 'theme': 'military', 'name': 'History'}, {'id': 'military__heroes', 'theme': 'military', 'name': 'Heroes'}, {'id': 'military__espionage', 'theme': 'military', 'name': 'Espionage'}, {'id': 'mystery__crime', 'theme': 'mystery', 'name': 'Crime'}, {'id': 'mystery__conspiracy', 'theme': 'mystery', 'name': 'Conspiracy'}, {'id': 'mystery__supernatural', 'theme': 'mystery', 'name': 'Supernatural'}, {'id': 'mystery__scientific', 'theme': 'mystery', 'name': 'Scientific'}, {'id': 'romance__love', 'theme': 'romance', 'name': 'Love'}, {'id': 'romance__relationships', 'theme': 'romance', 'name': 'Relationships'}, {'id': 'romance__sex', 'theme': 'romance', 'name': 'Sex'}, {'id': 'romance__youth', 'theme': 'romance', 'name': 'Youth'}, {'id': 'sport__team', 'theme': 'sport', 'name': 'Team'}, {'id': 'sport__individual', 'theme': 'sport', 'name': 'Individual'}, {'id': 'sport__fitness', 'theme': 'sport', 'name': 'Fitness'}, {'id': 'sport__martial_arts', 'theme': 'sport', 'name': 'Martial arts'}, {'id': 'survival__zombies', 'theme': 'survival', 'name': 'Zombies'}, {'id': 'survival__wilderness', 'theme': 'survival', 'name': 'Wilderness'}, {'id': 'survival__disaster', 'theme': 'survival', 'name': 'Disaster'}, {'id': 'survival__war', 'theme': 'survival', 'name': 'War'}, {'id': 'tech__electronics', 'theme': 'tech', 'name': 'Electronics'}, {'id': 'tech__software', 'theme': 'tech', 'name': 'Software'}, {'id': 'tech__mechanics', 'theme': 'tech', 'name': 'Mechanics'}, {'id': 'tech__medicine', 'theme': 'tech', 'name': 'Medicine'}, {'id': 'vehicles__motorcycles', 'theme': 'vehicles', 'name': 'Motorcycles'}, {'id': 'vehicles__airplanes', 'theme': 'vehicles', 'name': 'Airplanes'}, {'id': 'vehicles__trains', 'theme': 'vehicles', 'name': 'Trains'}, {'id': 'vehicles__ships', 'theme': 'vehicles', 'name': 'Ships'}, {'id': 'weapons__guns', 'theme': 'weapons', 'name': 'Guns'}, {'id': 'weapons__high_tech', 'theme': 'weapons', 'name': 'High-tech'}, {'id': 'weapons__mass_destruction', 'theme': 'weapons', 'name': 'Mass destruction'}, {'id': 'weapons__historic', 'theme': 'weapons', 'name': 'Historic'}, {'id': 'nature__islands', 'theme': 'nature', 'name': 'Islands'}, {'id': 'nature__animals', 'theme': 'nature', 'name': 'Animals'}, {'id': 'nature__mountains', 'theme': 'nature', 'name': 'Mountains'}, {'id': 'nature__water', 'theme': 'nature', 'name': 'Water'}, {'id': 'realism__life', 'theme': 'realism', 'name': 'Life'}, {'id': 'realism__people', 'theme': 'realism', 'name': 'People'}, {'id': 'realism__truth', 'theme': 'realism', 'name': 'Truth'}, {'id': 'realism__document', 'theme': 'realism', 'name': 'Document'}, {'id': 'scifi__universe', 'theme': 'scifi', 'name': 'Universe'}, {'id': 'scifi__aliens', 'theme': 'scifi', 'name': 'Aliens'}, {'id': 'scifi__future', 'theme': 'scifi', 'name': 'Future'}, {'id': 'scifi__technology', 'theme': 'scifi', 'name': 'Technology'}, {'id': 'architecture__building', 'theme': 'architecture', 'name': 'Building'}, {'id': 'architecture__design', 'theme': 'architecture', 'name': 'Design'}, {'id': 'architecture__construction', 'theme': 'architecture', 'name': 'Construction'}, {'id': 'architecture__art', 'theme': 'architecture', 'name': 'Art'}, {'id': 'city__building', 'theme': 'city', 'name': 'building'}, {'id': 'city__people', 'theme': 'city', 'name': 'people'}, {'id': 'city__busy', 'theme': 'city', 'name': 'busy'}, {'id': 'city__traffic', 'theme': 'city', 'name': 'traffic'}, {'id': 'farm__animals', 'theme': 'farm', 'name': 'animals'}, {'id': 'farm__crops', 'theme': 'farm', 'name': 'crops'}, {'id': 'farm__trees', 'theme': 'farm', 'name': 'trees'}, {'id': 'farm__garden', 'theme': 'farm', 'name': 'garden'}, {'id': 'garden__flowers', 'theme': 'garden', 'name': 'flowers'}, {'id': 'garden__plants', 'theme': 'garden', 'name': 'plants'}, {'id': 'garden__trees', 'theme': 'garden', 'name': 'trees'}, {'id': 'garden__vegetables', 'theme': 'garden', 'name': 'vegetables'}, {'id': 'music__dance', 'theme': 'music', 'name': 'dance'}, {'id': 'music__sing', 'theme': 'music', 'name': 'sing'}, {'id': 'music__chill', 'theme': 'music', 'name': 'chill'}, {'id': 'music__background', 'theme': 'music', 'name': 'background'}],
sc.GENRES: [
 {'id': 'puzzle', 'name': 'Puzzles'},
 {'id': 'action', 'name': 'Action'},
 {'id': 'simulation', 'name': 'Simulations'},
 {'id': 'slots', 'name': 'Slots'},
 {'id': 'interactive_story', 'name': 'Interactive story'},
 {'id': 'customization', 'name': 'Customization'},
 {'id': 'strategy', 'name': 'Strategy'},
 {'id': 'rpg', 'name': 'Role Playing Games'},
 {'id': 'ar', 'name': 'Augmented Reality / Location'}],
sc.GENRES_SUB: [{'id': 'match3', 'name': 'Matching or Merge puzzles', 'genre': 'puzzle'},
 {'id': 'cards', 'name': 'Word or Card puzzles', 'genre': 'puzzle'},
 {'id': 'hidden_objects', 'name': 'Hidden object puzzles', 'genre': 'puzzle'},
 {'id': 'puzzle_physics', 'name': 'Puzzles with physics', 'genre': 'puzzle'},
 {'id': 'labyrinth', 'name': 'Escape or Maze puzzles', 'genre': 'puzzle'},
 {'id': 'non_shooting_action',
  'name': 'Non-shooter Action',
  'genre': 'action'},
 {'id': 'shooting_action', 'name': 'Shooter Action', 'genre': 'action'},
 {'id': 'tycoon', 'name': 'Tycoon', 'genre': 'simulation'},
 {'id': 'idle_tycoon', 'name': 'Idle tycoon', 'genre': 'simulation'},
 {'id': 'life_sim', 'name': 'Life simulations', 'genre': 'simulation'},
 {'id': 'sandbox', 'name': 'Sandbox', 'genre': 'simulation'}]
}

In [4]:
from src.server.models.dms_constants import DmsConstants

platform = DmsModel.get_dms_data_to_json(conn, guid=DmsConstants.platform_guid)
prompts = DmsModel.get_dms_data_to_json(conn, guid=DmsConstants.prompts_guid)

In [5]:
def format_name(name: str) -> str:
    return name.replace("-", "_").replace(" ", "_").lower()

def prompt_tag_to_interface(prompt_tag: str):
    for it in platform["Interface"]:
        node = it["Product_node"]
        if node == "Solutions" and prompt_tag == "Solutions":
            pass
        if node == prompt_tag and it["Search_node"] is not None and it["Search_node"] != "":
            return it
    return None

final_data = {
    "existing_cols": {
        "topics": [],
        "genres": []
    },
    "potential_cols": {
        "topics": [],
        "genres": []
    },
    "items": {

    }
}
areas = pp.get_private_data()["google"]["google_docs"]["prompts"]["areas"]
for area in areas:
    for it in prompts[area]:
        is_genre = area == "Genres"
        tag = it["Tag"]
        interface = prompt_tag_to_interface(it["Tag"])
        if interface is None:
            continue
        if interface["Category"] == "Genre" and not is_genre:
            continue
        if interface["Category"] == "Topic" and is_genre:
            continue

        c = interface["Category"]
        s = interface["Subcategory"]
        n = interface["Search_node"]
        def_id = f"{GembaseUtils.name_to_col(c)}__{GembaseUtils.name_to_col(s)}__{GembaseUtils.name_to_col(n)}"

        search_node = interface["Search_node"]
        if interface is not None:
            tagged_col = f"{format_name(area)}__{format_name(it['Category'])}__{format_name(tag)}"

            try:
                row = conn.select_one_or_none(f"""
                SELECT ROUND((SUM(a.downloads_us_gp_12m) / 6) / 155000000 * 8, 2) AS product
                  FROM tagged_data.apps tg,
                       scraped_data.gp_ext_data a
                 WHERE tg.{tagged_col} = 1
                   AND tg.app_id = a.app_id
                """)
                if row is not None:
                    if search_node not in final_data["items"]:
                        final_data["items"][search_node] = {
                            "id": def_id,
                            "prompts": 0,
                            "survey": 0,
                            "def": interface,
                            "potential_id": "",
                            "existing_id": "",
                        }
                    final_data["items"][search_node]["prompts"] = float(row['product'])
                    final_data["items"][search_node]["existing_id"] = tagged_col
                    if is_genre:
                        final_data["existing_cols"]["genres"].append({
                            "col": tagged_col,
                            "def_id": def_id
                        })
                    else:
                        final_data["existing_cols"]["topics"].append({
                            "col": tagged_col,
                            "def_id": def_id
                        })
            except Exception as err:
                print(f"NOT FOUND: Tag: {tag} -> Search Node: {search_node} -> {tagged_col}")

In [7]:
df = DmsModel.get_dms_data_to_df(conn, guid=DmsConstants.demo_panel)
df

,guid,cint_id,time,age,gender,spending,spending__avg,genres__puzzle,genres__slots,genres__interactive_story,...,competitors__brawl_stars,competitors__archero,competitors__pubg_mobile,competitors__cats_crash_arena_turbo_stars,competitors__pokemon_go,competitors__episode_choose_your_story,competitors__chapters_interactive_stories,competitors__the_sims,competitors__avakin_life_3d,competitors__idle_life_sim
0,6,6,299.0,45,f,4,35.5,0.50,0.50,0.75,...,NaN,NaN,NaN,NaN,NaN,0.75,0.75,0.75,0.25,0.75
1,8,8,5498.0,37,f,1,0.0,0.25,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9,9,1134.0,55,f,1,0.0,0.50,0.50,0.25,...,0.00,0.00,0.00,0.00,1.00,NaN,NaN,0.25,0.00,0.00
3,10,10,2514.0,41,m,6,300.5,0.75,0.75,0.75,...,0.75,0.00,0.50,0.00,0.50,0.50,0.50,0.75,0.00,0.00
4,12,12,548.0,41,m,2,5.5,0.75,0.50,1.00,...,0.50,0.00,0.25,0.25,0.75,0.25,0.25,0.50,0.25,0.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1992,2663,2663,468.0,34,m,2,5.5,0.75,1.00,0.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.75,0.00,0.00
1993,2664,2664,453.0,21,m,4,35.5,NaN,0.50,0.50,...,0.75,0.00,0.50,0.50,0.75,NaN,NaN,0.75,0.75,0.00
1994,2665,2665,8719.0,31,m,3,15.5,0.75,0.50,0.50,...,0.25,0.25,0.50,0.00,0.50,NaN,NaN,NaN,NaN,NaN
1995,2666,2666,698.0,34,m,4,35.5,0.50,0.50,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1996,2667,2667,10579.0,46,m,2,5.5,1.00,1.00,0.75,...,0.25,0.25,0.25,0.25,0.75,0.25,0.25,0.75,0.25,0.25

In [14]:
def find_def(gr: str, c: str):
    res = []
    p = sc.get_prefix(gr)
    c = c.replace(p, "")
    for it in SURVEY_DEF[gr]:
        if it["id"] == c:
            for interface in platform["Interface"]:
                if interface["Audience_node"].lower() == it["name"].lower():
                    if interface["Search_node"] is not None and interface["Search_node"] != "":
                        res.append(interface)
    return res

cnt = len(df.index)
for col in df.columns:
    for k in SURVEY_DEF:
        p = sc.get_prefix(k)
        if p in col:
            for d in find_def(k, col):
                c = d["Category"]
                s = d["Subcategory"]
                n = d["Search_node"]
                def_id = f"{GembaseUtils.name_to_col(c)}__{GembaseUtils.name_to_col(s)}__{GembaseUtils.name_to_col(n)}"

                search_node = d["Search_node"]
                if search_node not in final_data["items"]:
                    final_data["items"][search_node] = {
                        "id": def_id,
                        "prompts": 0,
                        "survey": 0,
                        "def": d,
                        "potential_id": "",
                        "existing_id": ""
                    }
                final_data["items"][search_node]["survey"] = round(len(df[df[col] >= 0.75].index) / cnt * 100, 2)
                final_data["items"][search_node]["potential_id"] = col
                if k == sc.GENRES or k == sc.GENRES_SUB:
                    final_data["potential_cols"]["genres"].append({
                        "def_id": def_id,
                        "col": col,
                    })
                elif k == sc.TOPICS or k == sc.THEMES:
                    final_data["potential_cols"]["topics"].append({
                        "def_id": def_id,
                        "col": col,
                    })

In [ ]:
final_data

In [ ]:
from src import external_api

values = []
values.append(["Search node", "Existing", "Potential"])

for k in final_data:
    values.append([k, str(final_data[k]["prompts"]), str(final_data[k]["survey"])])

external_api.write_sheet("1TIu0NXPH8LFgVmlzA4-y2GdI80MbnQW_-FAvAxDCvys", "search_gaps_test", values)

In [15]:

dms_data = []
for k in final_data["items"]:
    potential = final_data["items"][k]["survey"]
    existing = final_data["items"][k]["prompts"]
    value = round(((potential - existing) / 100) * 155000000)
    if value < 1000:
        value = round(value / 100) * 100
    elif value < 10000:
        value = round(value / 1000) * 1000
    elif value < 100000:
        value = round(value / 10000) * 10000
    else:
        value = round(value / 100000) * 100000

    c = final_data["items"][k]["def"]["Category"]
    s = final_data["items"][k]["def"]["Subcategory"]
    n = final_data["items"][k]["def"]["Search_node"]
    potential_id = final_data["items"][k]["potential_id"]
    existing_id = final_data["items"][k]["existing_id"]
    if existing_id != "" and potential_id != "":
        dms_data.append({
            "id": f"{GembaseUtils.name_to_col(c)}__{GembaseUtils.name_to_col(s)}__{GembaseUtils.name_to_col(n)}",
            "category": c,
            "subcategory": s,
            "node": n,
            "value": value,
            "existing_id": existing_id,
            "potential_id": potential_id
        })

DmsModel.save_json_to_dms(conn, {
    "items": dms_data,
    "existing_cols": final_data["existing_cols"],
    "potential_cols": final_data["potential_cols"]
}, guid=DmsConstants.search_gaps, file_type="search gaps")
conn.commit()

In [16]:
conn = DbConnection(rr.ENV_PROD)
DmsModel.save_json_to_dms(conn, {
    "items": dms_data,
    "existing_cols": final_data["existing_cols"],
    "potential_cols": final_data["potential_cols"]
}, guid=DmsConstants.search_gaps, file_type="search gaps")
conn.commit()

In [ ]:
existing_id = "genres__genre__puzzle"
potential_id = "genres__puzzle"

search_gaps = DmsModel.get_dms_data_to_json(conn, guid=DmsConstants.search_gaps)
data = {}
for tagged_col in search_gaps["existing_cols"]["topics"]:
    row = conn.select_one_or_none(f"""
    SELECT ROUND((SUM(a.downloads_us_gp_12m) / 6) / 155000000 * 8, 2) AS cnt
      FROM tagged_data.apps tg,
           scraped_data.gp_ext_data a
     WHERE tg.{tagged_col} = 1
       AND tg.{existing_id} = 1
       AND tg.app_id = a.app_id
    """)
    data[tagged_col] = 0
    if row is not None:
        data[tagged_col] = float(row["cnt"])
#data
cnt = len(df.index)
for survey_col in search_gaps["potential_cols"]["topics"]:
    print(round((len(df[df[survey_col] >= 0.75].index) / cnt) * 100, 2))

In [70]:
df[(df["genres__ar"] >= 0.75) & (df["genres__action"] >= 0.75)]

,guid,cint_id,time,age,gender,spending,genres__puzzle,genres__slots,genres__interactive_story,genres__customization,...,competitors__brawl_stars,competitors__archero,competitors__pubg_mobile,competitors__cats_crash_arena_turbo_stars,competitors__pokemon_go,competitors__episode_choose_your_story,competitors__chapters_interactive_stories,competitors__the_sims,competitors__avakin_life_3d,competitors__idle_life_sim
3,10,10,2514.0,41,m,6,0.75,0.75,0.75,1.00,...,0.75,0.00,0.50,0.00,0.50,0.50,0.50,0.75,0.00,0.00
5,13,13,278.0,46,m,4,1.00,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
7,15,15,425.0,55,f,4,1.00,0.75,0.75,0.50,...,0.00,0.00,0.00,0.00,0.75,0.00,0.00,1.00,0.00,0.00
14,22,22,554.0,45,m,5,0.75,0.75,0.50,0.75,...,0.50,0.50,0.75,0.00,0.75,NaN,NaN,0.75,0.00,0.00
15,23,23,280.0,31,m,1,NaN,0.25,0.50,0.25,...,0.25,0.00,0.50,0.00,0.75,NaN,NaN,0.75,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1983,2648,2648,244.0,34,m,5,1.00,0.25,1.00,0.50,...,0.50,0.75,0.50,0.50,1.00,1.00,0.75,1.00,0.75,1.00
1987,2655,2655,409.0,29,m,5,1.00,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
1989,2659,2659,764.0,28,m,4,1.00,0.75,0.75,0.50,...,0.75,0.75,1.00,0.50,1.00,0.50,0.50,0.75,0.50,0.50
1993,2664,2664,453.0,21,m,4,NaN,0.50,0.50,0.50,...,0.75,0.00,0.50,0.50,0.75,NaN,NaN,0.75,0.75,0.00
1996,2667,2667,10579.0,46,m,2,1.00,1.00,0.75,1.00,...,0.25,0.25,0.25,0.25,0.75,0.25,0.25,0.75,0.25,0.25

In [9]:
df[df["age"] <= 24]

,guid,cint_id,time,age,gender,spending,spending__avg,genres__puzzle,genres__slots,genres__interactive_story,...,competitors__brawl_stars,competitors__archero,competitors__pubg_mobile,competitors__cats_crash_arena_turbo_stars,competitors__pokemon_go,competitors__episode_choose_your_story,competitors__chapters_interactive_stories,competitors__the_sims,competitors__avakin_life_3d,competitors__idle_life_sim
46,63,63,337.0,24,f,2,5.5,0.75,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.50,0.00,0.25
51,69,69,241.0,24,f,1,0.0,0.25,0.50,0.75,...,NaN,NaN,NaN,NaN,NaN,0.50,0.75,NaN,NaN,NaN
57,76,76,527.0,22,m,1,0.0,1.00,1.00,1.00,...,0.25,0.25,0.50,0.25,0.75,0.25,0.25,0.75,0.25,0.25
60,80,80,554.0,21,f,8,1000.0,0.50,0.50,1.00,...,NaN,NaN,NaN,NaN,NaN,0.75,0.75,1.00,0.25,0.00
63,83,83,302.0,19,f,2,5.5,0.75,0.25,0.75,...,0.25,0.25,0.50,0.25,0.50,0.75,0.25,0.50,0.25,0.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1975,2639,2639,172.0,23,m,4,35.5,0.50,0.50,0.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1976,2640,2640,483.0,19,m,2,5.5,0.50,0.25,0.75,...,0.25,0.00,0.25,0.00,0.75,0.50,0.50,0.50,0.00,0.00
1988,2657,2657,1733.0,19,m,1,0.0,0.25,0.50,0.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,0.00,0.00
1990,2660,2660,326.0,20,None,2,5.5,0.25,0.50,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.75,0.25,0.25
1993,2664,2664,453.0,21,m,4,35.5,NaN,0.50,0.50,...,0.75,0.00,0.50,0.50,0.75,NaN,NaN,0.75,0.75,0.00