In [1]:
import json
import numpy as np
import pandas as pd
from functools import reduce
from tqdm import tqdm
import pickle
import io

import mysql.connector
from mysql.connector import MySQLConnection

import larch
from larch.roles import P,X

import pyarrow as pa
import pyarrow.feather as feather

# Data load & preprocess

## Load data

In [2]:
credentials = {
  "user": "external.data.user",
  "password": "wIfQxcjgZ5!gA*FWgi1z$Kj9",
  "host": "35.208.148.42",
  "port": 3306
}

conn: MySQLConnection = mysql.connector.connect(**credentials)

In [3]:
def get_dms_data(conn: MySQLConnection, guid: str):
    cur = conn.cursor()
    query = """
    SELECT DATA FROM external_data.dms WHERE guid = %s
    """

    cur.execute(query, [guid])
    columns = cur.description
    rows = [{columns[index][0]: column for index, column in enumerate(value)} for value in cur.fetchall()]
    cur.close()
    
    return dict(rows[0])['DATA']

def get_dms_data_to_json(conn: MySQLConnection, guid: str):
    return json.loads(get_dms_data(conn, guid))

def get_dms_data_to_df(conn: MySQLConnection, guid: str):
    return feather.read_feather(pa.BufferReader(get_dms_data(conn, guid)))

In [4]:
guid_info = "7c0eea07-99a1-458e-a315-2b67cc9981ad"
guid_topics_dcm = "2ecf3ce4-aede-4516-a049-5d274659e5ec"
guid_genres_dcm = "4a30eb82-dc77-47c0-99ab-98d4ffb9759f"
guid_tags = "73df38cd-31aa-43e5-b05b-6e973ab35295"

In [5]:
info_df = get_dms_data_to_df(conn, guid_info)
topic_dcm_df = get_dms_data_to_df(conn, guid_topics_dcm)
genres_dcm_df = get_dms_data_to_df(conn, guid_genres_dcm)
tags_df = get_dms_data_to_df(conn, guid_tags)

In [6]:
conn.close()

In [7]:
# user metadata1 - age, gender, spend, playtime, loyalty
info_df

,id,survey_meta_id,survey_instance,age,gender,role,favorite_game,spending,playing_time,loyalty
0,1,1,33cbe449-af6a-484b-a521-6a4d08f73454,37,f,10,com.my.defense,75,15,5
1,2,1,5db16995-594b-4b4e-9151-e502b85d6ff3,42,m,10,com.scopely.monopolygo,5,13,4
2,3,1,9722c487-9a13-4a9d-8599-577b69805034,42,f,10,com.dreamgames.royalmatch,5,0,1
3,4,1,7094ec2f-88d4-4642-90f6-f12b41eca4f1,65,m,10,com.samfinaco.paradise,300,15,5
4,5,1,eb6a4d45-c680-4eaf-bef7-aebe5edb7ce0,37,m,10,com.riotgames.league.teamfighttactics,300,8,4
...,...,...,...,...,...,...,...,...,...,...
1965,1966,1,35fc0bbf-cef7-4ad9-b0c7-8bfb50043cc3,32,m,10,com.miniclip.eightballpool,15,8,4
1966,1967,1,b11b6d9c-f739-478a-ab26-d26d11825827,32,m,10,com.nintendo.zara,0,8,1
1967,1968,1,e9c3e858-826f-479e-a85d-6ea3b0e4e43a,32,m,10,com.playtika.wsop.gp,15,8,-1
1968,1969,1,b6e5ec83-0b04-4f2d-8d54-1bc0d6785adc,32,m,4,com.bandainamcogames.dbzdokkanww,0,0,1
1969,1970,1,8ec75988-2510-4d41-b5da-456e237c2574,32,m,7,com.activision.callofduty.shooter,300,8,4

In [8]:
# topic - environment + eras / domain + focus / entity / role conjoint
topic_dcm_df

,id,survey_meta_id,survey_instance,dcm_order,topic,feature_1a,feature_1b,feature_2a,feature_2b,chosen_a,chosen_b
0,1,1,33cbe449-af6a-484b-a521-6a4d08f73454,1,topics__fantasy,entities__robot,roles__creator,entities__celestial,roles__team,None,None
1,2,1,33cbe449-af6a-484b-a521-6a4d08f73454,2,topics__fantasy,entities__kid,roles__carer,entities__animal,roles__warrior,None,None
2,3,1,33cbe449-af6a-484b-a521-6a4d08f73454,3,topics__fantasy,environment__aquatic,domains__crime,environment__alternality,domains__business,environment__aquatic,domains__crime
3,4,1,33cbe449-af6a-484b-a521-6a4d08f73454,4,topics__fantasy,entities__adult,roles__rebel,entities__zombie,roles__creator,entities__zombie,roles__creator
4,5,1,33cbe449-af6a-484b-a521-6a4d08f73454,5,topics__fantasy,environment__wilderness,focus__weapons,environment__space,domains__military,None,None
...,...,...,...,...,...,...,...,...,...,...,...
6985,6986,1,8ec75988-2510-4d41-b5da-456e237c2574,1,topics__mystery,entities__celestial,roles__mystic,entities__plant,roles__follower,entities__plant,roles__follower
6986,6987,1,8ec75988-2510-4d41-b5da-456e237c2574,2,topics__mystery,entities__super_,roles__warrior,entities__celestial,roles__creator,entities__super_,roles__warrior
6987,6988,1,8ec75988-2510-4d41-b5da-456e237c2574,3,topics__mystery,entities__human,roles__team,entities__robot,roles__carer,entities__human,roles__team
6988,6989,1,8ec75988-2510-4d41-b5da-456e237c2574,4,topics__mystery,entities__alien,roles__solver,entities__celestial,roles__mystic,entities__alien,roles__solver
6989,6990,1,8ec75988-2510-4d41-b5da-456e237c2574,5,topics__mystery,eras__renaissance,domains__family,environment__urban,domains__health,eras__renaissance,domains__family

In [9]:
# genres - mechanics conjoint
genres_dcm_df

,id,survey_meta_id,survey_instance,dcm_order,genre_1,genre_2,core_1,core_2,chosen
0,1,1,33cbe449-af6a-484b-a521-6a4d08f73454,1,genre__match,None,core__connect,core__merge,core__merge
1,2,1,33cbe449-af6a-484b-a521-6a4d08f73454,2,genre__casino,None,core__slots,core__poker,core__slots
2,3,1,33cbe449-af6a-484b-a521-6a4d08f73454,3,genre__strategy,None,core__4x,core__lane,core__lane
3,4,1,33cbe449-af6a-484b-a521-6a4d08f73454,4,genre__strategy,genre__match,core__lane,core__blast,core__blast
4,5,1,33cbe449-af6a-484b-a521-6a4d08f73454,5,genre__match,genre__strategy,core__merge,core__summon,core__summon
...,...,...,...,...,...,...,...,...,...
8940,8941,1,8ec75988-2510-4d41-b5da-456e237c2574,1,genre__combat,genre__education,core__moba,core__asymetric,core__moba
8941,8942,1,8ec75988-2510-4d41-b5da-456e237c2574,2,genre__education,genre__combat,core__vehicular,core__bullet_hell,core__bullet_hell
8942,8943,1,8ec75988-2510-4d41-b5da-456e237c2574,3,genre__puzzle,genre__casino,core__time_loop,core__poker,core__time_loop
8943,8944,1,8ec75988-2510-4d41-b5da-456e237c2574,4,genre__puzzle,genre__education,core__escape_room,core__move_blocks,core__escape_room
8944,8945,1,8ec75988-2510-4d41-b5da-456e237c2574,5,genre__puzzle,genre__education,core__time_loop,core__jigsaw,core__time_loop

In [10]:
# user metadata 2 - platforms, genres, topics, needs, behaviours, activities, movies, hobbies, socials
tags_df

,id,survey_meta_id,tag_id,tag_value,survey_instance
0,1,1,platforms__mobile,1,33cbe449-af6a-484b-a521-6a4d08f73454
1,2,1,platforms__playstation,1,33cbe449-af6a-484b-a521-6a4d08f73454
2,3,1,platforms__pc,1,33cbe449-af6a-484b-a521-6a4d08f73454
3,4,1,genre__rpg,66,33cbe449-af6a-484b-a521-6a4d08f73454
4,5,1,genre__match,100,33cbe449-af6a-484b-a521-6a4d08f73454
...,...,...,...,...,...
121361,121362,1,multiplayer__multi,4,8ec75988-2510-4d41-b5da-456e237c2574
121362,121363,1,multiplayer__single,3,8ec75988-2510-4d41-b5da-456e237c2574
121363,121364,1,activities__working,1,8ec75988-2510-4d41-b5da-456e237c2574
121364,121365,1,activities__parenting,1,8ec75988-2510-4d41-b5da-456e237c2574
121365,121366,1,activities__video_games,1,8ec75988-2510-4d41-b5da-456e237c2574

In [11]:
tags_pivot_df = tags_df.pivot(
    index="survey_instance", columns="tag_id", values="tag_value"
).reset_index()

tags_pivot_df.columns.name = None

sorted_categories = ['platforms', 'multiplayer', 'genre', 'topics', 'needs', 'behaviors', 'activities', 'movies', 'hobbies', 'socials']
sorted_col_names = sorted(tags_df.tag_id.unique(), key=lambda x: f"{sorted_categories.index(x.split('_')[0])}_{'_'.join(x.split('_')[2:])}")

tags_pivot_df = tags_pivot_df[['survey_instance'] + sorted_col_names]
tags_pivot_df

,survey_instance,platforms__mobile,platforms__pc,platforms__playstation,platforms__switch,platforms__xbox,multiplayer__multi,multiplayer__single,genre__arcade,genre__building,...,socials__linkedin,socials__pinterest,socials__reddit,socials__snapchat,socials__telegram,socials__tiktok,socials__twitch,socials__twitter,socials__whatsapp,socials__youtube
0,000e7770-bcb0-494f-87b1-ff31f975c98d,1.0,NaN,NaN,NaN,NaN,4.0,4.0,33.0,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0027a589-c6bf-480d-8e12-77cf79b45152,1.0,NaN,NaN,NaN,NaN,1.0,4.0,100.0,NaN,...,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN
2,003d6fa0-2ce5-4eba-9053-5f0bc832d6ff,1.0,1.0,1.0,1.0,NaN,3.0,4.0,100.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,004d89f9-a2ce-4777-b32a-3e111edb5d44,1.0,NaN,NaN,NaN,1.0,3.0,4.0,33.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,005f6277-0f98-417c-86d7-9462a8780587,1.0,NaN,1.0,NaN,1.0,4.0,4.0,100.0,33.0,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1965,ffc684b4-4c08-41c2-9c13-22700afecc6b,1.0,NaN,1.0,NaN,NaN,3.0,4.0,66.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1966,ffedffd2-21c5-449e-9396-4991f62ca880,1.0,1.0,1.0,NaN,NaN,2.0,4.0,33.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1967,fff0cf1d-11dd-4819-a104-a12051e64a2f,1.0,NaN,1.0,1.0,NaN,3.0,4.0,66.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1968,fff7e72f-0682-4d36-9690-6d8f95466e6a,1.0,1.0,NaN,NaN,1.0,4.0,4.0,66.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1969,fffa4324-b58c-417a-b7bd-b69e1576694e,1.0,1.0,NaN,NaN,1.0,2.0,4.0,66.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
sorted_col_names

['platforms__mobile',
 'platforms__pc',
 'platforms__playstation',
 'platforms__switch',
 'platforms__xbox',
 'multiplayer__multi',
 'multiplayer__single',
 'genre__arcade',
 'genre__building',
 'genre__casino',
 'genre__combat',
 'genre__driving',
 'genre__education',
 'genre__idle',
 'genre__match',
 'genre__party',
 'genre__puzzle',
 'genre__rpg',
 'genre__simulation',
 'genre__sports',
 'genre__story',
 'genre__strategy',
 'genre__tabletop',
 'topics__action',
 'topics__adventure',
 'topics__comedy',
 'topics__drama',
 'topics__fantasy',
 'topics__horror',
 'topics__mystery',
 'topics__realistic',
 'topics__romance',
 'topics__sci_fi',
 'needs__acceptance',
 'needs__accomplishment',
 'needs__appreciation',
 'needs__control',
 'needs__fitness',
 'needs__insight',
 'needs__intimacy',
 'needs__mastery',
 'needs__morality',
 'needs__novelty',
 'needs__recognition',
 'needs__relief',
 'needs__safety',
 'needs__superiority',
 'needs__trust',
 'needs__uniqueness',
 'needs__wealth',
 'behaviors__chill',
 'behaviors__collect',
 'behaviors__combat',
 'behaviors__compete',
 'behaviors__complete',
 'behaviors__cooperate',
 'behaviors__destroy',
 'behaviors__discover',
 'behaviors__empower',
 'behaviors__experiment',
 'behaviors__express',
 'behaviors__immerse',
 'behaviors__plan',
 'behaviors__react',
 'behaviors__solve',
 'activities__following_news',
 'activities__friends',
 'activities__hobbies',
 'activities__learning',
 'activities__movies',
 'activities__music',
 'activities__parenting',
 'activities__partner',
 'activities__pets',
 'activities__reading',
 'activities__social_media',
 'activities__video_games',
 'activities__working',
 'movies__action_adventure',
 'movies__anime',
 'movies__children_family',
 'movies__classic',
 'movies__comedies',
 'movies__criminal',
 'movies__documentary',
 'movies__drama',
 'movies__fantasy',
 'movies__horror',
 'movies__reality_shows',
 'movies__romantic',
 'movies__scifi',
 'movies__thriller',
 'hobbies__building_fixing',
 'hobbies__collecting',
 'hobbies__cooking',
 'hobbies__design',
 'hobbies__diy',
 'hobbies__driving',
 'hobbies__exercising_sports',
 'hobbies__farm_garden',
 'hobbies__fishing_hunting',
 'hobbies__gardening',
 'hobbies__performing_arts',
 'hobbies__photographing',
 'hobbies__serving_community',
 'hobbies__teaching',
 'hobbies__watching_games',
 'hobbies__watching_sports',
 'socials__discord',
 'socials__facebook',
 'socials__instagram',
 'socials__linkedin',
 'socials__pinterest',
 'socials__reddit',
 'socials__snapchat',
 'socials__telegram',
 'socials__tiktok',
 'socials__twitch',
 'socials__twitter',
 'socials__whatsapp',
 'socials__youtube']

In [13]:
PLATFORM_COLS = ['platforms__mobile', 'platforms__pc', 'platforms__playstation', 'platforms__switch', 'platforms__xbox']
MULTIPLAYER_COLS = ['multiplayer__multi', 'multiplayer__single']
GENRE_COLS = [
    'genre__arcade', 'genre__building', 'genre__casino', 'genre__combat', 'genre__driving',
    'genre__education', 'genre__idle', 'genre__match', 'genre__party', 'genre__puzzle',
    'genre__rpg', 'genre__simulation', 'genre__sports', 'genre__story', 'genre__strategy',
    'genre__tabletop',
]
TOPIC_COLS = [
    'topics__action', 'topics__adventure', 'topics__comedy', 'topics__drama', 'topics__fantasy','topics__horror', 'topics__mystery', 'topics__realistic', 'topics__romance', 'topics__sci_fi',
]
NEED_COLS = [
    'needs__acceptance', 'needs__accomplishment', 'needs__appreciation', 'needs__control',
    'needs__fitness', 'needs__insight', 'needs__intimacy', 'needs__mastery', 'needs__morality',
    'needs__novelty', 'needs__recognition', 'needs__relief', 'needs__safety', 'needs__superiority',
    'needs__trust', 'needs__uniqueness', 'needs__wealth',
]
BEHAVIOUR_COLS = [
    'behaviors__chill', 'behaviors__collect', 'behaviors__combat', 'behaviors__compete',
    'behaviors__complete', 'behaviors__cooperate', 'behaviors__destroy', 'behaviors__discover',
    'behaviors__empower', 'behaviors__experiment', 'behaviors__express', 'behaviors__immerse',
    'behaviors__plan', 'behaviors__react', 'behaviors__solve',
]
ACTIVITY_COLS = [
    'activities__following_news', 'activities__friends', 'activities__hobbies', 'activities__learning','activities__movies', 'activities__music', 'activities__parenting', 'activities__partner',
    'activities__pets', 'activities__reading', 'activities__social_media', 'activities__video_games',
    'activities__working',
]
MOVIE_COLS = [
    'movies__action_adventure', 'movies__anime', 'movies__children_family', 'movies__classic',
    'movies__comedies', 'movies__criminal', 'movies__documentary', 'movies__drama', 'movies__fantasy',
    'movies__horror', 'movies__reality_shows', 'movies__romantic', 'movies__scifi',
]
HOBBY_COLS = [
    'hobbies__building_fixing', 'hobbies__collecting', 'hobbies__cooking', 'hobbies__design',
    'hobbies__diy', 'hobbies__driving', 'hobbies__exercising_sports', 'hobbies__farm_garden',
    'hobbies__fishing_hunting', 'hobbies__gardening', 'hobbies__performing_arts', 'hobbies__photographing',
    'hobbies__serving_community', 'hobbies__teaching', 'hobbies__watching_games', 'hobbies__watching_sports',
]
SOCIAL_COLS = [
    'socials__discord', 'socials__facebook', 'socials__instagram', 'socials__linkedin', 'socials__pinterest',
    'socials__reddit', 'socials__snapchat', 'socials__telegram', 'socials__tiktok', 'socials__twitch',
    'socials__twitter', 'socials__whatsapp', 'socials__youtube',
]

In [14]:
user_df = info_df.merge(tags_pivot_df, on='survey_instance')

In [15]:
user_df

,id,survey_meta_id,survey_instance,age,gender,role,favorite_game,spending,playing_time,loyalty,...,socials__linkedin,socials__pinterest,socials__reddit,socials__snapchat,socials__telegram,socials__tiktok,socials__twitch,socials__twitter,socials__whatsapp,socials__youtube
0,1,1,33cbe449-af6a-484b-a521-6a4d08f73454,37,f,10,com.my.defense,75,15,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1,5db16995-594b-4b4e-9151-e502b85d6ff3,42,m,10,com.scopely.monopolygo,5,13,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1,9722c487-9a13-4a9d-8599-577b69805034,42,f,10,com.dreamgames.royalmatch,5,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1,7094ec2f-88d4-4642-90f6-f12b41eca4f1,65,m,10,com.samfinaco.paradise,300,15,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1,eb6a4d45-c680-4eaf-bef7-aebe5edb7ce0,37,m,10,com.riotgames.league.teamfighttactics,300,8,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1965,1966,1,35fc0bbf-cef7-4ad9-b0c7-8bfb50043cc3,32,m,10,com.miniclip.eightballpool,15,8,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1966,1967,1,b11b6d9c-f739-478a-ab26-d26d11825827,32,m,10,com.nintendo.zara,0,8,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
1967,1968,1,e9c3e858-826f-479e-a85d-6ea3b0e4e43a,32,m,10,com.playtika.wsop.gp,15,8,-1,...,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
1968,1969,1,b6e5ec83-0b04-4f2d-8d54-1bc0d6785adc,32,m,4,com.bandainamcogames.dbzdokkanww,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1969,1970,1,8ec75988-2510-4d41-b5da-456e237c2574,32,m,7,com.activision.callofduty.shooter,300,8,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## User metadata preprocessing

In [16]:
user_df.gender.value_counts()

f    1002
m     945
b      22
o       1
Name: gender, dtype: int64

In [17]:
user_df['gender_female'] = user_df.gender.apply(lambda x: 1 if x == 'f' else 0)

In [18]:
user_df.age.value_counts()

32    345
42    301
21    292
65    277
52    241
37    191
27    177
47    142
18      4
Name: age, dtype: int64

### Platform

In [19]:
for col in PLATFORM_COLS:
    user_df[col] = user_df[col].apply(lambda x: 0 if pd.isna(x) else x)

### Multiplayer

In [20]:
user_df[MULTIPLAYER_COLS].isna().sum()

multiplayer__multi     80
multiplayer__single    80
dtype: int64

In [21]:
user_df[MULTIPLAYER_COLS].mode()

   multiplayer__multi  multiplayer__single
0                 3.0                  4.0

In [22]:
for col in MULTIPLAYER_COLS:
    user_df[col] = user_df[col].fillna(user_df[col].mode())

### Genres

In [23]:
genres_with_na = user_df[GENRE_COLS].isna().sum().loc[lambda x: x > 0].index.to_list()
GENRE_NA_COLS = [f'{x}_na' for x in genres_with_na]

for col, col_named in zip(genres_with_na, GENRE_NA_COLS):
    if col_named not in user_df:
        user_df[col_named] = user_df[col].apply(lambda x: 1 if pd.isna(x) else 0)
    user_df[col] = user_df[col].apply(lambda x: 0 if pd.isna(x) else x)

### Activity

In [24]:
for col in ACTIVITY_COLS:
    user_df[col] = user_df[col].apply(lambda x: 0 if pd.isna(x) else x)

### Movie

In [25]:
filled_movie = ~((~user_df[MOVIE_COLS].isna()).sum(axis=1) == 0)

for col in MOVIE_COLS:
    user_df.loc[filled_movie, col] = user_df.loc[filled_movie, col].apply(lambda x: 0 if pd.isna(x) else x)

### Hobby

In [26]:
filled_hobby = ~((~user_df[HOBBY_COLS].isna()).sum(axis=1) == 0)

for col in HOBBY_COLS:
    user_df.loc[filled_hobby, col] = user_df.loc[filled_hobby, col].apply(lambda x: 0 if pd.isna(x) else x)

### Social

In [27]:
filled_social = ~((~user_df[SOCIAL_COLS].isna()).sum(axis=1) == 0)

for col in SOCIAL_COLS:
    user_df.loc[filled_social, col] = user_df.loc[filled_social, col].apply(lambda x: 0 if pd.isna(x) else x)

# DCM datasets

## Mechanics

In [28]:
genres_dcm_df

,id,survey_meta_id,survey_instance,dcm_order,genre_1,genre_2,core_1,core_2,chosen
0,1,1,33cbe449-af6a-484b-a521-6a4d08f73454,1,genre__match,None,core__connect,core__merge,core__merge
1,2,1,33cbe449-af6a-484b-a521-6a4d08f73454,2,genre__casino,None,core__slots,core__poker,core__slots
2,3,1,33cbe449-af6a-484b-a521-6a4d08f73454,3,genre__strategy,None,core__4x,core__lane,core__lane
3,4,1,33cbe449-af6a-484b-a521-6a4d08f73454,4,genre__strategy,genre__match,core__lane,core__blast,core__blast
4,5,1,33cbe449-af6a-484b-a521-6a4d08f73454,5,genre__match,genre__strategy,core__merge,core__summon,core__summon
...,...,...,...,...,...,...,...,...,...
8940,8941,1,8ec75988-2510-4d41-b5da-456e237c2574,1,genre__combat,genre__education,core__moba,core__asymetric,core__moba
8941,8942,1,8ec75988-2510-4d41-b5da-456e237c2574,2,genre__education,genre__combat,core__vehicular,core__bullet_hell,core__bullet_hell
8942,8943,1,8ec75988-2510-4d41-b5da-456e237c2574,3,genre__puzzle,genre__casino,core__time_loop,core__poker,core__time_loop
8943,8944,1,8ec75988-2510-4d41-b5da-456e237c2574,4,genre__puzzle,genre__education,core__escape_room,core__move_blocks,core__escape_room
8944,8945,1,8ec75988-2510-4d41-b5da-456e237c2574,5,genre__puzzle,genre__education,core__time_loop,core__jigsaw,core__time_loop

In [29]:
len(genres_dcm_df.chosen.unique())

124

In [30]:
len(pd.concat([genres_dcm_df.core_1, genres_dcm_df.core_2]).unique())

123

In [31]:
genre_mechanic_dict = {}

for col in GENRE_COLS:
    temp_df = genres_dcm_df[(genres_dcm_df.genre_1 == col) & (genres_dcm_df.genre_2.isna())]
    
    genre_mechanics = list(set(pd.concat([temp_df.core_1, temp_df.core_2]).to_list()))
    genre_mechanic_dict[col] = genre_mechanics
    
mechanic_genre_dict = {mechanic: genre for genre, mechanics in genre_mechanic_dict.items() for mechanic in mechanics}

mechanic_idx_dict = {x: idx for idx, x in enumerate(mechanic_genre_dict)}
idx_mechanic_dict = {y: x for x, y in mechanic_idx_dict.items()}
    
len(mechanic_genre_dict)

123

In [32]:
cols_used = ['age'] + GENRE_COLS + GENRE_NA_COLS + TOPIC_COLS + BEHAVIOUR_COLS # 'gender_female', 

df_mech = genres_dcm_df.merge(user_df, on='survey_instance')
av_cols = []

# availablity cols
for idx, col in idx_mechanic_dict.items():
    av_col = ((df_mech.core_1 == col).astype(int) + (df_mech.core_2 == col).astype(int))
    av_col.name = f'av_{idx}'
    
    av_cols.append(av_col)

df_mech = pd.concat([df_mech] + av_cols, axis=1).copy()
df_mech[f'av_{len(idx_mechanic_dict)}'] = 1
df_mech['choice'] = df_mech['chosen'].apply(lambda x: len(idx_mechanic_dict) if x is None else mechanic_idx_dict[x])

# combined cols
new_dcm_cols = []
idx_cols_dict = {x:[] for x in idx_mechanic_dict}

for user_col in tqdm(cols_used):
    user_col_min = df_mech[user_col].min()
    user_col_max = df_mech[user_col].max()
    
    for idx, col in idx_mechanic_dict.items():
        dcm_user_col = df_mech[f'av_{idx}'] * df_mech[user_col]
        # min-max scaling -> 0-1
        dcm_user_col = (dcm_user_col - user_col_min) / (user_col_max - user_col_min)
        dcm_user_col.name = f'{col}__{user_col}'

        idx_cols_dict[idx].append(f'{col}__{user_col}')
        new_dcm_cols.append(dcm_user_col)

df_mech = pd.concat([df_mech] + new_dcm_cols, axis=1).copy()

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:02<00:00, 21.53it/s]

In [33]:
m = larch.Model()

In [34]:
m.choice_co_code = 'choice'

In [35]:
m.availability_co_vars = {idx: f'av_{idx}' for idx in range(len(idx_mechanic_dict) + 1)}

for idx, user_cols in idx_cols_dict.items():
    m.utility_co[idx] = P(f'{idx_mechanic_dict[idx]}_ASC')
    
    for user_col in user_cols:
        m.utility_co[idx] += X(user_col) * P(user_col)

m.utility_co[len(idx_mechanic_dict)] = 0

dfs = larch.DataFrames(df_mech, alt_codes=[i for i in range(len(idx_mechanic_dict) + 1)])

In [36]:
m.dataservice = dfs

In [37]:
m.load_data()

C:\Users\daide\AppData\Local\Temp/ipykernel_21908/1940460508.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  m.load_data()

In [38]:
%%time
m.maximize_loglike(quiet=False, maxiter=30)

,value,initvalue,nullvalue,minimum,maximum,holdfast,note,best
core__4x_ASC,-0.288217,0.0,0.0,-inf,inf,0,,-0.288136
core__4x__age,-0.269079,0.0,0.0,-inf,inf,0,,-0.269130
core__4x__behaviors__chill,-0.721520,0.0,0.0,-inf,inf,0,,-0.721916
core__4x__behaviors__collect,-0.445766,0.0,0.0,-inf,inf,0,,-0.445799
core__4x__behaviors__combat,0.591848,0.0,0.0,-inf,inf,0,,0.590490
...,...,...,...,...,...,...,...,...
core__word__topics__horror,0.368188,0.0,0.0,-inf,inf,0,,0.368101
core__word__topics__mystery,-0.540075,0.0,0.0,-inf,inf,0,,-0.540396
core__word__topics__realistic,0.800750,0.0,0.0,-inf,inf,0,,0.800921
core__word__topics__romance,-0.255829,0.0,0.0,-inf,inf,0,,-0.256592
core__word__topics__sci_fi,-0.400303,0.0,0.0,-inf,inf,0,,-0.401078

c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.242305509795312e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.318516118277616e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.022211352206651e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.0743517216189916e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.4328374080837507e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.3032678077835445e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.30288770538876e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.1744896886888814e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.0262630597034556e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.7770748774748296e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.4870122965877475e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.94735633434317e-33 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.615864542906958e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.533173302709678e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.9347183224070368e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.7774307943658e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.189116918267097e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.501323424380376e-35 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.56531627914589e-33 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.410323379516134e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.359992262385242e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.407548634318056e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.478221788824824e-32 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c=8944
n_cases, n_cases_local, n_alts, num_threads=(8945, 8945, 124, 12)
error in mnl_d_log_likelihood_from_dataframes_all_rows
Traceback (most recent call last):
  File "larch\model\mnl.pyx", line 650, in larch.model.mnl.mnl_d_log_likelihood_from_dataframes_all_rows
  File "c:\programs\miniconda\lib\site-packages\numpy\core\_methods.py", line 46, in _sum
    def _sum(a, axis=None, dtype=None, out=None, keepdims=False,
KeyboardInterrupt
error in maximize_loglike
Traceback (most recent call last):
  File "c:\programs\miniconda\lib\site-packages\larch\model\optimization.py", line 257, in maximize_loglike
    current_ll, tolerance, iter_bhhh, steps_bhhh, message = model.simple_fit_bhhh(
  File "larch\model\abstract_model.pyx", line 369, in larch.model.abstract_model.AbstractChoiceModel.simple_fit_bhhh
  File "larch\model\abstract_model.pyx", line 199, in larch.model.abstract_model.AbstractChoiceModel._loglike2_bhhh_tuple
  File "larch\model\controller.pyx", line 788, in larch.model.controller.Model5c.loglike2_bhhh
  File "larch\model\controller.pyx", line 635, in larch.model.controller.Model5c.__d_log_likelihood_from_dataframes_all_rows
  File "larch\model\mnl.pyx", line 693, in larch.model.mnl.mnl_d_log_likelihood_from_dataframes_all_rows
  File "larch\model\mnl.pyx", line 650, in larch.model.mnl.mnl_d_log_likelihood_from_dataframes_all_rows
  File "c:\programs\miniconda\lib\site-packages\numpy\core\_methods.py", line 46, in _sum
    def _sum(a, axis=None, dtype=None, out=None, keepdims=False,
KeyboardInterrupt

KeyboardInterrupt:

In [39]:
m.get_values()

core__4x_ASC                    -0.288217
core__4x__age                   -0.269079
core__4x__behaviors__chill      -0.721520
core__4x__behaviors__collect    -0.445766
core__4x__behaviors__combat      0.591848
                                   ...
core__word__topics__horror       0.368188
core__word__topics__mystery     -0.540075
core__word__topics__realistic    0.800750
core__word__topics__romance     -0.255829
core__word__topics__sci_fi      -0.400303
Name: value, Length: 6273, dtype: float64

### Results

In [40]:
pickle.dump(m.get_values().to_dict(), open("mechanic_coefs_2.p", "wb"))

In [41]:
pickle.load(open("mechanic_coefs_2.p", "rb"))

{'core__4x_ASC': -0.28821734003813154,
 'core__4x__age': -0.26907939704942685,
 'core__4x__behaviors__chill': -0.721519508567868,
 'core__4x__behaviors__collect': -0.44576552105507145,
 'core__4x__behaviors__combat': 0.5918475969497278,
 'core__4x__behaviors__compete': -0.2732887488012513,
 'core__4x__behaviors__complete': -0.04599465094773169,
 'core__4x__behaviors__cooperate': -0.08774136279446082,
 'core__4x__behaviors__destroy': 0.05689770468239871,
 'core__4x__behaviors__discover': 0.31786734080878,
 'core__4x__behaviors__empower': 0.8337100954705845,
 'core__4x__behaviors__experiment': -0.21595277706346722,
 'core__4x__behaviors__express': -0.07542662979010684,
 'core__4x__behaviors__immerse': 0.7484224865352311,
 'core__4x__behaviors__plan': 0.5829705553833191,
 'core__4x__behaviors__react': -0.36743293941658983,
 'core__4x__behaviors__solve': 0.2875541709602418,
 'core__4x__genre__arcade': 0.7103442010168542,
 'core__4x__genre__building': 3.111070677803588,
 'core__4x__genre__building_na': 1.8721941880723894,
 'core__4x__genre__casino': 0.3990364579136189,
 'core__4x__genre__combat': -0.445715921055846,
 'core__4x__genre__driving': 0.8697503426565923,
 'core__4x__genre__driving_na': -0.08007218090604071,
 'core__4x__genre__education': -0.723546879715271,
 'core__4x__genre__education_na': -0.7988549550379124,
 'core__4x__genre__idle': 0.1466875145958885,
 'core__4x__genre__idle_na': -0.10819308772650826,
 'core__4x__genre__match': 0.8122866811557553,
 'core__4x__genre__party': 0.6536726089782859,
 'core__4x__genre__party_na': 0.348709521810787,
 'core__4x__genre__puzzle': -0.31408810967867873,
 'core__4x__genre__rpg': 0.7705430323675828,
 'core__4x__genre__simulation': -0.40311445316933353,
 'core__4x__genre__sports': -0.670877807862398,
 'core__4x__genre__sports_na': -0.8172791699125532,
 'core__4x__genre__story': -2.0253846276431093,
 'core__4x__genre__story_na': -1.5214071071976372,
 'core__4x__genre__strategy': -0.28821762062956163,
 'core__4x__genre__tabletop': -0.1968293781081448,
 'core__4x__genre__tabletop_na': -0.6243332760751393,
 'core__4x__topics__action': 0.1501283938584784,
 'core__4x__topics__adventure': 0.13386527765592018,
 'core__4x__topics__comedy': -1.1580490725879338,
 'core__4x__topics__drama': 0.07492640383968492,
 'core__4x__topics__fantasy': 0.8216551167798709,
 'core__4x__topics__horror': 0.0887800585657974,
 'core__4x__topics__mystery': 0.276168081935362,
 'core__4x__topics__realistic': 0.23810230004573818,
 'core__4x__topics__romance': 1.0506578402502624,
 'core__4x__topics__sci_fi': 0.8660084999371006,
 'core__agriculture_ASC': -2.0959882897288757,
 'core__agriculture__age': 3.14950042354948,
 'core__agriculture__behaviors__chill': 4.223846025373782,
 'core__agriculture__behaviors__collect': -2.130347503212598,
 'core__agriculture__behaviors__combat': 0.783652429227573,
 'core__agriculture__behaviors__compete': -0.8294282247740483,
 'core__agriculture__behaviors__complete': 6.280428778640911,
 'core__agriculture__behaviors__cooperate': -3.2172671574240215,
 'core__agriculture__behaviors__destroy': -0.366343882534545,
 'core__agriculture__behaviors__discover': -1.6953535294093665,
 'core__agriculture__behaviors__empower': 1.7659720383221018,
 'core__agriculture__behaviors__experiment': 0.773409895015108,
 'core__agriculture__behaviors__express': 2.706969876792557,
 'core__agriculture__behaviors__immerse': -0.2756361441098669,
 'core__agriculture__behaviors__plan': -0.7806421392194901,
 'core__agriculture__behaviors__react': -0.21085967497003724,
 'core__agriculture__behaviors__solve': -0.6501501422902269,
 'core__agriculture__genre__arcade': -4.288177890622192,
 'core__agriculture__genre__building': 4.644164008249457,
 'core__agriculture__genre__building_na': -0.27265829738368164,
 'core__agriculture__genre__casino': 0.18543448977583102,
 'core__agriculture__genre__combat': 2.876421999500415,
 'core__agriculture__genre__driving': -1.0080392038601615,
 'core__agriculture__genre__driving_na': -6.919795896425447,
 'core__agriculture__genre__education': 0.18789501471141087,
 'core__agriculture__genre__education_na': -4.629593285741716,
 'core__agriculture__genre__idle': 3.337811277908526,
 'core__agriculture__genre__idle_na': 0.7430505262882692,
 'core__agriculture__genre__match': 5.410768337837694,
 'core__agriculture__genre__party': 15.969129261131723,
 'core__agriculture__genre__party_na': 7.080322877613472,
 'core__agriculture__genre__puzzle': -1.1437889318963321,
 'core__agriculture__genre__rpg': 3.581857320119953,
 'core__agriculture__genre__simulation': -2.095990201773486,
 'core__agriculture__genre__sports': -1.354075231333423,
 'core__agriculture__genre__sports_na': -5.012565258227523,
 'core__agriculture__genre__story': -0.253525275096236,
 'core__agriculture__genre__story_na': -2.1933729944053817,
 'core__agriculture__genre__strategy': 0.933097364508601,
 'core__agriculture__genre__tabletop': 5.657273392448139,
 'core__agriculture__genre__tabletop_na': -1.3712415111326002,
 'core__agriculture__topics__action': 0.5192212336316042,
 'core__agriculture__topics__adventure': -4.713134522079701,
 'core__agriculture__topics__comedy': -1.6366143421053119,
 'core__agriculture__topics__drama': -3.874839165195889,
 'core__agriculture__topics__fantasy': -3.0505778476429937,
 'core__agriculture__topics__horror': 3.238995895531519,
 'core__agriculture__topics__mystery': 2.4059904872882925,
 'core__agriculture__topics__realistic': -1.5888357153503188,
 'core__agriculture__topics__romance': 5.940051879917583,
 'core__agriculture__topics__sci_fi': 2.355201509035006,
 'core__artillery_ASC': 0.2216503491381699,
 'core__artillery__age': 2.887372909074013,
 'core__artillery__behaviors__chill': 1.0554767186942187,
 'core__artillery__behaviors__collect': -2.779875499862945,
 'core__artillery__behaviors__combat': -0.9828665963424639,
 'core__artillery__behaviors__compete': 0.11359430238826827,
 'core__artillery__behaviors__complete': -2.2031885045820148,
 'core__artillery__behaviors__cooperate': -0.1306145918241258,
 'core__artillery__behaviors__destroy': 0.5997081962534022,
 'core__artillery__behaviors__discover': 1.3452021106978262,
 'core__artillery__behaviors__empower': 0.896008230956752,
 'core__artillery__behaviors__experiment': 0.1255441232991287,
 'core__artillery__behaviors__express': -1.2551100039281258,
 'core__artillery__behaviors__immerse': -0.702349083525596,
 'core__artillery__behaviors__plan': 0.4624114326923598,
 'core__artillery__behaviors__react': 1.3327089975200936,
 'core__artillery__behaviors__solve': -0.4947314419025927,
 'core__artillery__genre__arcade': -1.0930297624102452,
 'core__artillery__genre__building': -2.3832987004416455,
 'core__artillery__genre__building_na': -0.5221889332861461,
 'core__artillery__genre__casino': -4.801113440341406,
 'core__artillery__genre__combat': 0.22169044518785508,
 'core__artillery__genre__driving': -4.331174491288127,
 'core__artillery__genre__driving_na': -1.6448325277119558,
 'core__artillery__genre__education': -0.17692326689388493,
 'core__artillery__genre__education_na': 0.603115641173363,
 'core__artillery__genre__idle': -0.15164591282297613,
 'core__artillery__genre__idle_na': 1.7541095401397846,
 'core__artillery__genre__match': 0.7797038971227123,
 'core__artillery__genre__party': 6.443662166246322,
 'core__artillery__genre__party_na': 6.041631251123454,
 'core__artillery__genre__puzzle': 2.612804599965354,
 'core__artillery__genre__rpg': -0.6720093281834923,
 'core__artillery__genre__simulation': 0.24787728798735859,
 'core__artillery__genre__sports': 1.888022018913047,
 'core__artillery__genre__sports_na': 3.0362630491306013,
 'core__artillery__genre__story': -22.213374617409457,
 'core__artillery__genre__story_na': -11.131456634122658,
 'core__artillery__genre__strategy': 2.7380395738283303,
 'core__artillery__genre__tabletop': 4.313914427042348,
 'core__artillery__genre__tabletop_na': 3.1935342085156675,
 'core__artillery__topics__action': 2.522744343397042,
 'core__artillery__topics__adventure': -0.5065936751332787,
 'core__artillery__topics__comedy': -0.2477784215083373,
 'core__artillery__topics__drama': -1.4338564800297664,
 'core__artillery__topics__fantasy': 3.924468064841632,
 'core__artillery__topics__horror': -0.4022115782970544,
 'core__artillery__topics__mystery': -2.7381112336307525,
 'core__artillery__topics__realistic': 1.7483543375254276,
 'core__artillery__topics__romance': 2.228788590266511,
 'core__artillery__topics__sci_fi': 0.24305420039339726,
 'core__asymetric_ASC': 0.07769599995876796,
 'core__asymetric__age': -1.1695401740612814,
 'core__asymetric__behaviors__chill': 0.06485812504813004,
 'core__asymetric__behaviors__collect': 0.683365605439064,
 'core__asymetric__behaviors__combat': 2.2180871672586377,
 'core__asymetric__behaviors__compete': 1.9944874408248774,
 'core__asymetric__behaviors__complete': -1.1118970955792873,
 'core__asymetric__behaviors__cooperate': -0.8552216347118798,
 'core__asymetric__behaviors__destroy': 1.0770948429464666,
 'core__asymetric__behaviors__discover': -1.093263304963066,
 'core__asymetric__behaviors__empower': -0.3136601037898961,
 'core__asymetric__behaviors__experiment': 1.3122047717440393,
 'core__asymetric__behaviors__express': -0.5080169004706993,
 'core__asymetric__behaviors__immerse': 0.9524883876896554,
 'core__asymetric__behaviors__plan': -0.2767830523641303,
 'core__asymetric__behaviors__react': 0.637392300098684,
 'core__asymetric__behaviors__solve': 1.2774655038596485,
 'core__asymetric__genre__arcade': -3.2286757668292294,
 'core__asymetric__genre__building': 3.551917915067183,
 'core__asymetric__genre__building_na': 3.2150504853672572,
 'core__asymetric__genre__casino': -1.5554132018335998,
 'core__asymetric__genre__combat': 0.07767225716862311,
 'core__asymetric__genre__driving': -5.098492944581143,
 'core__asymetric__genre__driving_na': -3.1362498200208844,
 'core__asymetric__genre__education': -1.3603883194650437,
 'core__asymetric__genre__education_na': -0.5296852565719964,
 'core__asymetric__genre__idle': -1.7521569436183266,
 'core__asymetric__genre__idle_na': 0.9532924428413229,
 'core__asymetric__genre__match': 1.5615067579619957,
 'core__asymetric__genre__party': 2.21431807669555,
 'core__asymetric__genre__party_na': 4.252415155167136,
 'core__asymetric__genre__puzzle': -1.6650704186494563,
 'core__asymetric__genre__rpg': -1.0796814061935192,
 'core__asymetric__genre__simulation': 0.12322061955236782,
 'core__asymetric__genre__sports': -2.6235066722767026,
 'core__asymetric__genre__sports_na': -1.1312477266578995,
 'core__asymetric__genre__story': -3.435909428559415,
 'core__asymetric__genre__story_na': -0.4610685249745586,
 'core__asymetric__genre__strategy': 2.7945334523785688,
 'core__asymetric__genre__tabletop': -5.1314233966351415,
 'core__asymetric__genre__tabletop_na': -2.696481915723409,
 'core__asymetric__topics__action': -1.9658134344991527,
 'core__asymetric__topics__adventure': -1.915937170887683,
 'core__asymetric__topics__comedy': -1.0827389683828106,
 'core__asymetric__topics__drama': 1.3946240235359133,
 'core__asymetric__topics__fantasy': -0.2743166223332697,
 'core__asymetric__topics__horror': 0.822698953238777,
 'core__asymetric__topics__mystery': 2.357364858476984,
 'core__asymetric__topics__realistic': 2.00524192656513,
 'core__asymetric__topics__romance': -0.01294640408139479,
 'core__asymetric__topics__sci_fi': 1.058445332511344,
 'core__auto_chess_ASC': -0.3468152219897701,
 'core__auto_chess__age': 0.5678372617249163,
 'core__auto_chess__behaviors__chill': 0.05320500849014772,
 'core__auto_chess__behaviors__collect': -0.10493828527984228,
 'core__auto_chess__behaviors__combat': -0.045397579130418586,
 'core__auto_chess__behaviors__compete': -0.24623852601986632,
 'core__auto_chess__behaviors__complete': -0.7790686761442495,
 'core__auto_chess__behaviors__cooperate': 0.047883073519035146,
 'core__auto_chess__behaviors__destroy': 0.438724702401851,
 'core__auto_chess__behaviors__discover': -1.2133279132737873,
 'core__auto_chess__behaviors__empower': 0.2202687474969784,
 'core__auto_chess__behaviors__experiment': 0.11963263558594772,
 'core__auto_chess__behaviors__express': -0.21122575341007,
 'core__auto_chess__behaviors__immerse': 1.188045053153985,
 'core__auto_chess__behaviors__plan': 1.7591842306663763,
 'core__auto_chess__behaviors__react': -1.0154261553916475,
 'core__auto_chess__behaviors__solve': -0.582753226115936,
 'core__auto_chess__genre__arcade': -0.3391714692152923,
 'core__auto_chess__genre__building': 1.042823229981721,
 'core__auto_chess__genre__building_na': -0.007530597857355447,
 'core__auto_chess__genre__casino': 0.26463266624041076,
 'core__auto_chess__genre__combat': 0.12895986133226836,
 'core__auto_chess__genre__driving': 0.38723011280542585,
 'core__auto_chess__genre__driving_na': 0.024875196000192362,
 'core__auto_chess__genre__education': -0.7768096806174124,
 'core__auto_chess__genre__education_na': -1.4120757024199866,
 'core__auto_chess__genre__idle': 2.18572098916934,
 'core__auto_chess__genre__idle_na': 0.9690806174317584,
 'core__auto_chess__genre__match': 1.3572928717163593,
 'core__auto_chess__genre__party': 1.0084180176099704,
 'core__auto_chess__genre__party_na': 0.23151014227188682,
 'core__auto_chess__genre__puzzle': 0.6814211165626871,
 'core__auto_chess__genre__rpg': 0.6032036154099137,
 'core__auto_chess__genre__simulation': 0.4860183016535301,
 'core__auto_chess__genre__sports': -0.7586775427117893,
 'core__auto_chess__genre__sports_na': -0.7247207077944281,
 'core__auto_chess__genre__story': -1.9144512010920078,
 'core__auto_chess__genre__story_na': -1.099493129177307,
 'core__auto_chess__genre__strategy': -0.3468144897137741,
 'core__auto_chess__genre__tabletop': 0.2589131850434509,
 'core__auto_chess__genre__tabletop_na': -0.0625380171060963,
 'core__auto_chess__topics__action': 0.5653366784897694,
 'core__auto_chess__topics__adventure': -0.10189063266004386,
 'core__auto_chess__topics__comedy': -0.7844823359904001,
 'core__auto_chess__topics__drama': 0.2671781715838151,
 'core__auto_chess__topics__fantasy': 0.5264239043575647,
 'core__auto_chess__topics__horror': 0.02782882403820906,
 'core__auto_chess__topics__mystery': -0.08305661898076581,
 'core__auto_chess__topics__realistic': 1.0733584251445891,
 'core__auto_chess__topics__romance': 0.6938636903228959,
 'core__auto_chess__topics__sci_fi': 0.37552240665516196,
 'core__automation_ASC': -0.6695369824540995,
 'core__automation__age': -0.1746968181822831,
 'core__automation__behaviors__chill': 0.10187455986075226,
 'core__automation__behaviors__collect': -0.15344713400902546,
 'core__automation__behaviors__combat': -1.0624051886827393,
 'core__automation__behaviors__compete': -0.9896620053065868,
 'core__automation__behaviors__complete': -0.1005668547658183,
 'core__automation__behaviors__cooperate': -0.006350072816701036,
 'core__automation__behaviors__destroy': 0.7585370432833174,
 'core__automation__behaviors__discover': -0.5096234675324564,
 'core__automation__behaviors__empower': 1.1375226158832836,
 'core__automation__behaviors__experiment': -0.9476158694693784,
 'core__automation__behaviors__express': 3.290957743983661,
 'core__automation__behaviors__immerse': -2.1237590234852397,
 'core__automation__behaviors__plan': 2.010033524259852,
 'core__automation__behaviors__react': -0.9526422386998477,
 'core__automation__behaviors__solve': 2.9348952005763294,
 'core__automation__genre__arcade': -0.003679848462884699,
 'core__automation__genre__building': 5.564171262700527,
 'core__automation__genre__building_na': 1.1860141015145695,
 'core__automation__genre__casino': 0.5245918624985786,
 'core__automation__genre__combat': -1.5932024927283037,
 'core__automation__genre__driving': 0.8626198010428003,
 'core__automation__genre__driving_na': -0.9657854223542511,
 'core__automation__genre__education': 2.6814598814659183,
 'core__automation__genre__education_na': 0.627217405925877,
 'core__automation__genre__idle': 0.8083035550246115,
 'core__automation__genre__idle_na': -0.31417056492178863,
 'core__automation__genre__match': 1.3423120871519434,
 'core__automation__genre__party': 0.0733018958607547,
 'core__automation__genre__party_na': -1.1630196550438758,
 'core__automation__genre__puzzle': -1.4820973302813025,
 'core__automation__genre__rpg': 3.784519168164872,
 'core__automation__genre__simulation': -0.6695347448840061,
 'core__automation__genre__sports': -4.198058975588289,
 'core__automation__genre__sports_na': -3.8104043558323704,
 'core__automation__genre__story': -2.8177720850604913,
 'core__automation__genre__story_na': -3.7463849598479335,
 'core__automation__genre__strategy': -2.14375302385209,
 'core__automation__genre__tabletop': 9.515014392376367,
 'core__automation__genre__tabletop_na': 4.169318825716725,
 'core__automation__topics__action': 2.2097547724685267,
 'core__automation__topics__adventure': 0.09132124532257396,
 'core__automation__topics__comedy': 1.5172006407137815,
 'core__automation__topics__drama': -0.06610870929179836,
 'core__automation__topics__fantasy': 0.6040614630316171,
 'core__automation__topics__horror': 1.648405439573645,
 'core__automation__topics__mystery': -0.48186801856272077,
 'core__automation__topics__realistic': -2.4364997605498266,
 'core__automation__topics__romance': -0.9561233280353522,
 'core__automation__topics__sci_fi': -1.440889475880653,
 'core__backtracking_ASC': -0.4774034734297917,
 'core__backtracking__age': -0.27343709633037316,
 'core__backtracking__behaviors__chill': 0.30460395958063824,
 'core__backtracking__behaviors__collect': -0.6988708434949452,
 'core__backtracking__behaviors__combat': -0.3636398436717871,
 'core__backtracking__behaviors__compete': 0.16284812722923903,
 'core__backtracking__behaviors__complete': -1.129343701640703,
 'core__backtracking__behaviors__cooperate': -0.3998399343648634,
 'core__backtracking__behaviors__destroy': 0.43872243107414033,
 'core__backtracking__behaviors__discover': 1.487412136008244,
 'core__backtracking__behaviors__empower': 0.9824240312585645,
 'core__backtracking__behaviors__experiment': -0.07529536056826754,
 'core__backtracking__behaviors__express': 0.9861771086435528,
 'core__backtracking__behaviors__immerse': -0.48352701202787474,
 'core__backtracking__behaviors__plan': 1.7689005395131583,
 'core__backtracking__behaviors__react': 0.4999662865147486,
 'core__backtracking__behaviors__solve': 0.845297847396514,
 'core__backtracking__genre__arcade': 0.24123978956870148,
 'core__backtracking__genre__building': 0.01223833677853639,
 'core__backtracking__genre__building_na': -0.4969074240232649,
 'core__backtracking__genre__casino': -0.5056230544669515,
 'core__backtracking__genre__combat': 0.8481599959060302,
 'core__backtracking__genre__driving': -1.0628354928004504,
 'core__backtracking__genre__driving_na': -0.5905683506225162,
 'core__backtracking__genre__education': -0.7148348328143725,
 'core__backtracking__genre__education_na': -1.0248475913011337,
 'core__backtracking__genre__idle': 0.8479250951988755,
 'core__backtracking__genre__idle_na': -0.20633199252865123,
 'core__backtracking__genre__match': 2.2738120484673963,
 'core__backtracking__genre__party': 0.2570005784137425,
 'core__backtracking__genre__party_na': 0.07748617690911198,
 'core__backtracking__genre__puzzle': -0.4774021879483034,
 'core__backtracking__genre__rpg': -0.2620908964363094,
 'core__backtracking__genre__simulation': 0.4677491257089617,
 'core__backtracking__genre__sports': 0.34159415848562197,
 'core__backtracking__genre__sports_na': -0.5025497561993149,
 'core__backtracking__genre__story': -0.7644766967846762,
 'core__backtracking__genre__story_na': -0.315133568195,
 'core__backtracking__genre__strategy': -0.4086113974305734,
 'core__backtracking__genre__tabletop': 0.0630202049273641,
 'core__backtracking__genre__tabletop_na': 0.19444643233689057,
 'core__backtracking__topics__action': -0.31894487918292797,

## Topics - 4 datasets

In [42]:
topic_dcm_df

,id,survey_meta_id,survey_instance,dcm_order,topic,feature_1a,feature_1b,feature_2a,feature_2b,chosen_a,chosen_b
0,1,1,33cbe449-af6a-484b-a521-6a4d08f73454,1,topics__fantasy,entities__robot,roles__creator,entities__celestial,roles__team,None,None
1,2,1,33cbe449-af6a-484b-a521-6a4d08f73454,2,topics__fantasy,entities__kid,roles__carer,entities__animal,roles__warrior,None,None
2,3,1,33cbe449-af6a-484b-a521-6a4d08f73454,3,topics__fantasy,environment__aquatic,domains__crime,environment__alternality,domains__business,environment__aquatic,domains__crime
3,4,1,33cbe449-af6a-484b-a521-6a4d08f73454,4,topics__fantasy,entities__adult,roles__rebel,entities__zombie,roles__creator,entities__zombie,roles__creator
4,5,1,33cbe449-af6a-484b-a521-6a4d08f73454,5,topics__fantasy,environment__wilderness,focus__weapons,environment__space,domains__military,None,None
...,...,...,...,...,...,...,...,...,...,...,...
6985,6986,1,8ec75988-2510-4d41-b5da-456e237c2574,1,topics__mystery,entities__celestial,roles__mystic,entities__plant,roles__follower,entities__plant,roles__follower
6986,6987,1,8ec75988-2510-4d41-b5da-456e237c2574,2,topics__mystery,entities__super_,roles__warrior,entities__celestial,roles__creator,entities__super_,roles__warrior
6987,6988,1,8ec75988-2510-4d41-b5da-456e237c2574,3,topics__mystery,entities__human,roles__team,entities__robot,roles__carer,entities__human,roles__team
6988,6989,1,8ec75988-2510-4d41-b5da-456e237c2574,4,topics__mystery,entities__alien,roles__solver,entities__celestial,roles__mystic,entities__alien,roles__solver
6989,6990,1,8ec75988-2510-4d41-b5da-456e237c2574,5,topics__mystery,eras__renaissance,domains__family,environment__urban,domains__health,eras__renaissance,domains__family

In [64]:
# Entity / era + enviro
topic_dcm_df.feature_1a.unique()

array(['entities__robot', 'entities__kid', 'environment__aquatic',
       'entities__adult', 'environment__wilderness', 'entities__alien',
       'eras__prehistoric', 'eras__medieval', 'entities__zombie',
       'entities__elder', 'eras__near_future', 'environment__alternality',
       'entities__super_', 'environment__space', 'eras__industrial',
       'environment__suburban', 'entities__human', 'entities__celestial',
       'eras__renaissance', 'eras__ancient', 'entities__microbe',
       'eras__timeless', 'eras__modern', 'entities__plant',
       'entities__monster', 'environment__rural', 'entities__animal',
       'environment__virtuality', 'eras__retro', 'environment__urban'],
      dtype=object)

In [65]:
# Role / domain + focus
topic_dcm_df.feature_1b.unique()

array(['roles__creator', 'roles__carer', 'domains__crime', 'roles__rebel',
       'focus__weapons', 'roles__authority', 'focus__structures',
       'domains__military', 'roles__solver', 'domains__food',
       'roles__explorer', 'domains__health', 'domains__art',
       'roles__team', 'roles__follower', 'roles__mystic',
       'focus__solutions', 'domains__luxury', 'focus__levels',
       'focus__events', 'roles__warrior', 'focus__cities',
       'domains__sports', 'domains__fashion', 'domains__rights',
       'focus__actors', 'domains__religion', 'domains__nature',
       'focus__vehicles', 'focus__interiors', 'roles__villain',
       'domains__politics', 'focus__bases', 'focus__self',
       'domains__family', 'focus__objects', 'domains__mythology',
       'domains__business'], dtype=object)

### Split datasets

In [66]:
dataset_split = topic_dcm_df.feature_1a.apply(lambda x: x.startswith('entities__'))
dataset_split

0        True
1        True
2       False
3        True
4       False
        ...
6985     True
6986     True
6987     True
6988     True
6989    False
Name: feature_1a, Length: 6990, dtype: bool

In [67]:
topic_dcm_df1 = topic_dcm_df[dataset_split].copy()
topic_dcm_df2 = topic_dcm_df[~dataset_split].copy()

In [68]:
entity_idx_dict = {x: idx for idx, x in enumerate(sorted(topic_dcm_df1.feature_1a.unique()))}
idx_entity_dict = {y: x for x, y in entity_idx_dict.items()}

role_idx_dict = {x: idx for idx, x in enumerate(sorted(topic_dcm_df1.feature_1b.unique()))}
idx_role_dict = {y: x for x, y in role_idx_dict.items()}

era_enviro_idx_dict = {x: idx for idx, x in enumerate(sorted(topic_dcm_df2.feature_1a.unique()))}
idx_era_enviro_dict = {y: x for x, y in era_enviro_idx_dict.items()}

domain_focus_idx_dict = {x: idx for idx, x in enumerate(sorted(topic_dcm_df2.feature_1b.unique()))}
idx_domain_focus_dict = {y: x for x, y in domain_focus_idx_dict.items()}

## Entity

In [69]:
cols_used = ['age'] + GENRE_COLS + GENRE_NA_COLS + TOPIC_COLS + BEHAVIOUR_COLS # 'gender_female', 

df_ent = topic_dcm_df1.merge(user_df, on='survey_instance')
av_cols = []

# availablity cols
for idx, col in idx_entity_dict.items():
    av_col = ((df_ent.feature_1a == col).astype(int) + (df_ent.feature_2a == col).astype(int))
    av_col.name = f'av_{idx}'
    
    av_cols.append(av_col)

df_ent = pd.concat([df_ent] + av_cols, axis=1).copy()
df_ent[f'av_{len(idx_entity_dict)}'] = 1
df_ent['choice'] = df_ent['chosen_a'].apply(lambda x: len(idx_entity_dict) if x is None else entity_idx_dict[x])

# combined cols
new_dcm_cols = []
idx_cols_dict = {x:[] for x in idx_entity_dict}

for user_col in tqdm(cols_used):
    user_col_min = df_ent[user_col].min()
    user_col_max = df_ent[user_col].max()
    
    for idx, col in idx_entity_dict.items():
        dcm_user_col = df_ent[f'av_{idx}'] * df_ent[user_col]
        # min-max scaling -> 0-1
        dcm_user_col = (dcm_user_col - user_col_min) / (user_col_max - user_col_min)
        dcm_user_col.name = f'{col}__{user_col}'

        idx_cols_dict[idx].append(f'{col}__{user_col}')
        new_dcm_cols.append(dcm_user_col)

df_ent = pd.concat([df_ent] + new_dcm_cols, axis=1).copy()

100%|█████████████████████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 248.50it/s]

In [70]:
m = larch.Model()

In [71]:
m.choice_co_code = 'choice'

In [72]:
m.availability_co_vars = {idx: f'av_{idx}' for idx in range(len(idx_entity_dict) + 1)}

for idx, user_cols in idx_cols_dict.items():
    m.utility_co[idx] = P(f'{idx_entity_dict[idx]}_ASC')
    
    for user_col in user_cols:
        m.utility_co[idx] += X(user_col) * P(user_col)

m.utility_co[len(idx_entity_dict)] = 0

dfs = larch.DataFrames(df_ent, alt_codes=[i for i in range(len(idx_entity_dict) + 1)])

In [73]:
m.dataservice = dfs

In [74]:
m.load_data()

C:\Users\daide\AppData\Local\Temp/ipykernel_12476/1940460508.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  m.load_data()

In [75]:
%%time
m.maximize_loglike(quiet=False)

,value,initvalue,nullvalue,minimum,maximum,holdfast,note,best
entities__adult_ASC,-89.180184,0.0,0.0,-inf,inf,0,,-89.180184
entities__adult__age,0.749316,0.0,0.0,-inf,inf,0,,0.749316
entities__adult__behaviors__chill,1.616049,0.0,0.0,-inf,inf,0,,1.616049
entities__adult__behaviors__collect,-0.520942,0.0,0.0,-inf,inf,0,,-0.520942
entities__adult__behaviors__combat,-0.214125,0.0,0.0,-inf,inf,0,,-0.214125
...,...,...,...,...,...,...,...,...
entities__zombie__topics__horror,1.655545,0.0,0.0,-inf,inf,0,,1.655545
entities__zombie__topics__mystery,0.097042,0.0,0.0,-inf,inf,0,,0.097042
entities__zombie__topics__realistic,0.291333,0.0,0.0,-inf,inf,0,,0.291333
entities__zombie__topics__romance,-0.753396,0.0,0.0,-inf,inf,0,,-0.753396
entities__zombie__topics__sci_fi,2.207079,0.0,0.0,-inf,inf,0,,2.207079

c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.988205314391124e-06 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.7755591486768624e-14 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.4025100042990448e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.7377880584179465e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.388251871565744e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.4434564051990983e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.8344467550162956e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.1434752753839527e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.99969477752447e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.7809780714085765e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.402513106346591e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.8913785721376016e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.373496166269275e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.730158335482278e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.327518520294578e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.335689503180909e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.217723289269808e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.888911267204629e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.152541320295586e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.522087865978124e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.706017571540218e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.4650000886066584e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.23910372915788e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.120826776064494e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.4161025599077985e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.22204039946512e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.901670856510735e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.510982265615157e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.1403431101282729e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.818124300847253e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.9225708315610615e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.500000401121485e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.450229226535876e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.306539858773528e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.840030534451405e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.5474760365757664e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.593298886044826e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.001068611393447e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 7.993935800101884e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.3806130531678954e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 7.372553888347384e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.454656045935168e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 7.583182629509711e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.15453822580807e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.0282849760245546e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.2895808776388237e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.510955381091191e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.03194441279376e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.118582091814879e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.5334839103254994e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 7.384326776823508e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.100204773941062e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.993851300529666e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.4198069307624732e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.887734820251485e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.365409325567e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.881666640115345e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.6292483978063203e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.350967436139496e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 7.243362809515095e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.572481403121778e-17 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.8469022862259885e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.9515261358215747e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 7.394958155538492e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.4685538829841873e-18 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.896926312066085e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.9359008260409154e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.037816270450676e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.3132265813244186e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.590489166155029e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.3469734166112514e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.1939085162310557e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.589340083599495e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.9634242872188377e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.729664499704272e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.854958345030549e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.831813760462411e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 7.762944201072147e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.892992596475794e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.172751528129738e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 7.501539294647688e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.190895305263833e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.963629029487908e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 7.660087843079617e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.627072907813165e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.281263311157374e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.8052418320837166e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.588752436615759e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.921677323181885e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.714600676585389e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.156525537958453e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.809750294517889e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.55358369512822e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")

Wall time: 2min

┣          loglike: -2112.6262801781268
┣                x: entities__adult_ASC                   -89.180184
┃                   entities__adult__age                    0.749316
┃                   entities__adult__behaviors__chill       1.616049
┃                   entities__adult__behaviors__collect    -0.520942
┃                   entities__adult__behaviors__combat     -0.214125
┃                                                            ...
┃                   entities__zombie__topics__horror        1.655545
┃                   entities__zombie__topics__mystery       0.097042
┃                   entities__zombie__topics__realistic     0.291333
┃                   entities__zombie__topics__romance      -0.753396
┃                   entities__zombie__topics__sci_fi        2.207079
┃                   Length: 663, dtype: float64
┣        tolerance: 9.584537943065642e-06
┣            steps: array([1.   , 1.   , 0.5  , 0.5  , 0.5  , 0.5  , 0.5  , 0.5  , 0.5  ,
┃                          0.5  , 0.25 , 0.25 , 0.25 , 0.25 , 0.25 , 0.25 , 0.125, 0.125,
┃                          0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
┃                          0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
┃                          0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
┃                          0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
┃                          0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
┃                          0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
┃                          0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
┃                          0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
┃                          0.125, 0.125, 0.125, 0.125, 0.125])
┣          message: 'Optimization terminated successfully.'
┣     elapsed_time: datetime.timedelta(seconds=120, microseconds=368409)
┣           method: 'bhhh'
┣          n_cases: 3046
┣ iteration_number: 95
┣          logloss: 0.6935739593493522

### Results

In [76]:
pickle.dump(m.get_values().to_dict(), open("entity_coefs_2.p", "wb"))

In [77]:
pickle.load(open("entity_coefs_2.p", "rb"))

{'entities__adult_ASC': -89.18018371080203,
 'entities__adult__age': 0.7493159712045754,
 'entities__adult__behaviors__chill': 1.6160489878049307,
 'entities__adult__behaviors__collect': -0.5209415571477631,
 'entities__adult__behaviors__combat': -0.2141252634882337,
 'entities__adult__behaviors__compete': 0.6482232938775078,
 'entities__adult__behaviors__complete': -1.9773429660757311,
 'entities__adult__behaviors__cooperate': 1.5110483266727397,
 'entities__adult__behaviors__destroy': -0.03727283801361043,
 'entities__adult__behaviors__discover': -0.19925106992945502,
 'entities__adult__behaviors__empower': 1.5560942855725797,
 'entities__adult__behaviors__experiment': 0.10514911892305662,
 'entities__adult__behaviors__express': -1.660219047857826,
 'entities__adult__behaviors__immerse': 0.1972442165887669,
 'entities__adult__behaviors__plan': 0.14392805862872293,
 'entities__adult__behaviors__react': 0.3033338668309503,
 'entities__adult__behaviors__solve': 0.7976565439879272,
 'entities__adult__genre__arcade': 0.2969469452634744,
 'entities__adult__genre__building': 1.5404615747969073,
 'entities__adult__genre__building_na': 14.523488536261711,
 'entities__adult__genre__casino': 0.1413268054370675,
 'entities__adult__genre__combat': -0.6541971105489323,
 'entities__adult__genre__driving': 0.2841776850697945,
 'entities__adult__genre__driving_na': 13.856040666439839,
 'entities__adult__genre__education': -0.8521592141871949,
 'entities__adult__genre__education_na': 13.422178635802943,
 'entities__adult__genre__idle': 1.3601882966751877,
 'entities__adult__genre__idle_na': 14.782503104677048,
 'entities__adult__genre__match': -0.04861667564944215,
 'entities__adult__genre__party': 0.059759808631142046,
 'entities__adult__genre__party_na': 13.788848477437444,
 'entities__adult__genre__puzzle': 1.3557006885701577,
 'entities__adult__genre__rpg': 0.22535249352149775,
 'entities__adult__genre__simulation': 0.15449329052494518,
 'entities__adult__genre__sports': -0.1395493161469183,
 'entities__adult__genre__sports_na': 13.626928412965098,
 'entities__adult__genre__story': 1.7328240589199533,
 'entities__adult__genre__story_na': 15.145238331444911,
 'entities__adult__genre__strategy': 0.284040120005703,
 'entities__adult__genre__tabletop': -1.6280478848159754,
 'entities__adult__genre__tabletop_na': 13.170792959583512,
 'entities__adult__topics__action': -0.3935397319534241,
 'entities__adult__topics__adventure': 0.7341104561289429,
 'entities__adult__topics__comedy': 0.007765052852115641,
 'entities__adult__topics__drama': 0.15591342105449324,
 'entities__adult__topics__fantasy': 0.4018955004865209,
 'entities__adult__topics__horror': 0.1312016185865145,
 'entities__adult__topics__mystery': 1.1157206526452348,
 'entities__adult__topics__realistic': 0.32813264072936166,
 'entities__adult__topics__romance': 0.4294306307392004,
 'entities__adult__topics__sci_fi': 1.9932365424924783,
 'entities__alien_ASC': 2.4577258421323225,
 'entities__alien__age': 0.35228107210809667,
 'entities__alien__behaviors__chill': 0.8174289716998613,
 'entities__alien__behaviors__collect': 0.2552955040787098,
 'entities__alien__behaviors__combat': -0.560254936137134,
 'entities__alien__behaviors__compete': 1.0661026277234615,
 'entities__alien__behaviors__complete': -1.3442198984774905,
 'entities__alien__behaviors__cooperate': 1.3598749307755604,
 'entities__alien__behaviors__destroy': 0.2709973229844843,
 'entities__alien__behaviors__discover': 0.7386583112190606,
 'entities__alien__behaviors__empower': 0.6629017041792743,
 'entities__alien__behaviors__experiment': -0.22127808629157283,
 'entities__alien__behaviors__express': -1.4567273646194856,
 'entities__alien__behaviors__immerse': 0.7386885119126777,
 'entities__alien__behaviors__plan': 0.8066189104793696,
 'entities__alien__behaviors__react': 0.06914361087536083,
 'entities__alien__behaviors__solve': -1.05847776521121,
 'entities__alien__genre__arcade': 0.7935243544882278,
 'entities__alien__genre__building': 3.524750835332216,
 'entities__alien__genre__building_na': 0.722004204566555,
 'entities__alien__genre__casino': 0.9021849417681631,
 'entities__alien__genre__combat': 0.11597441911326759,
 'entities__alien__genre__driving': -3.1847642807701235,
 'entities__alien__genre__driving_na': -3.022683246811389,
 'entities__alien__genre__education': 0.9291780848714607,
 'entities__alien__genre__education_na': -1.1372989640369915,
 'entities__alien__genre__idle': 2.278804959700593,
 'entities__alien__genre__idle_na': 0.3012797192253985,
 'entities__alien__genre__match': -1.0163627243898095,
 'entities__alien__genre__party': -1.33521493134041,
 'entities__alien__genre__party_na': -1.7688972475462448,
 'entities__alien__genre__puzzle': 1.2473435385437057,
 'entities__alien__genre__rpg': -0.27850039280958644,
 'entities__alien__genre__simulation': -0.3260460150753112,
 'entities__alien__genre__sports': -0.8458114312852331,
 'entities__alien__genre__sports_na': -1.6586886246901675,
 'entities__alien__genre__story': 3.1789668854689648,
 'entities__alien__genre__story_na': 0.32979323160435964,
 'entities__alien__genre__strategy': -0.7577937393961829,
 'entities__alien__genre__tabletop': -1.306354983279058,
 'entities__alien__genre__tabletop_na': -1.9593951396017117,
 'entities__alien__topics__action': 0.9640406417216655,
 'entities__alien__topics__adventure': -1.3573323673510502,
 'entities__alien__topics__comedy': -0.28563043666761456,
 'entities__alien__topics__drama': 0.2504753272051489,
 'entities__alien__topics__fantasy': 2.5520719561850482,
 'entities__alien__topics__horror': 0.9595705473865147,
 'entities__alien__topics__mystery': -0.9079003206092637,
 'entities__alien__topics__realistic': 0.29130833012827423,
 'entities__alien__topics__romance': -1.062287663398298,
 'entities__alien__topics__sci_fi': 3.103201845765343,
 'entities__animal_ASC': 0.5872748828526456,
 'entities__animal__age': 0.8448697534076505,
 'entities__animal__behaviors__chill': 0.737113391276013,
 'entities__animal__behaviors__collect': 0.5091928451413352,
 'entities__animal__behaviors__combat': 1.363881601949624,
 'entities__animal__behaviors__compete': 0.2295786774003997,
 'entities__animal__behaviors__complete': -1.1787953564145364,
 'entities__animal__behaviors__cooperate': 1.1096424037224173,
 'entities__animal__behaviors__destroy': 0.41026543427461915,
 'entities__animal__behaviors__discover': 1.0335745991996794,
 'entities__animal__behaviors__empower': -0.471391624328233,
 'entities__animal__behaviors__experiment': -0.5186296449353639,
 'entities__animal__behaviors__express': -0.577485652270641,
 'entities__animal__behaviors__immerse': -0.03051097218548784,
 'entities__animal__behaviors__plan': -0.6290423846848207,
 'entities__animal__behaviors__react': -1.0186390898392084,
 'entities__animal__behaviors__solve': 0.3043304789016036,
 'entities__animal__genre__arcade': 0.026369830154948426,
 'entities__animal__genre__building': 3.0018172877954914,
 'entities__animal__genre__building_na': 1.1154359493832757,
 'entities__animal__genre__casino': 0.7821511730538991,
 'entities__animal__genre__combat': 0.1736321249701558,
 'entities__animal__genre__driving': -2.0300711599844536,
 'entities__animal__genre__driving_na': -2.424001419689979,
 'entities__animal__genre__education': -1.7204807726605162,
 'entities__animal__genre__education_na': -2.1090045046093513,
 'entities__animal__genre__idle': 1.2734402885533107,
 'entities__animal__genre__idle_na': -0.6215547342840498,
 'entities__animal__genre__match': -0.4623301462638751,
 'entities__animal__genre__party': 1.453576964685922,
 'entities__animal__genre__party_na': 0.03946847739333822,
 'entities__animal__genre__puzzle': 1.6470281009187857,
 'entities__animal__genre__rpg': 1.0135529486325001,
 'entities__animal__genre__simulation': 0.5931664374305196,
 'entities__animal__genre__sports': 0.27534290962931557,
 'entities__animal__genre__sports_na': -0.10651243734191004,
 'entities__animal__genre__story': -0.2676427746938806,
 'entities__animal__genre__story_na': -1.0034414949931925,
 'entities__animal__genre__strategy': -0.1945738626543179,
 'entities__animal__genre__tabletop': 0.7021724679891871,
 'entities__animal__genre__tabletop_na': -0.3048960920811795,
 'entities__animal__topics__action': 0.37215340734922847,
 'entities__animal__topics__adventure': 0.7956319622694645,
 'entities__animal__topics__comedy': -1.3283311888467721,
 'entities__animal__topics__drama': 1.137384940411799,
 'entities__animal__topics__fantasy': 0.791828497137196,
 'entities__animal__topics__horror': -0.45316515505845195,
 'entities__animal__topics__mystery': -0.16329355762000328,
 'entities__animal__topics__realistic': 0.06864835931742382,
 'entities__animal__topics__romance': -0.1753262367481148,
 'entities__animal__topics__sci_fi': 0.7146016559391115,
 'entities__celestial_ASC': 1.6830013342610126,
 'entities__celestial__age': 1.1787559916539219,
 'entities__celestial__behaviors__chill': 0.7139400540228428,
 'entities__celestial__behaviors__collect': 0.7880334169098976,
 'entities__celestial__behaviors__combat': -0.20660761765031013,
 'entities__celestial__behaviors__compete': 0.3469945989354141,
 'entities__celestial__behaviors__complete': -0.6319627178126364,
 'entities__celestial__behaviors__cooperate': 0.5606144450930652,
 'entities__celestial__behaviors__destroy': 0.6279084606306026,
 'entities__celestial__behaviors__discover': 0.13791686794494357,
 'entities__celestial__behaviors__empower': 0.36613377555755616,
 'entities__celestial__behaviors__experiment': 0.09826041104158299,
 'entities__celestial__behaviors__express': -0.9553402689127733,
 'entities__celestial__behaviors__immerse': 0.1033925620641447,
 'entities__celestial__behaviors__plan': -1.486440722505299,
 'entities__celestial__behaviors__react': -0.044207528543197434,
 'entities__celestial__behaviors__solve': 1.2524786072162102,
 'entities__celestial__genre__arcade': -0.5036014299955379,
 'entities__celestial__genre__building': 0.051013858033188045,
 'entities__celestial__genre__building_na': -1.550393919327597,
 'entities__celestial__genre__casino': -0.07375025767859503,
 'entities__celestial__genre__combat': -0.31364019362850476,
 'entities__celestial__genre__driving': 1.0242384196886831,
 'entities__celestial__genre__driving_na': -0.646743248732537,
 'entities__celestial__genre__education': -1.9192713384778675,
 'entities__celestial__genre__education_na': -2.321739195444215,
 'entities__celestial__genre__idle': 2.8553996049017147,
 'entities__celestial__genre__idle_na': 0.13836363693250286,
 'entities__celestial__genre__match': -0.4802172797641395,
 'entities__celestial__genre__party': 0.9512764667918759,
 'entities__celestial__genre__party_na': -1.2229678650910372,
 'entities__celestial__genre__puzzle': 0.8434915088965727,
 'entities__celestial__genre__rpg': 1.0860547465651011,
 'entities__celestial__genre__simulation': 0.2534070107631922,
 'entities__celestial__genre__sports': -0.298982038150011,
 'entities__celestial__genre__sports_na': -1.5119006698249284,
 'entities__celestial__genre__story': -0.30160944539323603,
 'entities__celestial__genre__story_na': -1.6617932295602964,
 'entities__celestial__genre__strategy': 0.77066770345575,
 'entities__celestial__genre__tabletop': 0.22603347147305564,
 'entities__celestial__genre__tabletop_na': -0.8998432933947217,
 'entities__celestial__topics__action': -0.0742462156827209,
 'entities__celestial__topics__adventure': 1.585332073904585,
 'entities__celestial__topics__comedy': -1.136398424292671,
 'entities__celestial__topics__drama': 0.011663421403002501,
 'entities__celestial__topics__fantasy': 2.2804000109452347,
 'entities__celestial__topics__horror': 0.4924232906397813,
 'entities__celestial__topics__mystery': 0.5037069109303696,
 'entities__celestial__topics__realistic': 1.3803893085861128,
 'entities__celestial__topics__romance': 0.04990587529298036,
 'entities__celestial__topics__sci_fi': 1.0354809005248513,
 'entities__elder_ASC': -1.6324434221418254,
 'entities__elder__age': 0.6778151053456164,
 'entities__elder__behaviors__chill': -0.47746924704544513,
 'entities__elder__behaviors__collect': 0.02529587362351024,
 'entities__elder__behaviors__combat': -0.14965965152172908,
 'entities__elder__behaviors__compete': 0.4345158092416462,
 'entities__elder__behaviors__complete': -0.12230528532366756,
 'entities__elder__behaviors__cooperate': 1.1086021719599863,
 'entities__elder__behaviors__destroy': -0.021730109599474055,
 'entities__elder__behaviors__discover': 0.895775713303202,
 'entities__elder__behaviors__empower': 0.7637803557040831,
 'entities__elder__behaviors__experiment': 0.29750581795026726,
 'entities__elder__behaviors__express': 0.04279446164907941,
 'entities__elder__behaviors__immerse': -0.6591557227676983,
 'entities__elder__behaviors__plan': -0.600868292023762,
 'entities__elder__behaviors__react': 0.4461239131652116,
 'entities__elder__behaviors__solve': -0.02583022712626839,
 'entities__elder__genre__arcade': -0.4305686106062462,
 'entities__elder__genre__building': -0.29996750798752897,
 'entities__elder__genre__building_na': -1.1253429810911506,
 'entities__elder__genre__casino': 0.35292281976734596,
 'entities__elder__genre__combat': -0.9918169712494015,
 'entities__elder__genre__driving': 1.9669912229744388,
 'entities__elder__genre__driving_na': 0.267750038392652,
 'entities__elder__genre__education': -0.2574976557653601,
 'entities__elder__genre__education_na': -0.691550192765491,
 'entities__elder__genre__idle': 1.825065782535228,
 'entities__elder__genre__idle_na': 0.0006141570875948946,
 'entities__elder__genre__match': -0.18565708908629633,
 'entities__elder__genre__party': 0.6699252582820784,
 'entities__elder__genre__party_na': -0.2846490656043677,
 'entities__elder__genre__puzzle': 2.06681554656815,
 'entities__elder__genre__rpg': 0.5705788805117934,
 'entities__elder__genre__simulation': -0.2938842612500535,
 'entities__elder__genre__sports': 0.6107197161997783,
 'entities__elder__genre__sports_na': -0.27622761187529826,
 'entities__elder__genre__story': -0.6942808842796416,
 'entities__elder__genre__story_na': -0.8421466778794187,
 'entities__elder__genre__strategy': 0.21318907730461606,
 'entities__elder__genre__tabletop': -1.7560113425799682,
 'entities__elder__genre__tabletop_na': -2.3892259600353727,
 'entities__elder__topics__action': -1.4285916682010475,
 'entities__elder__topics__adventure': 1.0614147042351743,
 'entities__elder__topics__comedy': 0.23453453463809923,
 'entities__elder__topics__drama': -0.28886435046587844,
 'entities__elder__topics__fantasy': 2.334218538745662,
 'entities__elder__topics__horror': 0.9836341561089563,
 'entities__elder__topics__mystery': 0.016584224827377807,
 'entities__elder__topics__realistic': 0.4911493991903641,
 'entities__elder__topics__romance': 0.1354608623011744,
 'entities__elder__topics__sci_fi': 2.546960452111496,
 'entities__human_ASC': 3.932016469192238,
 'entities__human__age': 1.0005251494422878,
 'entities__human__behaviors__chill': 0.6842925293507508,
 'entities__human__behaviors__collect': -0.3252508686511515,
 'entities__human__behaviors__combat': -0.03806609515604246,
 'entities__human__behaviors__compete': -0.20872973825064894,
 'entities__human__behaviors__complete': 0.5205781340668699,
 'entities__human__behaviors__cooperate': 0.852123417890672,
 'entities__human__behaviors__destroy': -0.12823276366637845,
 'entities__human__behaviors__discover': 0.423333399891399,
 'entities__human__behaviors__empower': 1.2486980876616305,
 'entities__human__behaviors__experiment': 0.5381829833361504,
 'entities__human__behaviors__express': -0.5887504458080038,
 'entities__human__behaviors__immerse': -0.18771425965131341,
 'entities__human__behaviors__plan': -0.9068790147620882,
 'entities__human__behaviors__react': 1.1032457857675064,
 'entities__human__behaviors__solve': 0.29154110631538505,
 'entities__human__genre__arcade': 0.039171286518958716,
 'entities__human__genre__building': 2.302245685510956,
 'entities__human__genre__building_na': -0.09956651101864432,
 'entities__human__genre__casino': 0.21637973168993282,
 'entities__human__genre__combat': 0.18387083485619846,
 'entities__human__genre__driving': -1.1345924190975825,
 'entities__human__genre__driving_na': -2.6766547591884478,
 'entities__human__genre__education': -2.278484895461088,
 'entities__human__genre__education_na': -2.60913228686019,
 'entities__human__genre__idle': 2.4366938543468972,
 'entities__human__genre__idle_na': -0.046682686814612864,
 'entities__human__genre__match': 1.1056641134338567,
 'entities__human__genre__party': 1.475449323014467,
 'entities__human__genre__party_na': -0.8784139442595624,
 'entities__human__genre__puzzle': 1.417819710299172,
 'entities__human__genre__rpg': 0.34614585305258067,
 'entities__human__genre__simulation': 0.1747314009914488,
 'entities__human__genre__sports': -0.9651688243528938,
 'entities__human__genre__sports_na': -1.62756190814594,
 'entities__human__genre__story': -0.34182453052703937,
 'entities__human__genre__story_na': -1.6115698180672149,
 'entities__human__genre__strategy': 1.0389304212718757,
 'entities__human__genre__tabletop': 0.17217791407035302,
 'entities__human__genre__tabletop_na': -1.2902054433274739,
 'entities__human__topics__action': -0.7902662448616694,
 'entities__human__topics__adventure': -0.1833350472619706,
 'entities__human__topics__comedy': -1.0182393150139426,
 'entities__human__topics__drama': -0.1436224150635374,
 'entities__human__topics__fantasy': 0.5366613392978257,
 'entities__human__topics__horror': 0.29930179703821863,
 'entities__human__topics__mystery': -0.2825925426663164,
 'entities__human__topics__realistic': 0.5228341092022443,
 'entities__human__topics__romance': 0.11453309328761473,
 'entities__human__topics__sci_fi': 0.9991669222403919,
 'entities__kid_ASC': -0.5558675870526376,
 'entities__kid__age': 0.7912085105280087,
 'entities__kid__behaviors__chill': 0.6950037589378825,
 'entities__kid__behaviors__collect': -0.4008579687745994,
 'entities__kid__behaviors__combat': -0.550397802607388,
 'entities__kid__behaviors__compete': 0.8822195805242581,
 'entities__kid__behaviors__complete': -1.7767721435284718,
 'entities__kid__behaviors__cooperate': 1.2009956733396183,
 'entities__kid__behaviors__destroy': 1.0771574476645358,
 'entities__kid__behaviors__discover': -0.30485041316053063,
 'entities__kid__behaviors__empower': -0.0641949910884149,
 'entities__kid__behaviors__experiment': -0.0816442996768784,
 'entities__kid__behaviors__express': 0.6280402968196659,
 'entities__kid__behaviors__immerse': 0.6670403119027365,
 'entities__kid__behaviors__plan': -0.11232332318276035,
 'entities__kid__behaviors__react': 0.6129293845546926,
 'entities__kid__behaviors__solve': 0.6277247299259986,
 'entities__kid__genre__arcade': 0.13739712884184613,
 'entities__kid__genre__building': 1.0141153707337418,
 'entities__kid__genre__building_na': -0.344251756457655,
 'entities__kid__genre__casino': -0.860896553624478,
 'entities__kid__genre__combat': -0.49563624239118165,
 'entities__kid__genre__driving': 0.14639715422488064,
 'entities__kid__genre__driving_na': -0.5884876691822992,
 'entities__kid__genre__education': -0.9657448885639104,
 'entities__kid__genre__education_na': -1.8296457754711017,
 'entities__kid__genre__idle': 2.606375257257533,
 'entities__kid__genre__idle_na': 0.5287661078139674,
 'entities__kid__genre__match': 0.018772005944704462,
 'entities__kid__genre__party': -0.3134372306334002,
 'entities__kid__genre__party_na': -1.67252288987545,
 'entities__kid__genre__puzzle': 2.2162371183987646,
 'entities__kid__genre__rpg': 0.9486809527971941,
 'entities__kid__genre__simulation': 0.5867178899747334,
 'entities__kid__genre__sports': -0.49387646432236704,
 'entities__kid__genre__sports_na': -0.7979092633093107,
 'entities__kid__genre__story': -0.21733748707720538,
 'entities__kid__genre__story_na': -0.3710955018900726,

## Role

In [78]:
cols_used = ['age'] + GENRE_COLS + GENRE_NA_COLS + TOPIC_COLS + BEHAVIOUR_COLS # 'gender_female', 

df_role = topic_dcm_df1.merge(user_df, on='survey_instance')
av_cols = []

# availablity cols
for idx, col in idx_role_dict.items():
    av_col = ((df_role.feature_1b == col).astype(int) + (df_role.feature_2b == col).astype(int))
    av_col.name = f'av_{idx}'
    
    av_cols.append(av_col)

df_role = pd.concat([df_role] + av_cols, axis=1).copy()
df_role[f'av_{len(idx_role_dict)}'] = 1
df_role['choice'] = df_role['chosen_b'].apply(lambda x: len(idx_role_dict) if x is None else role_idx_dict[x])

# combined cols
new_dcm_cols = []
idx_cols_dict = {x:[] for x in idx_role_dict}

for user_col in tqdm(cols_used):
    user_col_min = df_role[user_col].min()
    user_col_max = df_role[user_col].max()
    
    for idx, col in idx_role_dict.items():
        dcm_user_col = df_role[f'av_{idx}'] * df_role[user_col]
        # min-max scaling -> 0-1
        dcm_user_col = (dcm_user_col - user_col_min) / (user_col_max - user_col_min)
        dcm_user_col.name = f'{col}__{user_col}'

        idx_cols_dict[idx].append(f'{col}__{user_col}')
        new_dcm_cols.append(dcm_user_col)

df_role = pd.concat([df_role] + new_dcm_cols, axis=1).copy()

100%|█████████████████████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 268.16it/s]

In [79]:
m = larch.Model()

In [80]:
m.choice_co_code = 'choice'

In [81]:
m.availability_co_vars = {idx: f'av_{idx}' for idx in range(len(idx_role_dict) + 1)}

for idx, user_cols in idx_cols_dict.items():
    m.utility_co[idx] = P(f'{idx_role_dict[idx]}_ASC')
    
    for user_col in user_cols:
        m.utility_co[idx] += X(user_col) * P(user_col)

m.utility_co[len(idx_role_dict)] = 0

dfs = larch.DataFrames(df_role, alt_codes=[i for i in range(len(idx_role_dict) + 1)])

In [82]:
m.dataservice = dfs

In [83]:
m.load_data()

C:\Users\daide\AppData\Local\Temp/ipykernel_12476/1940460508.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  m.load_data()

In [84]:
%%time
m.maximize_loglike(quiet=False)

,value,initvalue,nullvalue,minimum,maximum,holdfast,note,best
roles__authority_ASC,0.913807,0.0,0.0,-inf,inf,0,,0.913807
roles__authority__age,0.942196,0.0,0.0,-inf,inf,0,,0.942196
roles__authority__behaviors__chill,0.392676,0.0,0.0,-inf,inf,0,,0.392676
roles__authority__behaviors__collect,-0.481727,0.0,0.0,-inf,inf,0,,-0.481727
roles__authority__behaviors__combat,0.068560,0.0,0.0,-inf,inf,0,,0.068560
...,...,...,...,...,...,...,...,...
roles__warrior__topics__horror,1.521173,0.0,0.0,-inf,inf,0,,1.521173
roles__warrior__topics__mystery,-0.029274,0.0,0.0,-inf,inf,0,,-0.029274
roles__warrior__topics__realistic,0.000764,0.0,0.0,-inf,inf,0,,0.000764
roles__warrior__topics__romance,-0.020722,0.0,0.0,-inf,inf,0,,-0.020722
roles__warrior__topics__sci_fi,1.282671,0.0,0.0,-inf,inf,0,,1.282671

Wall time: 31.1 s

┣          loglike: -2304.4261458781425
┣                x: roles__authority_ASC                    0.913807
┃                   roles__authority__age                   0.942196
┃                   roles__authority__behaviors__chill      0.392676
┃                   roles__authority__behaviors__collect   -0.481727
┃                   roles__authority__behaviors__combat     0.068560
┃                                                             ...
┃                   roles__warrior__topics__horror          1.521173
┃                   roles__warrior__topics__mystery        -0.029274
┃                   roles__warrior__topics__realistic       0.000764
┃                   roles__warrior__topics__romance        -0.020722
┃                   roles__warrior__topics__sci_fi          1.282671
┃                   Length: 561, dtype: float64
┣        tolerance: 8.29056506938578e-06
┣            steps: array([1. , 1. , 1. , 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
┃                          0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
┃                          0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])
┣          message: 'Optimization terminated successfully.'
┣     elapsed_time: datetime.timedelta(seconds=31, microseconds=120283)
┣           method: 'bhhh'
┣          n_cases: 3046
┣ iteration_number: 39
┣          logloss: 0.7565417419166587

### Results

In [85]:
pickle.dump(m.get_values().to_dict(), open("role_coefs_2.p", "wb"))

In [86]:
pickle.load(open("role_coefs_2.p", "rb"))

{'roles__authority_ASC': 0.9138067835247548,
 'roles__authority__age': 0.9421963787296576,
 'roles__authority__behaviors__chill': 0.3926756142927551,
 'roles__authority__behaviors__collect': -0.4817273154693917,
 'roles__authority__behaviors__combat': 0.06855975799651985,
 'roles__authority__behaviors__compete': 0.0949355360186911,
 'roles__authority__behaviors__complete': -0.5780808601388445,
 'roles__authority__behaviors__cooperate': 0.922573883135487,
 'roles__authority__behaviors__destroy': 0.5514492090291896,
 'roles__authority__behaviors__discover': -0.07255393697383873,
 'roles__authority__behaviors__empower': 0.4359040139474411,
 'roles__authority__behaviors__experiment': 0.6893595932260929,
 'roles__authority__behaviors__express': -0.4024283665302244,
 'roles__authority__behaviors__immerse': 0.025990116100552126,
 'roles__authority__behaviors__plan': 0.49190015644428114,
 'roles__authority__behaviors__react': 0.0443734322535008,
 'roles__authority__behaviors__solve': -0.22584700907554595,
 'roles__authority__genre__arcade': 0.16897979329329296,
 'roles__authority__genre__building': 0.4262575537876833,
 'roles__authority__genre__building_na': -1.057845286190233,
 'roles__authority__genre__casino': 0.44642653544586297,
 'roles__authority__genre__combat': -0.36634029265200146,
 'roles__authority__genre__driving': -1.790652749432662,
 'roles__authority__genre__driving_na': -2.250306788539084,
 'roles__authority__genre__education': -0.22247766964089372,
 'roles__authority__genre__education_na': -0.8032416976911209,
 'roles__authority__genre__idle': 2.1543291815583805,
 'roles__authority__genre__idle_na': 0.06858425207984194,
 'roles__authority__genre__match': -0.8065266915287288,
 'roles__authority__genre__party': 0.882263577859446,
 'roles__authority__genre__party_na': -0.6716697641896261,
 'roles__authority__genre__puzzle': 1.987497563375121,
 'roles__authority__genre__rpg': 1.3579469238420443,
 'roles__authority__genre__simulation': 0.003695064472138315,
 'roles__authority__genre__sports': -0.07386390033795856,
 'roles__authority__genre__sports_na': -0.8786324302423877,
 'roles__authority__genre__story': 1.3645105894287897,
 'roles__authority__genre__story_na': -0.1138177138162403,
 'roles__authority__genre__strategy': -0.17635434648177634,
 'roles__authority__genre__tabletop': -0.21093498544217557,
 'roles__authority__genre__tabletop_na': -1.1612966502552449,
 'roles__authority__topics__action': -0.49005491343178587,
 'roles__authority__topics__adventure': 0.6420471341379856,
 'roles__authority__topics__comedy': 0.21955163177019646,
 'roles__authority__topics__drama': 0.7349929915987928,
 'roles__authority__topics__fantasy': 0.4183417424990908,
 'roles__authority__topics__horror': 0.19944176031036748,
 'roles__authority__topics__mystery': -0.24153107089022544,
 'roles__authority__topics__realistic': 0.5322838912972283,
 'roles__authority__topics__romance': -0.1752031920743207,
 'roles__authority__topics__sci_fi': 1.0893306054361458,
 'roles__carer_ASC': 0.015920584612806175,
 'roles__carer__age': 1.36920033249991,
 'roles__carer__behaviors__chill': -0.23269297911494663,
 'roles__carer__behaviors__collect': 0.623963940751424,
 'roles__carer__behaviors__combat': 0.5603072043229741,
 'roles__carer__behaviors__compete': -0.4216945693659014,
 'roles__carer__behaviors__complete': -0.5972054118411592,
 'roles__carer__behaviors__cooperate': 1.9383684338320928,
 'roles__carer__behaviors__destroy': 0.5361769804517774,
 'roles__carer__behaviors__discover': 0.3495388516058292,
 'roles__carer__behaviors__empower': 0.3746479869923763,
 'roles__carer__behaviors__experiment': -0.5704570346089275,
 'roles__carer__behaviors__express': -1.2107949329221979,
 'roles__carer__behaviors__immerse': 0.037108250989090034,
 'roles__carer__behaviors__plan': -0.32627467822811934,
 'roles__carer__behaviors__react': 0.6707825480490036,
 'roles__carer__behaviors__solve': 0.620585845716931,
 'roles__carer__genre__arcade': 0.30255482784772364,
 'roles__carer__genre__building': 1.0358648998224176,
 'roles__carer__genre__building_na': 0.0022790327837028464,
 'roles__carer__genre__casino': 0.5301691791417962,
 'roles__carer__genre__combat': -0.022754594991390143,
 'roles__carer__genre__driving': -1.558551356611896,
 'roles__carer__genre__driving_na': -1.7509412415829047,
 'roles__carer__genre__education': 0.019420356768342296,
 'roles__carer__genre__education_na': -0.7369478831918002,
 'roles__carer__genre__idle': 1.8462986966154877,
 'roles__carer__genre__idle_na': 0.2646495320031966,
 'roles__carer__genre__match': -0.21351089731279044,
 'roles__carer__genre__party': 1.3756093330131542,
 'roles__carer__genre__party_na': -0.344474226820571,
 'roles__carer__genre__puzzle': 0.9461302546503645,
 'roles__carer__genre__rpg': 0.7844089257983292,
 'roles__carer__genre__simulation': 0.9727042951327554,
 'roles__carer__genre__sports': -0.05240874547540348,
 'roles__carer__genre__sports_na': -0.652780131166134,
 'roles__carer__genre__story': -0.6479709310546179,
 'roles__carer__genre__story_na': -0.954216587845737,
 'roles__carer__genre__strategy': -0.7100527062897873,
 'roles__carer__genre__tabletop': -1.564503219890715,
 'roles__carer__genre__tabletop_na': -1.6660104833316818,
 'roles__carer__topics__action': -0.292749130764798,
 'roles__carer__topics__adventure': 1.085005985669047,
 'roles__carer__topics__comedy': -0.6500568676308098,
 'roles__carer__topics__drama': -0.2883559500877083,
 'roles__carer__topics__fantasy': 0.5012624261805051,
 'roles__carer__topics__horror': 0.37745283724466766,
 'roles__carer__topics__mystery': 0.03632943995432557,
 'roles__carer__topics__realistic': 0.34208603714200575,
 'roles__carer__topics__romance': 0.7458098913988835,
 'roles__carer__topics__sci_fi': 1.370195802120377,
 'roles__creator_ASC': 0.6086610486963627,
 'roles__creator__age': 0.5202218784523337,
 'roles__creator__behaviors__chill': 0.17338814954475873,
 'roles__creator__behaviors__collect': 0.19361153468459988,
 'roles__creator__behaviors__combat': -0.47744647270379637,
 'roles__creator__behaviors__compete': -0.23724394426298917,
 'roles__creator__behaviors__complete': 0.4596037839322672,
 'roles__creator__behaviors__cooperate': 0.9230353214071735,
 'roles__creator__behaviors__destroy': 0.5064836602076721,
 'roles__creator__behaviors__discover': 1.0935577880099294,
 'roles__creator__behaviors__empower': 1.0249575873777708,
 'roles__creator__behaviors__experiment': -0.32924308538444336,
 'roles__creator__behaviors__express': -0.7446313091196743,
 'roles__creator__behaviors__immerse': -0.325481074750778,
 'roles__creator__behaviors__plan': 0.3032426633499764,
 'roles__creator__behaviors__react': -0.0008469681152655131,
 'roles__creator__behaviors__solve': -0.15067990448820348,
 'roles__creator__genre__arcade': 0.7400776130563218,
 'roles__creator__genre__building': 0.7068728894503491,
 'roles__creator__genre__building_na': -1.2555362659080656,
 'roles__creator__genre__casino': 0.9272384041759208,
 'roles__creator__genre__combat': -0.4178745537787147,
 'roles__creator__genre__driving': -0.24557313844681358,
 'roles__creator__genre__driving_na': -1.1950120043027785,
 'roles__creator__genre__education': -0.9603289472082197,
 'roles__creator__genre__education_na': -1.90539873660409,
 'roles__creator__genre__idle': 1.2027997159001904,
 'roles__creator__genre__idle_na': -0.41997972518713816,
 'roles__creator__genre__match': 0.6839561407675651,
 'roles__creator__genre__party': 0.5930328317314086,
 'roles__creator__genre__party_na': -1.057237047083107,
 'roles__creator__genre__puzzle': 1.2840364054097377,
 'roles__creator__genre__rpg': 1.0056331896751851,
 'roles__creator__genre__simulation': 0.2695644442120826,
 'roles__creator__genre__sports': 0.4674008764586389,
 'roles__creator__genre__sports_na': -1.2457456037237533,
 'roles__creator__genre__story': 1.4498943416614174,
 'roles__creator__genre__story_na': -0.014382267333135275,
 'roles__creator__genre__strategy': 0.8972751609717643,
 'roles__creator__genre__tabletop': -0.16040623197452547,
 'roles__creator__genre__tabletop_na': -0.9376632549848243,
 'roles__creator__topics__action': -0.47872066594830515,
 'roles__creator__topics__adventure': 0.25531577832395813,
 'roles__creator__topics__comedy': -0.11785041504054555,
 'roles__creator__topics__drama': -0.7870127620013699,
 'roles__creator__topics__fantasy': -0.10888143641592656,
 'roles__creator__topics__horror': -0.06524302406681286,
 'roles__creator__topics__mystery': 0.19378884287986903,
 'roles__creator__topics__realistic': 0.7524117940360812,
 'roles__creator__topics__romance': 0.3183417150299871,
 'roles__creator__topics__sci_fi': 0.9447610105210673,
 'roles__explorer_ASC': -3.739428148931366,
 'roles__explorer__age': 0.13991767989680118,
 'roles__explorer__behaviors__chill': 0.39840519775817324,
 'roles__explorer__behaviors__collect': 0.2636354461546579,
 'roles__explorer__behaviors__combat': 0.11895866302136303,
 'roles__explorer__behaviors__compete': 0.5498462577445633,
 'roles__explorer__behaviors__complete': -0.2590170103091117,
 'roles__explorer__behaviors__cooperate': 0.5948970629621643,
 'roles__explorer__behaviors__destroy': 1.2914300758422788,
 'roles__explorer__behaviors__discover': 1.2409200256187227,
 'roles__explorer__behaviors__empower': 0.569905031283773,
 'roles__explorer__behaviors__experiment': 0.25664215411885144,
 'roles__explorer__behaviors__express': -0.6040001947930123,
 'roles__explorer__behaviors__immerse': 0.2130523788028736,
 'roles__explorer__behaviors__plan': -0.4470989594605835,
 'roles__explorer__behaviors__react': 0.4148758764336108,
 'roles__explorer__behaviors__solve': 0.11570896356245909,
 'roles__explorer__genre__arcade': 0.49971500608498054,
 'roles__explorer__genre__building': 0.6782459218246281,
 'roles__explorer__genre__building_na': 0.07828053524239048,
 'roles__explorer__genre__casino': 0.40248493131952584,
 'roles__explorer__genre__combat': -0.3694135250136641,
 'roles__explorer__genre__driving': -1.1326216586169717,
 'roles__explorer__genre__driving_na': -1.2550393060984368,
 'roles__explorer__genre__education': -0.3413510301109187,
 'roles__explorer__genre__education_na': -0.44823835320291106,
 'roles__explorer__genre__idle': 0.8777099467314138,
 'roles__explorer__genre__idle_na': 0.9812646089515468,
 'roles__explorer__genre__match': 0.5315330224146794,
 'roles__explorer__genre__party': -0.6271527649060837,
 'roles__explorer__genre__party_na': -0.6196559234475161,
 'roles__explorer__genre__puzzle': 1.9164042586928496,
 'roles__explorer__genre__rpg': -0.1581292089998151,
 'roles__explorer__genre__simulation': 0.8236929069667102,
 'roles__explorer__genre__sports': 0.8311918056226214,
 'roles__explorer__genre__sports_na': 0.6798967348537193,
 'roles__explorer__genre__story': -0.44212657279582274,
 'roles__explorer__genre__story_na': -0.4536140129646858,
 'roles__explorer__genre__strategy': -0.4514704284530068,
 'roles__explorer__genre__tabletop': -2.317040035378277,
 'roles__explorer__genre__tabletop_na': -1.6760149844731682,
 'roles__explorer__topics__action': -0.6734760670071044,
 'roles__explorer__topics__adventure': 0.972168912478887,
 'roles__explorer__topics__comedy': -0.46146850169888787,
 'roles__explorer__topics__drama': 0.5338336278746307,
 'roles__explorer__topics__fantasy': 1.6239223189252452,
 'roles__explorer__topics__horror': -0.27307451949126865,
 'roles__explorer__topics__mystery': 0.8819855792549801,
 'roles__explorer__topics__realistic': -0.09070468959837041,
 'roles__explorer__topics__romance': 0.15582355245560592,
 'roles__explorer__topics__sci_fi': 1.0358047033675113,
 'roles__follower_ASC': -1.6989331973520603,
 'roles__follower__age': -0.009692582598413504,
 'roles__follower__behaviors__chill': 1.0718278544355109,
 'roles__follower__behaviors__collect': 0.32551969722016866,
 'roles__follower__behaviors__combat': 0.5358574765985964,
 'roles__follower__behaviors__compete': 0.7642769857847385,
 'roles__follower__behaviors__complete': -1.1509733222891159,
 'roles__follower__behaviors__cooperate': 0.3854027589529565,
 'roles__follower__behaviors__destroy': 0.2593590301809746,
 'roles__follower__behaviors__discover': 0.43472845422440926,
 'roles__follower__behaviors__empower': -0.1090986611266459,
 'roles__follower__behaviors__experiment': 0.6252799548161249,
 'roles__follower__behaviors__express': -0.8812778034394582,
 'roles__follower__behaviors__immerse': -0.22841278368537138,
 'roles__follower__behaviors__plan': -0.4672579057277081,
 'roles__follower__behaviors__react': -0.2279865631264016,
 'roles__follower__behaviors__solve': 1.3337332711793597,
 'roles__follower__genre__arcade': -0.4254705380085051,
 'roles__follower__genre__building': 1.5903479233963485,
 'roles__follower__genre__building_na': 0.4086517295941744,
 'roles__follower__genre__casino': 0.07478105452719937,
 'roles__follower__genre__combat': -0.06288120207472678,
 'roles__follower__genre__driving': -1.6950882248448882,
 'roles__follower__genre__driving_na': -1.7801620712537283,
 'roles__follower__genre__education': -2.0723326665986104,
 'roles__follower__genre__education_na': -1.5780035888351494,
 'roles__follower__genre__idle': 1.6310066947682782,
 'roles__follower__genre__idle_na': 0.6789169973147307,
 'roles__follower__genre__match': 0.320553628538493,
 'roles__follower__genre__party': -0.3209673953553592,
 'roles__follower__genre__party_na': -0.5943014502667829,
 'roles__follower__genre__puzzle': 0.9815583011501787,
 'roles__follower__genre__rpg': 0.03235600706209557,
 'roles__follower__genre__simulation': 1.3689875266700184,
 'roles__follower__genre__sports': -0.013806629723525816,
 'roles__follower__genre__sports_na': -0.12303569586172722,
 'roles__follower__genre__story': -0.34199102482482313,
 'roles__follower__genre__story_na': -0.7935970040935318,
 'roles__follower__genre__strategy': 0.2765656131481991,
 'roles__follower__genre__tabletop': 0.03904288839436472,
 'roles__follower__genre__tabletop_na': 0.10882237870327717,
 'roles__follower__topics__action': 0.05522505969609434,
 'roles__follower__topics__adventure': 0.495924885093431,
 'roles__follower__topics__comedy': 0.10073503938312449,
 'roles__follower__topics__drama': -0.8285124700389663,
 'roles__follower__topics__fantasy': 2.2994158755678766,
 'roles__follower__topics__horror': 0.39290856677143643,
 'roles__follower__topics__mystery': -0.20770908476172,
 'roles__follower__topics__realistic': -0.24299880542772714,
 'roles__follower__topics__romance': 0.8112458803509487,
 'roles__follower__topics__sci_fi': 0.4832868951601196,
 'roles__mystic_ASC': -1.178420583844531,
 'roles__mystic__age': 0.4347590068377594,
 'roles__mystic__behaviors__chill': 0.8406794757682765,
 'roles__mystic__behaviors__collect': 0.16368865176932518,
 'roles__mystic__behaviors__combat': 0.43506777131440016,
 'roles__mystic__behaviors__compete': 1.2227353540710717,
 'roles__mystic__behaviors__complete': -1.1553080874057704,
 'roles__mystic__behaviors__cooperate': 0.35746766458026025,
 'roles__mystic__behaviors__destroy': 0.18863567831253036,
 'roles__mystic__behaviors__discover': 1.0020356468553018,
 'roles__mystic__behaviors__empower': 0.10971448953534196,
 'roles__mystic__behaviors__experiment': -0.07545017290881748,
 'roles__mystic__behaviors__express': -0.9045020915808827,
 'roles__mystic__behaviors__immerse': 0.4285030793719913,
 'roles__mystic__behaviors__plan': -0.4040637608841583,
 'roles__mystic__behaviors__react': -0.22569572681303485,
 'roles__mystic__behaviors__solve': 0.002865205145088712,
 'roles__mystic__genre__arcade': -0.3024533216919074,
 'roles__mystic__genre__building': 2.5297698161600284,
 'roles__mystic__genre__building_na': 1.0216088629453073,
 'roles__mystic__genre__casino': 0.04934312375370664,
 'roles__mystic__genre__combat': -0.4184601872945335,
 'roles__mystic__genre__driving': -0.26691912042185584,
 'roles__mystic__genre__driving_na': -0.8372630971494595,
 'roles__mystic__genre__education': -0.9809657493635929,
 'roles__mystic__genre__education_na': -1.409625857173614,
 'roles__mystic__genre__idle': 1.70245849242007,
 'roles__mystic__genre__idle_na': 0.010875507537748541,
 'roles__mystic__genre__match': -0.13705157175349847,
 'roles__mystic__genre__party': 1.9312695614939663,
 'roles__mystic__genre__party_na': 0.5267517905378866,
 'roles__mystic__genre__puzzle': 2.844700597389204,
 'roles__mystic__genre__rpg': 0.48391679934654686,
 'roles__mystic__genre__simulation': 0.6358669876864558,
 'roles__mystic__genre__sports': -0.36464300311046943,
 'roles__mystic__genre__sports_na': -1.1559216365710259,
 'roles__mystic__genre__story': -0.7466161631051144,
 'roles__mystic__genre__story_na': -0.7914533358079783,
 'roles__mystic__genre__strategy': 0.16695087479164758,
 'roles__mystic__genre__tabletop': -1.1536340440749904,
 'roles__mystic__genre__tabletop_na': -1.3297172460690438,
 'roles__mystic__topics__action': -0.2430260870900958,
 'roles__mystic__topics__adventure': -0.8565650506633362,
 'roles__mystic__topics__comedy': -0.2754151033129411,
 'roles__mystic__topics__drama': -0.0348718073715459,
 'roles__mystic__topics__fantasy': 1.7569726552051583,
 'roles__mystic__topics__horror': 0.521644523501967,
 'roles__mystic__topics__mystery': -0.5093612702430876,
 'roles__mystic__topics__realistic': -0.2696442328803632,
 'roles__mystic__topics__romance': 0.5084701762428777,
 'roles__mystic__topics__sci_fi': 1.759537199019331,
 'roles__rebel_ASC': 0.7516864715221093,
 'roles__rebel__age': 0.6550680615941052,
 'roles__rebel__behaviors__chill': 0.18466270084369502,
 'roles__rebel__behaviors__collect': 0.38859562994880825,
 'roles__rebel__behaviors__combat': 0.3510970418987622,
 'roles__rebel__behaviors__compete': 0.3953805966348897,
 'roles__rebel__behaviors__complete': 0.22953346419497553,
 'roles__rebel__behaviors__cooperate': 0.6326791711709621,
 'roles__rebel__behaviors__destroy': 0.518670167428712,
 'roles__rebel__behaviors__discover': 1.6768206304021944,
 'roles__rebel__behaviors__empower': 0.3215892676379462,
 'roles__rebel__behaviors__experiment': -0.2964609239809838,
 'roles__rebel__behaviors__express': -0.786368051080795,
 'roles__rebel__behaviors__immerse': 0.5120064160918371,
 'roles__rebel__behaviors__plan': -0.4241442915387003,
 'roles__rebel__behaviors__react': -0.34332367331518004,
 'roles__rebel__behaviors__solve': 0.7949914820199001,
 'roles__rebel__genre__arcade': 0.39064296908301327,
 'roles__rebel__genre__building': -0.25730276978385347,
 'roles__rebel__genre__building_na': -1.4868043083799525,
 'roles__rebel__genre__casino': 0.2046001055663458,
 'roles__rebel__genre__combat': 0.7160296131565203,
 'roles__rebel__genre__driving': -0.9783912789734674,
 'roles__rebel__genre__driving_na': -1.7251812165663356,
 'roles__rebel__genre__education': -0.058745269058345456,
 'roles__rebel__genre__education_na': -0.933087850588102,
 'roles__rebel__genre__idle': 0.22571648755418033,
 'roles__rebel__genre__idle_na': -0.8304467239617228,
 'roles__rebel__genre__match': -0.29301058839204086,
 'roles__rebel__genre__party': 0.45689394171383285,
 'roles__rebel__genre__party_na': -0.5117709906520025,
 'roles__rebel__genre__puzzle': 1.0904247712022677,
 'roles__rebel__genre__rpg': 0.7489042371742439,
 'roles__rebel__genre__simulation': 0.1718043544102603,
 'roles__rebel__genre__sports': -0.8357261298435716,
 'roles__rebel__genre__sports_na': -1.2766386393167841,
 'roles__rebel__genre__story': -0.23139728128777448,
 'roles__rebel__genre__story_na': -0.6627995383392075,
 'roles__rebel__genre__strategy': 0.08832917312993137,
 'roles__rebel__genre__tabletop': -0.652229217939354,
 'roles__rebel__genre__tabletop_na': -1.391041765569346,
 'roles__rebel__topics__action': -0.10833891802358901,
 'roles__rebel__topics__adventure': 0.38086245050228246,
 'roles__rebel__topics__comedy': 0.10786764445548931,
 'roles__rebel__topics__drama': -0.26771596280941773,
 'roles__rebel__topics__fantasy': 0.19375604737362673,
 'roles__rebel__topics__horror': 0.8963282417941378,

## Environment + eras

In [87]:
cols_used = ['age'] + GENRE_COLS + GENRE_NA_COLS + TOPIC_COLS + BEHAVIOUR_COLS # 'gender_female', 

df_era = topic_dcm_df2.merge(user_df, on='survey_instance')
av_cols = []

# availablity cols
for idx, col in idx_era_enviro_dict.items():
    av_col = ((df_era.feature_1a == col).astype(int) + (df_era.feature_2a == col).astype(int))
    av_col.name = f'av_{idx}'
    
    av_cols.append(av_col)

df_era = pd.concat([df_era] + av_cols, axis=1).copy()
df_era[f'av_{len(idx_era_enviro_dict)}'] = 1
df_era['choice'] = df_era['chosen_a'].apply(lambda x: len(idx_era_enviro_dict) if x is None else era_enviro_idx_dict[x])

# combined cols
new_dcm_cols = []
idx_cols_dict = {x:[] for x in idx_era_enviro_dict}

for user_col in tqdm(cols_used):
    user_col_min = df_era[user_col].min()
    user_col_max = df_era[user_col].max()
    
    for idx, col in idx_era_enviro_dict.items():
        dcm_user_col = df_era[f'av_{idx}'] * df_era[user_col]
        # min-max scaling -> 0-1
        dcm_user_col = (dcm_user_col - user_col_min) / (user_col_max - user_col_min)
        dcm_user_col.name = f'{col}__{user_col}'

        idx_cols_dict[idx].append(f'{col}__{user_col}')
        new_dcm_cols.append(dcm_user_col)

df_era = pd.concat([df_era] + new_dcm_cols, axis=1).copy()

100%|█████████████████████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 194.71it/s]

In [88]:
m = larch.Model()

In [89]:
m.choice_co_code = 'choice'

In [90]:
m.availability_co_vars = {idx: f'av_{idx}' for idx in range(len(idx_era_enviro_dict) + 1)}

for idx, user_cols in idx_cols_dict.items():
    m.utility_co[idx] = P(f'{idx_era_enviro_dict[idx]}_ASC')
    
    for user_col in user_cols:
        m.utility_co[idx] += X(user_col) * P(user_col)

m.utility_co[len(idx_era_enviro_dict)] = 0

dfs = larch.DataFrames(df_era, alt_codes=[i for i in range(len(idx_era_enviro_dict) + 1)])

In [91]:
m.dataservice = dfs

In [92]:
m.load_data()

C:\Users\daide\AppData\Local\Temp/ipykernel_12476/1940460508.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  m.load_data()

In [93]:
%%time
m.maximize_loglike(quiet=False)

,value,initvalue,nullvalue,minimum,maximum,holdfast,note,best
environment__alternality_ASC,-4.566236,0.0,0.0,-inf,inf,0,,-4.566236
environment__alternality__age,-0.960144,0.0,0.0,-inf,inf,0,,-0.960144
environment__alternality__behaviors__chill,0.961490,0.0,0.0,-inf,inf,0,,0.961490
environment__alternality__behaviors__collect,-0.464641,0.0,0.0,-inf,inf,0,,-0.464641
environment__alternality__behaviors__combat,-0.403260,0.0,0.0,-inf,inf,0,,-0.403260
...,...,...,...,...,...,...,...,...
eras__timeless__topics__horror,0.397137,0.0,0.0,-inf,inf,0,,0.397137
eras__timeless__topics__mystery,-0.041323,0.0,0.0,-inf,inf,0,,-0.041323
eras__timeless__topics__realistic,0.972961,0.0,0.0,-inf,inf,0,,0.972961
eras__timeless__topics__romance,0.035081,0.0,0.0,-inf,inf,0,,0.035081
eras__timeless__topics__sci_fi,1.536521,0.0,0.0,-inf,inf,0,,1.536521

c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.518383484961034e-11 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.6775913991295965e-11 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.4695102913546064e-11 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.3168312646458168e-11 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.2050499435420207e-11 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.1214806860848346e-11 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.0666856265118821e-11 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.0188801896366534e-11 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.918635353087832e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.663718067952354e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.553949428461883e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.525531656040618e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.512592102911522e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.432683800714154e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.407671310805027e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.410684904953559e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.387814202226064e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.383383278011286e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.328252119312694e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.323469473136899e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.33412144099718e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.314993219511003e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.306444503753063e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.288254193551282e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.28312981997497e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.261980071783717e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.220568752965514e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.25382392576424e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.202139050742264e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.217043794862187e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.223455332829462e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.196213226933664e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.174494497438487e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.188189732710697e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.15781731079675e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.18508314112082e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.115299931961723e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.12073836489394e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.125899688708301e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.113043652812146e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.09388840271638e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.090691836757434e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.090857441439501e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.079918873350836e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.103735356737863e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.078635857074044e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.032997383843662e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.01998859475765e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.032844966339618e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.050750741030492e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.03939124760816e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.032072375597617e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.0209451304832e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.025805920474328e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.990744209554785e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.003030959631175e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.985116308209541e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.9776620501163e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.958940185915224e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.992001594547178e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.991177062183135e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.954876228560449e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.961173816879331e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.945619210455852e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.963399812340365e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.952888777414773e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.925526879864383e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.937038744683337e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.952323547813682e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.942957477873576e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.928285189009102e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.916604858507242e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.90233677023602e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.899796183218026e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.888422983730351e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.928819306369771e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.923363783285707e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.903271783011287e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.910989760885441e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.906830488607177e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.871159415510445e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.870904010757372e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.882075196858446e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.867447141147255e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.872709858147648e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.874241619305728e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.87389207249281e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.82894451857257e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.85275164806665e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.848744651992453e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.859952701767556e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.843899570563296e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.846477988268942e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.840492140410906e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.859238863344201e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.862910839262335e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.834136980966303e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.85852486682417e-12 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")

Wall time: 4min 24s

┣          loglike: -2902.399422545532
┣                x: environment__alternality_ASC                   -4.566236
┃                   environment__alternality__age                  -0.960144
┃                   environment__alternality__behaviors__chill      0.961490
┃                   environment__alternality__behaviors__collect   -0.464641
┃                   environment__alternality__behaviors__combat    -0.403260
┃                                                                     ...
┃                   eras__timeless__topics__horror                  0.397137
┃                   eras__timeless__topics__mystery                -0.041323
┃                   eras__timeless__topics__realistic               0.972961
┃                   eras__timeless__topics__romance                 0.035081
┃                   eras__timeless__topics__sci_fi                  1.536521
┃                   Length: 867, dtype: float64
┣        tolerance: 0.021836405302391792
┣            steps: array([1.     , 1.     , 0.5    , 0.5    , 0.25   , 0.25   , 0.25   ,
┃                          0.25   , 0.25   , 0.25   , 0.25   , 0.25   , 0.125  , 0.0625 ,
┃                          0.0625 , 0.0625 , 0.0625 , 0.03125, 0.03125, 0.03125, 0.03125,
┃                          0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125,
┃                          0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125,
┃                          0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125,
┃                          0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125,
┃                          0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125,
┃                          0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125,
┃                          0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125,
┃                          0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125,
┃                          0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125,
┃                          0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125,
┃                          0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125,
┃                          0.03125, 0.03125])
┣          message: 'Optimization terminated after 100 iterations.'
┣     elapsed_time: datetime.timedelta(seconds=264, microseconds=275742)
┣           method: 'bhhh'
┣          n_cases: 3944
┣ iteration_number: 100
┣          logloss: 0.735902490503431

### Results

In [94]:
pickle.dump(m.get_values().to_dict(), open("enviro_era_coefs_2.p", "wb"))

In [95]:
pickle.load(open("enviro_era_coefs_2.p", "rb"))

{'environment__alternality_ASC': -4.566235690866905,
 'environment__alternality__age': -0.9601435773171749,
 'environment__alternality__behaviors__chill': 0.9614899119755768,
 'environment__alternality__behaviors__collect': -0.4646409935638142,
 'environment__alternality__behaviors__combat': -0.4032600931290022,
 'environment__alternality__behaviors__compete': 0.2931782791311439,
 'environment__alternality__behaviors__complete': 0.7521686028547492,
 'environment__alternality__behaviors__cooperate': 0.00535168893649527,
 'environment__alternality__behaviors__destroy': 1.044303992859118,
 'environment__alternality__behaviors__discover': 1.0792565463169208,
 'environment__alternality__behaviors__empower': -0.4417815853148955,
 'environment__alternality__behaviors__experiment': -0.10866189320494932,
 'environment__alternality__behaviors__express': 0.05309379375952228,
 'environment__alternality__behaviors__immerse': 0.29571392959221,
 'environment__alternality__behaviors__plan': 0.30573580491107083,
 'environment__alternality__behaviors__react': 0.028153491656251185,
 'environment__alternality__behaviors__solve': 0.191807773516478,
 'environment__alternality__genre__arcade': 1.8073088479255481,
 'environment__alternality__genre__building': 0.5765492081267637,
 'environment__alternality__genre__building_na': 0.2764979534771146,
 'environment__alternality__genre__casino': -1.3085558568605442,
 'environment__alternality__genre__combat': 0.25860953406601395,
 'environment__alternality__genre__driving': -0.9693870857289623,
 'environment__alternality__genre__driving_na': -0.449354904896969,
 'environment__alternality__genre__education': -1.7536100940753934,
 'environment__alternality__genre__education_na': -0.7565712597201459,
 'environment__alternality__genre__idle': -0.323499475570862,
 'environment__alternality__genre__idle_na': 0.23248555632886408,
 'environment__alternality__genre__match': 0.1144370948156321,
 'environment__alternality__genre__party': 1.9683735468044976,
 'environment__alternality__genre__party_na': 0.2574081122546036,
 'environment__alternality__genre__puzzle': 1.3638430606611025,
 'environment__alternality__genre__rpg': 0.46987476163604625,
 'environment__alternality__genre__simulation': 0.6398683357966883,
 'environment__alternality__genre__sports': -0.40716808296698964,
 'environment__alternality__genre__sports_na': -0.484967397406561,
 'environment__alternality__genre__story': 0.6607981208848871,
 'environment__alternality__genre__story_na': 0.5850271168618584,
 'environment__alternality__genre__strategy': -0.6827859388071542,
 'environment__alternality__genre__tabletop': 1.0228167205819656,
 'environment__alternality__genre__tabletop_na': 0.8588560984056587,
 'environment__alternality__topics__action': 0.8068538977516866,
 'environment__alternality__topics__adventure': -1.361059549284469,
 'environment__alternality__topics__comedy': 0.17738324528214114,
 'environment__alternality__topics__drama': -0.09536818581896962,
 'environment__alternality__topics__fantasy': 0.2499305605092107,
 'environment__alternality__topics__horror': -0.18870191021389274,
 'environment__alternality__topics__mystery': 1.0383908896354994,
 'environment__alternality__topics__realistic': 0.8341960147006052,
 'environment__alternality__topics__romance': -0.09077672011705351,
 'environment__alternality__topics__sci_fi': 1.0048359719658932,
 'environment__aquatic_ASC': 1.3604229667849637,
 'environment__aquatic__age': 0.13203862647644538,
 'environment__aquatic__behaviors__chill': 1.026269472508651,
 'environment__aquatic__behaviors__collect': -0.0884188125289465,
 'environment__aquatic__behaviors__combat': 0.02063537646222192,
 'environment__aquatic__behaviors__compete': -0.7925185566548405,
 'environment__aquatic__behaviors__complete': -1.197508462106178,
 'environment__aquatic__behaviors__cooperate': 0.6465791384677754,
 'environment__aquatic__behaviors__destroy': 0.41645303333805145,
 'environment__aquatic__behaviors__discover': 0.8885625079919367,
 'environment__aquatic__behaviors__empower': -0.20881769953187135,
 'environment__aquatic__behaviors__experiment': 0.314216910777832,
 'environment__aquatic__behaviors__express': -0.08092239208252706,
 'environment__aquatic__behaviors__immerse': 0.1358880935760013,
 'environment__aquatic__behaviors__plan': -0.2519971379677313,
 'environment__aquatic__behaviors__react': 0.3919064010250773,
 'environment__aquatic__behaviors__solve': 1.415250125184411,
 'environment__aquatic__genre__arcade': 1.0987113772911057,
 'environment__aquatic__genre__building': 0.40269755841272,
 'environment__aquatic__genre__building_na': -1.0815948880920616,
 'environment__aquatic__genre__casino': 0.02203245341195123,
 'environment__aquatic__genre__combat': 0.9819036570384737,
 'environment__aquatic__genre__driving': 0.09401512218825193,
 'environment__aquatic__genre__driving_na': -0.7096458856484436,
 'environment__aquatic__genre__education': 0.13653157988824227,
 'environment__aquatic__genre__education_na': -1.2840346985695639,
 'environment__aquatic__genre__idle': 0.981093742313377,
 'environment__aquatic__genre__idle_na': 0.19463795593385944,
 'environment__aquatic__genre__match': 0.14527114053163215,
 'environment__aquatic__genre__party': 1.2952053365189888,
 'environment__aquatic__genre__party_na': -1.0551871324789013,
 'environment__aquatic__genre__puzzle': 0.9078702175936807,
 'environment__aquatic__genre__rpg': 0.08968618608180813,
 'environment__aquatic__genre__simulation': 0.739356255813612,
 'environment__aquatic__genre__sports': -1.6259331126877292,
 'environment__aquatic__genre__sports_na': -2.35953939779882,
 'environment__aquatic__genre__story': 2.1876683266602654,
 'environment__aquatic__genre__story_na': 0.41511535843549763,
 'environment__aquatic__genre__strategy': 0.04078461167006678,
 'environment__aquatic__genre__tabletop': -0.18920237400995396,
 'environment__aquatic__genre__tabletop_na': -1.3654352724145054,
 'environment__aquatic__topics__action': 0.44354229950180674,
 'environment__aquatic__topics__adventure': -1.0275833966001298,
 'environment__aquatic__topics__comedy': -0.19425443991342511,
 'environment__aquatic__topics__drama': 0.6838109205106562,
 'environment__aquatic__topics__fantasy': 0.2194725533340704,
 'environment__aquatic__topics__horror': -0.7187225982099764,
 'environment__aquatic__topics__mystery': 0.6561756350526664,
 'environment__aquatic__topics__realistic': 1.2184591368418085,
 'environment__aquatic__topics__romance': -1.1287677400890304,
 'environment__aquatic__topics__sci_fi': 0.46005510500260544,
 'environment__rural_ASC': -0.43989336421603475,
 'environment__rural__age': 1.4402892036222705,
 'environment__rural__behaviors__chill': 1.024162560036041,
 'environment__rural__behaviors__collect': 0.5101211640309016,
 'environment__rural__behaviors__combat': 0.439112348241169,
 'environment__rural__behaviors__compete': 0.4920220938525245,
 'environment__rural__behaviors__complete': -1.2534632580300749,
 'environment__rural__behaviors__cooperate': -0.13758739841237447,
 'environment__rural__behaviors__destroy': 0.4217970082419842,
 'environment__rural__behaviors__discover': 0.16860986031177214,
 'environment__rural__behaviors__empower': 0.9990352743795938,
 'environment__rural__behaviors__experiment': 0.7988324000041309,
 'environment__rural__behaviors__express': 0.39665816722493,
 'environment__rural__behaviors__immerse': -0.22286670589402297,
 'environment__rural__behaviors__plan': -0.08587251401212201,
 'environment__rural__behaviors__react': -1.4393006569849638,
 'environment__rural__behaviors__solve': 0.22933644625428573,
 'environment__rural__genre__arcade': 1.6415500453985468,
 'environment__rural__genre__building': -0.36237545026287604,
 'environment__rural__genre__building_na': -1.0519239842983963,
 'environment__rural__genre__casino': -0.4415049832732389,
 'environment__rural__genre__combat': -0.23033913512793325,
 'environment__rural__genre__driving': 0.169528911592943,
 'environment__rural__genre__driving_na': -1.2697869116481493,
 'environment__rural__genre__education': -1.5674534070330726,
 'environment__rural__genre__education_na': -2.177949547164857,
 'environment__rural__genre__idle': -0.4605898747582596,
 'environment__rural__genre__idle_na': -1.0784736107948012,
 'environment__rural__genre__match': 0.42691077449483544,
 'environment__rural__genre__party': 2.145435004785284,
 'environment__rural__genre__party_na': -0.1815231081448314,
 'environment__rural__genre__puzzle': 1.851640737191784,
 'environment__rural__genre__rpg': -0.15315271044367126,
 'environment__rural__genre__simulation': -0.5959860188961361,
 'environment__rural__genre__sports': 0.1994168212359675,
 'environment__rural__genre__sports_na': -0.7440043760343089,
 'environment__rural__genre__story': 0.5489629209593909,
 'environment__rural__genre__story_na': -0.8888530850735253,
 'environment__rural__genre__strategy': 0.1988551934475094,
 'environment__rural__genre__tabletop': 0.9040338019399887,
 'environment__rural__genre__tabletop_na': -0.7287872990997658,
 'environment__rural__topics__action': 0.43407597027394523,
 'environment__rural__topics__adventure': 0.15221060059162284,
 'environment__rural__topics__comedy': -0.18422448408672476,
 'environment__rural__topics__drama': 1.096123926981477,
 'environment__rural__topics__fantasy': 0.7361303995580497,
 'environment__rural__topics__horror': 0.3224621210536264,
 'environment__rural__topics__mystery': 0.7402293570815782,
 'environment__rural__topics__realistic': 0.8900197709412393,
 'environment__rural__topics__romance': -0.722560892507542,
 'environment__rural__topics__sci_fi': 1.1084604469913963,
 'environment__space_ASC': -0.1077375107053741,
 'environment__space__age': -0.5630608934009982,
 'environment__space__behaviors__chill': 0.33278156148861054,
 'environment__space__behaviors__collect': 0.2962024827580411,
 'environment__space__behaviors__combat': 0.029394558591673944,
 'environment__space__behaviors__compete': 0.4011165940127209,
 'environment__space__behaviors__complete': -0.8343615452160037,
 'environment__space__behaviors__cooperate': 0.6456436102136447,
 'environment__space__behaviors__destroy': 0.256524254066106,
 'environment__space__behaviors__discover': 0.9934584985066359,
 'environment__space__behaviors__empower': 0.6433088020077965,
 'environment__space__behaviors__experiment': -0.6196467406206192,
 'environment__space__behaviors__express': 0.5951557300294128,
 'environment__space__behaviors__immerse': 0.9044271579248314,
 'environment__space__behaviors__plan': -0.08844926105424906,
 'environment__space__behaviors__react': 0.3723474091880181,
 'environment__space__behaviors__solve': 0.5323444843208249,
 'environment__space__genre__arcade': 1.434547970751047,
 'environment__space__genre__building': -0.8703792450786889,
 'environment__space__genre__building_na': -1.2414986719908205,
 'environment__space__genre__casino': -0.8353737887677833,
 'environment__space__genre__combat': -0.556135268490364,
 'environment__space__genre__driving': -0.5767172780387916,
 'environment__space__genre__driving_na': -1.0369303261836527,
 'environment__space__genre__education': -0.3080899768062339,
 'environment__space__genre__education_na': -1.5504223133346147,
 'environment__space__genre__idle': 0.7662754261615393,
 'environment__space__genre__idle_na': -0.9115400418738782,
 'environment__space__genre__match': 0.87915417881188,
 'environment__space__genre__party': -0.4190791324607417,
 'environment__space__genre__party_na': -1.3254480165631113,
 'environment__space__genre__puzzle': 2.2138658373146125,
 'environment__space__genre__rpg': 0.46233781735789214,
 'environment__space__genre__simulation': -0.6886895592428396,
 'environment__space__genre__sports': -0.6072322259848397,
 'environment__space__genre__sports_na': -0.7172095109028523,
 'environment__space__genre__story': 2.421081305982869,
 'environment__space__genre__story_na': 1.066311358794545,
 'environment__space__genre__strategy': 1.1893077772469582,
 'environment__space__genre__tabletop': 0.29318720990724506,
 'environment__space__genre__tabletop_na': -1.0947154666626393,
 'environment__space__topics__action': -0.11870510896787811,
 'environment__space__topics__adventure': -0.5317563081395122,
 'environment__space__topics__comedy': -0.6900241280887597,
 'environment__space__topics__drama': -0.35348425803532346,
 'environment__space__topics__fantasy': 1.2929978290587194,
 'environment__space__topics__horror': -0.8065810776724588,
 'environment__space__topics__mystery': 0.1094389327511652,
 'environment__space__topics__realistic': 0.5623119661693918,
 'environment__space__topics__romance': 0.14852304562244453,
 'environment__space__topics__sci_fi': 1.3226481548220475,
 'environment__suburban_ASC': -12.838616995802246,
 'environment__suburban__age': 0.8357772252942758,
 'environment__suburban__behaviors__chill': 0.34892190939114415,
 'environment__suburban__behaviors__collect': -0.46180304540403355,
 'environment__suburban__behaviors__combat': -0.21187038905923755,
 'environment__suburban__behaviors__compete': 0.14916438765583315,
 'environment__suburban__behaviors__complete': -0.3492803715946156,
 'environment__suburban__behaviors__cooperate': 0.8005322893226074,
 'environment__suburban__behaviors__destroy': 0.740829683654343,
 'environment__suburban__behaviors__discover': 2.1777657744655237,
 'environment__suburban__behaviors__empower': 0.190488804148427,
 'environment__suburban__behaviors__experiment': -0.7162287241089893,
 'environment__suburban__behaviors__express': 0.40751036532328067,
 'environment__suburban__behaviors__immerse': -0.2612817045669197,
 'environment__suburban__behaviors__plan': 0.5131640333640648,
 'environment__suburban__behaviors__react': 0.12322657238711056,
 'environment__suburban__behaviors__solve': 0.6672588839070278,
 'environment__suburban__genre__arcade': 0.7091027956819156,
 'environment__suburban__genre__building': -1.3054634400335494,
 'environment__suburban__genre__building_na': 0.4519190082850434,
 'environment__suburban__genre__casino': 0.06636474899850238,
 'environment__suburban__genre__combat': -0.2395992839760497,
 'environment__suburban__genre__driving': -1.4741414345439035,
 'environment__suburban__genre__driving_na': 1.2186179807948185,
 'environment__suburban__genre__education': -1.1997102830736421,
 'environment__suburban__genre__education_na': 1.176846089559973,
 'environment__suburban__genre__idle': 1.2617553200898848,
 'environment__suburban__genre__idle_na': 3.1047662166189407,
 'environment__suburban__genre__match': 0.012743934488730275,
 'environment__suburban__genre__party': 0.8423970171032382,
 'environment__suburban__genre__party_na': 2.384656936363163,
 'environment__suburban__genre__puzzle': 0.7624375306601211,
 'environment__suburban__genre__rpg': -0.6355122441051718,
 'environment__suburban__genre__simulation': 0.28551275576552365,
 'environment__suburban__genre__sports': -2.444428743114627,
 'environment__suburban__genre__sports_na': 0.22939154434184128,
 'environment__suburban__genre__story': -0.6150044023064969,
 'environment__suburban__genre__story_na': 2.159814430705989,
 'environment__suburban__genre__strategy': -0.6945920261985025,
 'environment__suburban__genre__tabletop': -1.096761710368978,
 'environment__suburban__genre__tabletop_na': 1.0311159518310662,
 'environment__suburban__topics__action': 1.0954912510475852,
 'environment__suburban__topics__adventure': -0.7055702112148864,
 'environment__suburban__topics__comedy': -0.4222982804774309,
 'environment__suburban__topics__drama': 0.782029435528486,
 'environment__suburban__topics__fantasy': 0.1770434138773854,
 'environment__suburban__topics__horror': 0.21381021992984886,
 'environment__suburban__topics__mystery': 1.2188140060439556,
 'environment__suburban__topics__realistic': 1.4655843436371112,
 'environment__suburban__topics__romance': -0.28980717581024235,
 'environment__suburban__topics__sci_fi': 0.9370145474623179,
 'environment__urban_ASC': 0.6595382841921917,
 'environment__urban__age': -0.43503425122967765,
 'environment__urban__behaviors__chill': 0.6537954326475481,
 'environment__urban__behaviors__collect': 0.014157388098143493,
 'environment__urban__behaviors__combat': -0.2179938483181965,
 'environment__urban__behaviors__compete': -0.4367875769129407,
 'environment__urban__behaviors__complete': -0.3594277843320206,
 'environment__urban__behaviors__cooperate': 0.7928687384427635,
 'environment__urban__behaviors__destroy': 0.08049298767081854,
 'environment__urban__behaviors__discover': 0.5992675055374909,
 'environment__urban__behaviors__empower': 1.0752346925749146,
 'environment__urban__behaviors__experiment': 1.0470567736123548,
 'environment__urban__behaviors__express': 0.6283573614176071,
 'environment__urban__behaviors__immerse': -0.2085426267137514,
 'environment__urban__behaviors__plan': 0.38468551695173503,
 'environment__urban__behaviors__react': 0.4395643814876376,
 'environment__urban__behaviors__solve': -0.5128169408773706,
 'environment__urban__genre__arcade': 1.2016507127595566,
 'environment__urban__genre__building': -0.033059639476658256,
 'environment__urban__genre__building_na': -1.7858272839526053,
 'environment__urban__genre__casino': -0.40201630508810815,
 'environment__urban__genre__combat': 0.11526868224756992,
 'environment__urban__genre__driving': 1.0339144323738854,
 'environment__urban__genre__driving_na': -0.20302376309145564,
 'environment__urban__genre__education': -1.3664048425672113,
 'environment__urban__genre__education_na': -2.2752403270212627,
 'environment__urban__genre__idle': 0.40847718164580216,
 'environment__urban__genre__idle_na': -0.6697582392918539,
 'environment__urban__genre__match': 0.2300089634907595,
 'environment__urban__genre__party': 2.1308463772915665,
 'environment__urban__genre__party_na': -0.22641338080237355,
 'environment__urban__genre__puzzle': 1.3318581553101774,
 'environment__urban__genre__rpg': 0.37888786178695866,
 'environment__urban__genre__simulation': 0.32080805549746944,
 'environment__urban__genre__sports': 1.2649305839418319,
 'environment__urban__genre__sports_na': -0.34575281980267564,
 'environment__urban__genre__story': 0.8353549017053872,
 'environment__urban__genre__story_na': -0.1383206315159247,
 'environment__urban__genre__strategy': -0.3826227059837912,
 'environment__urban__genre__tabletop': 0.37380789506564516,
 'environment__urban__genre__tabletop_na': -1.4287727386541011,
 'environment__urban__topics__action': 0.03123416190791008,
 'environment__urban__topics__adventure': -0.7639077473529492,
 'environment__urban__topics__comedy': -0.3079426776562498,
 'environment__urban__topics__drama': 1.2216611537512934,
 'environment__urban__topics__fantasy': 0.41923529393249725,
 'environment__urban__topics__horror': 0.20934701255575694,
 'environment__urban__topics__mystery': -0.5006326080552358,
 'environment__urban__topics__realistic': 0.1540079626903142,
 'environment__urban__topics__romance': -0.11578000837603833,
 'environment__urban__topics__sci_fi': 1.168770343276116,
 'environment__virtuality_ASC': -1.2023917356399725,
 'environment__virtuality__age': -0.02521629717257704,
 'environment__virtuality__behaviors__chill': -0.09229831958247606,
 'environment__virtuality__behaviors__collect': 0.4727528318763724,
 'environment__virtuality__behaviors__combat': 0.4315041775875405,
 'environment__virtuality__behaviors__compete': -0.6540090027722183,
 'environment__virtuality__behaviors__complete': -0.7157712950304744,
 'environment__virtuality__behaviors__cooperate': -0.13460775127928187,
 'environment__virtuality__behaviors__destroy': 0.19060877987255928,
 'environment__virtuality__behaviors__discover': 0.7650568074674203,
 'environment__virtuality__behaviors__empower': 0.06280133477530846,
 'environment__virtuality__behaviors__experiment': 0.33875453982396075,
 'environment__virtuality__behaviors__express': 0.5486201395166524,

## Focus + domain

In [96]:
cols_used = ['age'] + GENRE_COLS + GENRE_NA_COLS + TOPIC_COLS + BEHAVIOUR_COLS # 'gender_female', 

df_focus = topic_dcm_df2.merge(user_df, on='survey_instance')
av_cols = []

# availablity cols
for idx, col in idx_domain_focus_dict.items():
    av_col = ((df_focus.feature_1b == col).astype(int) + (df_focus.feature_2b == col).astype(int))
    av_col.name = f'av_{idx}'
    
    av_cols.append(av_col)

df_focus = pd.concat([df_focus] + av_cols, axis=1).copy()
df_focus[f'av_{len(idx_domain_focus_dict)}'] = 1
df_focus['choice'] = df_focus['chosen_b'].apply(lambda x: len(idx_domain_focus_dict) if x is None else domain_focus_idx_dict[x])

# combined cols
new_dcm_cols = []
idx_cols_dict = {x:[] for x in idx_domain_focus_dict}

for user_col in tqdm(cols_used):
    user_col_min = df_focus[user_col].min()
    user_col_max = df_focus[user_col].max()
    
    for idx, col in idx_domain_focus_dict.items():
        dcm_user_col = df_focus[f'av_{idx}'] * df_focus[user_col]
        # min-max scaling -> 0-1
        dcm_user_col = (dcm_user_col - user_col_min) / (user_col_max - user_col_min)
        dcm_user_col.name = f'{col}__{user_col}'

        idx_cols_dict[idx].append(f'{col}__{user_col}')
        new_dcm_cols.append(dcm_user_col)

df_focus = pd.concat([df_focus] + new_dcm_cols, axis=1).copy()

100%|█████████████████████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 115.85it/s]

In [97]:
m = larch.Model()

In [98]:
m.choice_co_code = 'choice'

In [99]:
m.availability_co_vars = {idx: f'av_{idx}' for idx in range(len(idx_domain_focus_dict) + 1)}

for idx, user_cols in idx_cols_dict.items():
    m.utility_co[idx] = P(f'{idx_domain_focus_dict[idx]}_ASC')
    
    for user_col in user_cols:
        m.utility_co[idx] += X(user_col) * P(user_col)

m.utility_co[len(idx_domain_focus_dict)] = 0

dfs = larch.DataFrames(df_focus, alt_codes=[i for i in range(len(idx_domain_focus_dict) + 1)])

In [100]:
m.dataservice = dfs

In [101]:
m.load_data()

C:\Users\daide\AppData\Local\Temp/ipykernel_12476/1940460508.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  m.load_data()

In [102]:
%%time
m.maximize_loglike(quiet=False)

,value,initvalue,nullvalue,minimum,maximum,holdfast,note,best
domains__art_ASC,-3435.003401,0.0,0.0,-inf,inf,0,,-3435.003401
domains__art__age,-0.122020,0.0,0.0,-inf,inf,0,,-0.122020
domains__art__behaviors__chill,1.253261,0.0,0.0,-inf,inf,0,,1.253261
domains__art__behaviors__collect,0.083912,0.0,0.0,-inf,inf,0,,0.083912
domains__art__behaviors__combat,0.093450,0.0,0.0,-inf,inf,0,,0.093450
...,...,...,...,...,...,...,...,...
focus__weapons__topics__horror,0.911709,0.0,0.0,-inf,inf,0,,0.911709
focus__weapons__topics__mystery,0.296231,0.0,0.0,-inf,inf,0,,0.296231
focus__weapons__topics__realistic,-0.598322,0.0,0.0,-inf,inf,0,,-0.598322
focus__weapons__topics__romance,-1.859022,0.0,0.0,-inf,inf,0,,-1.859022
focus__weapons__topics__sci_fi,2.726362,0.0,0.0,-inf,inf,0,,2.726362

c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 7.744639727613547e-10 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.485612065125567e-17 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.195003410181122e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.414207906356572e-17 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.5058899332260185e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.2051805991854068e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.193381832271818e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.5081985849283229e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.8799043714243045e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.084465653096804e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.3691910278121955e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 7.635446405469473e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.541259453185513e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.3284728083813185e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.147499692099233e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.919902319740141e-17 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.0045468574223511e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.9984892636567425e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.752664525877923e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.742416262869313e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.6446814835453587e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.6627819228861178e-17 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.0166264662709848e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.958445201496047e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.258138029358189e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.496407172083864e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.4547488830967143e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.333836275166422e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.358054125231868e-18 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.257314138176571e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.3137588881471983e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.231967341140979e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.5333176264344133e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.688049227504458e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.1001282878211395e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.330063505539124e-17 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.938147618117231e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.646074865131791e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.010432753683153e-17 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.941962841343248e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.3789692772834456e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.68950939594803e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.5341085148559795e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.9368154994656403e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.902857538638674e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.0495001532829223e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.611649692624093e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.424845924025685e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.578079513531196e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.2352472166742473e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.473015314240033e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.0341500837740477e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.84029110782353e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.3159930694550367e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.4944173191862563e-17 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.7506018119360176e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.318306038332363e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.367444041835712e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.011744348864316e-18 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.442986299211564e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.2965513805602807e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.0922803919241465e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.029379230182012e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.667488426284188e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.1220598489739324e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.6367803669384286e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.948829348223369e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.5462271407723137e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.067678678646622e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.055731286794996e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.0351187168218312e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.641384280852447e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.1415567215232585e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.276980248504218e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.9246263200195133e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.7576403732160838e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.6886037805138702e-17 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.034694264734392e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 7.910850106235773e-17 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.3475237282890445e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.853574731364115e-17 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.1408979909556393e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.398885858724778e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.673858079434792e-15 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.211526870040955e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.866997219603335e-18 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 8.843878922390908e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.587655586316524e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.4851173018267007e-17 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.5713479975973305e-17 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 5.084347890534893e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 4.543753554145536e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.292520480524534e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 9.369171762151518e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 1.489547602193224e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 2.457392286048702e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.8235856124000984e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 3.3614925148645587e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
c:\programs\miniconda\lib\site-packages\larch\linalg\__init__.py:18: UserWarning: minimum eig 6.768493743728767e-16 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")

Wall time: 11min 13s

┣          loglike: -2456.9435908446926
┣                x: domains__art_ASC                    -3435.003401
┃                   domains__art__age                      -0.122020
┃                   domains__art__behaviors__chill          1.253261
┃                   domains__art__behaviors__collect        0.083912
┃                   domains__art__behaviors__combat         0.093450
┃                                                           ...
┃                   focus__weapons__topics__horror          0.911709
┃                   focus__weapons__topics__mystery         0.296231
┃                   focus__weapons__topics__realistic      -0.598322
┃                   focus__weapons__topics__romance        -1.859022
┃                   focus__weapons__topics__sci_fi          2.726362
┃                   Length: 1377, dtype: float64
┣        tolerance: 0.0004542438794328346
┣            steps: array([1.   , 1.   , 0.5  , 0.5  , 0.25 , 0.25 , 0.25 , 0.25 , 0.25 ,
┃                          0.25 , 0.25 , 0.25 , 0.25 , 0.25 , 0.25 , 0.25 , 0.25 , 0.25 ,
┃                          0.25 , 0.25 , 0.25 , 0.25 , 0.25 , 0.25 , 0.25 , 0.25 , 0.25 ,
┃                          0.25 , 0.25 , 0.25 , 0.25 , 0.125, 0.125, 0.125, 0.125, 0.125,
┃                          0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
┃                          0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
┃                          0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
┃                          0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
┃                          0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
┃                          0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
┃                          0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
┃                          0.125])
┣          message: 'Optimization terminated after 100 iterations.'
┣     elapsed_time: datetime.timedelta(seconds=673, microseconds=406456)
┣           method: 'bhhh'
┣          n_cases: 3944
┣ iteration_number: 100
┣          logloss: 0.6229572999099119

### Results

In [103]:
pickle.dump(m.get_values().to_dict(), open("focus_domain_coefs_2.p", "wb"))

In [104]:
pickle.load(open("focus_domain_coefs_2.p", "rb"))

{'domains__art_ASC': -3435.0034007452377,
 'domains__art__age': -0.12202041213932821,
 'domains__art__behaviors__chill': 1.25326112196447,
 'domains__art__behaviors__collect': 0.08391240023302936,
 'domains__art__behaviors__combat': 0.09345005181309078,
 'domains__art__behaviors__compete': -0.36292305997656016,
 'domains__art__behaviors__complete': -0.6616076839606051,
 'domains__art__behaviors__cooperate': 0.5230593414469284,
 'domains__art__behaviors__destroy': 0.8180822082374998,
 'domains__art__behaviors__discover': 2.3653557053896526,
 'domains__art__behaviors__empower': 0.0720227512567071,
 'domains__art__behaviors__experiment': 0.25791101786547777,
 'domains__art__behaviors__express': -0.5922546955523607,
 'domains__art__behaviors__immerse': 0.4746910023211322,
 'domains__art__behaviors__plan': 0.5847625288707279,
 'domains__art__behaviors__react': -0.6752669019769335,
 'domains__art__behaviors__solve': 0.9199550013674176,
 'domains__art__genre__arcade': 1.6105005350509989,
 'domains__art__genre__building': -0.15611046161813028,
 'domains__art__genre__building_na': 571.3286613502619,
 'domains__art__genre__casino': -1.806468914859333,
 'domains__art__genre__combat': -1.7017572413935238,
 'domains__art__genre__driving': -0.22175219052372064,
 'domains__art__genre__driving_na': 571.89590753918,
 'domains__art__genre__education': -3.883910533269963,
 'domains__art__genre__education_na': 569.5055326852578,
 'domains__art__genre__idle': 1.729213926674044,
 'domains__art__genre__idle_na': 572.858398957085,
 'domains__art__genre__match': 1.0322863730293161,
 'domains__art__genre__party': -0.3432161659551661,
 'domains__art__genre__party_na': 570.9363522859518,
 'domains__art__genre__puzzle': 0.8277139041907339,
 'domains__art__genre__rpg': 1.5207526289772462,
 'domains__art__genre__simulation': -0.38807027059571036,
 'domains__art__genre__sports': 1.2451599327336331,
 'domains__art__genre__sports_na': 571.6406552908281,
 'domains__art__genre__story': -0.6897916466722528,
 'domains__art__genre__story_na': 571.9261293168227,
 'domains__art__genre__strategy': -0.886759314287042,
 'domains__art__genre__tabletop': 1.1471281500955213,
 'domains__art__genre__tabletop_na': 571.7405175000525,
 'domains__art__topics__action': 0.23586583930715901,
 'domains__art__topics__adventure': 0.6044445566270095,
 'domains__art__topics__comedy': 0.95243656691909,
 'domains__art__topics__drama': 0.6825072090502144,
 'domains__art__topics__fantasy': 0.14854913112497925,
 'domains__art__topics__horror': 0.14787476555251572,
 'domains__art__topics__mystery': 1.146266935294922,
 'domains__art__topics__realistic': 0.9172101656978883,
 'domains__art__topics__romance': -0.15864960624723667,
 'domains__art__topics__sci_fi': 0.923165761423456,
 'domains__business_ASC': -16256.794794890133,
 'domains__business__age': -0.45631031969797103,
 'domains__business__behaviors__chill': 0.6115890304854494,
 'domains__business__behaviors__collect': -1.3752778295181887,
 'domains__business__behaviors__combat': -0.2478334908009275,
 'domains__business__behaviors__compete': -0.5236373250244567,
 'domains__business__behaviors__complete': -0.4941493087147687,
 'domains__business__behaviors__cooperate': 1.8478009551944554,
 'domains__business__behaviors__destroy': 0.647664128899414,
 'domains__business__behaviors__discover': -0.32126810348334534,
 'domains__business__behaviors__empower': 1.4800120864096822,
 'domains__business__behaviors__experiment': -0.16049504528053382,
 'domains__business__behaviors__express': 0.04201711490837077,
 'domains__business__behaviors__immerse': -0.841183146959861,
 'domains__business__behaviors__plan': 0.5302099932404399,
 'domains__business__behaviors__react': 1.036113574569587,
 'domains__business__behaviors__solve': 0.9548241398149749,
 'domains__business__genre__arcade': 1.5108137017219203,
 'domains__business__genre__building': 0.3511362632043542,
 'domains__business__genre__building_na': 2709.0702737223673,
 'domains__business__genre__casino': -0.6455961719979652,
 'domains__business__genre__combat': -0.6618231277802755,
 'domains__business__genre__driving': -0.5121490399667246,
 'domains__business__genre__driving_na': 2708.202498347246,
 'domains__business__genre__education': -1.1320919053790517,
 'domains__business__genre__education_na': 2708.384813552731,
 'domains__business__genre__idle': -2.5043640926322666,
 'domains__business__genre__idle_na': 2707.1311186936255,
 'domains__business__genre__match': 0.5737475517129645,
 'domains__business__genre__party': 0.8183029129335845,
 'domains__business__genre__party_na': 2709.077315411189,
 'domains__business__genre__puzzle': 0.7745079902260442,
 'domains__business__genre__rpg': 0.4606285321524792,
 'domains__business__genre__simulation': -0.40106388486985933,
 'domains__business__genre__sports': -1.4577787128488287,
 'domains__business__genre__sports_na': 2708.1165136203945,
 'domains__business__genre__story': 1.003876544166046,
 'domains__business__genre__story_na': 2709.467535540743,
 'domains__business__genre__strategy': 0.101709835734603,
 'domains__business__genre__tabletop': 1.9607172226797827,
 'domains__business__genre__tabletop_na': 2709.9006829165287,
 'domains__business__topics__action': 0.8060311388377938,
 'domains__business__topics__adventure': -0.2709006318280655,
 'domains__business__topics__comedy': -0.2611759889425974,
 'domains__business__topics__drama': 0.5430843252912474,
 'domains__business__topics__fantasy': -0.33526858878236315,
 'domains__business__topics__horror': 0.23399514530677618,
 'domains__business__topics__mystery': 1.2757594877431617,
 'domains__business__topics__realistic': 2.216981177362844,
 'domains__business__topics__romance': -0.7329921692669784,
 'domains__business__topics__sci_fi': 1.563796134388897,
 'domains__crime_ASC': -4.026611420439246,
 'domains__crime__age': -2.1996637615621726,
 'domains__crime__behaviors__chill': 0.6769879389449318,
 'domains__crime__behaviors__collect': 0.8081553412125562,
 'domains__crime__behaviors__combat': 1.0720593559009877,
 'domains__crime__behaviors__compete': 0.22006855862140184,
 'domains__crime__behaviors__complete': 3.1928310844702525,
 'domains__crime__behaviors__cooperate': -0.802199689808977,
 'domains__crime__behaviors__destroy': 0.1527284585210316,
 'domains__crime__behaviors__discover': 1.2662431608657119,
 'domains__crime__behaviors__empower': -0.12731970879963178,
 'domains__crime__behaviors__experiment': 1.8225845934347908,
 'domains__crime__behaviors__express': 0.45480340637531164,
 'domains__crime__behaviors__immerse': -0.10350599225682522,
 'domains__crime__behaviors__plan': 0.4277431807195809,
 'domains__crime__behaviors__react': 0.3738714031905305,
 'domains__crime__behaviors__solve': -0.2392742943338906,
 'domains__crime__genre__arcade': 1.1738212980722995,
 'domains__crime__genre__building': -1.1224391074180164,
 'domains__crime__genre__building_na': -1.1774734925504236,
 'domains__crime__genre__casino': -0.034296649722179086,
 'domains__crime__genre__combat': -1.2031239798718845,
 'domains__crime__genre__driving': -0.48251458193117475,
 'domains__crime__genre__driving_na': -0.021503279427193794,
 'domains__crime__genre__education': -0.5508672432917093,
 'domains__crime__genre__education_na': 0.21491382012336174,
 'domains__crime__genre__idle': 4.157600789251743,
 'domains__crime__genre__idle_na': 2.2965076829016096,
 'domains__crime__genre__match': 0.5888914942238457,
 'domains__crime__genre__party': -0.08145411348040547,
 'domains__crime__genre__party_na': -0.7399061684816436,
 'domains__crime__genre__puzzle': 2.4993966386050324,
 'domains__crime__genre__rpg': 0.6350905946017015,
 'domains__crime__genre__simulation': -1.2426481435428192,
 'domains__crime__genre__sports': 0.028514588950258234,
 'domains__crime__genre__sports_na': 0.08727985706074126,
 'domains__crime__genre__story': -3.753907005078737,
 'domains__crime__genre__story_na': -1.553670710921935,
 'domains__crime__genre__strategy': -0.383234305906671,
 'domains__crime__genre__tabletop': 0.2971181419120646,
 'domains__crime__genre__tabletop_na': -0.22273688284024604,
 'domains__crime__topics__action': -1.036429155389086,
 'domains__crime__topics__adventure': -3.026513270575497,
 'domains__crime__topics__comedy': -0.7241443952073179,
 'domains__crime__topics__drama': 0.8232440067487533,
 'domains__crime__topics__fantasy': 0.9693013517798549,
 'domains__crime__topics__horror': 1.5788641636016236,
 'domains__crime__topics__mystery': -0.28212100789667344,
 'domains__crime__topics__realistic': 1.9018783601061715,
 'domains__crime__topics__romance': -1.437300640956934,
 'domains__crime__topics__sci_fi': 0.24676480067136045,
 'domains__family_ASC': 5.277188405199454,
 'domains__family__age': 0.9951503368374869,
 'domains__family__behaviors__chill': 1.0483516643468627,
 'domains__family__behaviors__collect': -1.4261703107814672,
 'domains__family__behaviors__combat': 0.7263160544208508,
 'domains__family__behaviors__compete': 0.7216978711493026,
 'domains__family__behaviors__complete': -1.3171528528831316,
 'domains__family__behaviors__cooperate': 0.7016444431742341,
 'domains__family__behaviors__destroy': -0.02015583799917448,
 'domains__family__behaviors__discover': 0.4380753701549084,
 'domains__family__behaviors__empower': 0.5979579056702762,
 'domains__family__behaviors__experiment': 1.218005047603578,
 'domains__family__behaviors__express': 1.8490934510045678,
 'domains__family__behaviors__immerse': 0.986098093603282,
 'domains__family__behaviors__plan': 0.5089846680201846,
 'domains__family__behaviors__react': 0.3360208469870159,
 'domains__family__behaviors__solve': -0.18546833056261483,
 'domains__family__genre__arcade': 0.13460805380803037,
 'domains__family__genre__building': -1.6783535766478057,
 'domains__family__genre__building_na': -3.194572587339664,
 'domains__family__genre__casino': -1.3119088851351732,
 'domains__family__genre__combat': -1.4330336048861894,
 'domains__family__genre__driving': 0.49298629549145623,
 'domains__family__genre__driving_na': -1.148056097472603,
 'domains__family__genre__education': -1.4348899743839674,
 'domains__family__genre__education_na': -2.3700074791707637,
 'domains__family__genre__idle': 1.4119930773238822,
 'domains__family__genre__idle_na': -0.9974414784805545,
 'domains__family__genre__match': 0.17804192939280303,
 'domains__family__genre__party': 0.9406863919465458,
 'domains__family__genre__party_na': -2.1636501435962017,
 'domains__family__genre__puzzle': 2.427933064690186,
 'domains__family__genre__rpg': -0.17563107348245088,
 'domains__family__genre__simulation': 0.8271049740663714,
 'domains__family__genre__sports': -1.1470432911257677,
 'domains__family__genre__sports_na': -2.684559451258979,
 'domains__family__genre__story': 0.8630562800692521,
 'domains__family__genre__story_na': -0.4916574097220598,
 'domains__family__genre__strategy': 0.6617007613264062,
 'domains__family__genre__tabletop': -0.32917511658225407,
 'domains__family__genre__tabletop_na': -1.7905966788884824,
 'domains__family__topics__action': -0.8855068052072171,
 'domains__family__topics__adventure': -0.05328401432390701,
 'domains__family__topics__comedy': 1.750364186325117,
 'domains__family__topics__drama': 0.2728846276748446,
 'domains__family__topics__fantasy': -0.9744452465936528,
 'domains__family__topics__horror': 0.4505874319447176,
 'domains__family__topics__mystery': -0.057645552786345276,
 'domains__family__topics__realistic': 1.6651064468844152,
 'domains__family__topics__romance': -0.09795735153835153,
 'domains__family__topics__sci_fi': 1.1405542044925097,
 'domains__fashion_ASC': -16251.187715483577,
 'domains__fashion__age': 1.4758427683219562,
 'domains__fashion__behaviors__chill': 0.9121361223559568,
 'domains__fashion__behaviors__collect': 0.36201399408226176,
 'domains__fashion__behaviors__combat': -1.2966556233274122,
 'domains__fashion__behaviors__compete': -0.3685939885854318,
 'domains__fashion__behaviors__complete': -0.788298978365241,
 'domains__fashion__behaviors__cooperate': 0.5290711590140535,
 'domains__fashion__behaviors__destroy': -0.18303104362662212,
 'domains__fashion__behaviors__discover': 1.4479689053727722,
 'domains__fashion__behaviors__empower': 2.230944276041686,
 'domains__fashion__behaviors__experiment': 0.9311594131663382,
 'domains__fashion__behaviors__express': 0.5668848614249529,
 'domains__fashion__behaviors__immerse': -1.4045172144351492,
 'domains__fashion__behaviors__plan': -1.0833875431211113,
 'domains__fashion__behaviors__react': 0.20890170806570946,
 'domains__fashion__behaviors__solve': 1.3686314491300016,
 'domains__fashion__genre__arcade': 0.2536122190072378,
 'domains__fashion__genre__building': -0.06582947910066723,
 'domains__fashion__genre__building_na': 2706.3910272410353,
 'domains__fashion__genre__casino': -0.2840931514843385,
 'domains__fashion__genre__combat': -1.9079880873543293,
 'domains__fashion__genre__driving': -0.2192395400701049,
 'domains__fashion__genre__driving_na': 2706.69858861,
 'domains__fashion__genre__education': 0.6667933592923262,
 'domains__fashion__genre__education_na': 2708.3988098924638,
 'domains__fashion__genre__idle': 1.4479463312834067,
 'domains__fashion__genre__idle_na': 2706.877109970632,
 'domains__fashion__genre__match': -0.19770103932056063,
 'domains__fashion__genre__party': 1.0087842975293375,
 'domains__fashion__genre__party_na': 2707.8129974072494,
 'domains__fashion__genre__puzzle': -1.7949838048939355,
 'domains__fashion__genre__rpg': 0.23411696150770747,
 'domains__fashion__genre__simulation': 1.2670050402430753,
 'domains__fashion__genre__sports': 0.36955463517492293,
 'domains__fashion__genre__sports_na': 2707.58697778178,
 'domains__fashion__genre__story': 1.764914687119711,
 'domains__fashion__genre__story_na': 2708.4385001086293,
 'domains__fashion__genre__strategy': 0.43770725771477065,
 'domains__fashion__genre__tabletop': 0.5938871108610437,
 'domains__fashion__genre__tabletop_na': 2708.4982500928054,
 'domains__fashion__topics__action': -0.8753851812929501,
 'domains__fashion__topics__adventure': 1.1236464618775337,
 'domains__fashion__topics__comedy': -1.355471904645521,
 'domains__fashion__topics__drama': 4.143475022798852,
 'domains__fashion__topics__fantasy': -0.005335105985682459,
 'domains__fashion__topics__horror': 1.8666525344808396,
 'domains__fashion__topics__mystery': 1.2083332386661874,
 'domains__fashion__topics__realistic': 0.1592086412440473,
 'domains__fashion__topics__romance': -0.2152297342999673,
 'domains__fashion__topics__sci_fi': 1.6355466415973308,
 'domains__food_ASC': -4.194389540848942,
 'domains__food__age': -1.1269112027781572,
 'domains__food__behaviors__chill': 2.649797179455109,
 'domains__food__behaviors__collect': 1.3144017080689543,
 'domains__food__behaviors__combat': 0.9472317335949489,
 'domains__food__behaviors__compete': -0.18327969334961242,
 'domains__food__behaviors__complete': -0.7480273114581003,
 'domains__food__behaviors__cooperate': -0.1237572026389625,
 'domains__food__behaviors__destroy': 1.104487532092687,
 'domains__food__behaviors__discover': 0.010793346566889465,
 'domains__food__behaviors__empower': 0.2648153777014007,
 'domains__food__behaviors__experiment': -0.638493207595102,
 'domains__food__behaviors__express': 0.44287050681143997,
 'domains__food__behaviors__immerse': -0.7508554423731902,
 'domains__food__behaviors__plan': -0.5706036572646028,
 'domains__food__behaviors__react': 1.1055915405432508,
 'domains__food__behaviors__solve': 0.5868256337092571,
 'domains__food__genre__arcade': 0.2529126237334907,
 'domains__food__genre__building': 0.9359375229835752,
 'domains__food__genre__building_na': 0.3010989416448947,
 'domains__food__genre__casino': 0.28004685915356414,
 'domains__food__genre__combat': -2.422835037171188,
 'domains__food__genre__driving': 0.3479404965860413,
 'domains__food__genre__driving_na': 0.5085989632994189,
 'domains__food__genre__education': -2.234581022625273,
 'domains__food__genre__education_na': -2.3113395901343647,
 'domains__food__genre__idle': -1.2108993454447594,
 'domains__food__genre__idle_na': -1.5703790260576764,
 'domains__food__genre__match': 1.9325913944496023,
 'domains__food__genre__party': 3.457685682388054,
 'domains__food__genre__party_na': 2.1433887948398436,
 'domains__food__genre__puzzle': -0.03549906116803716,
 'domains__food__genre__rpg': -0.45668891687454316,
 'domains__food__genre__simulation': -1.0294302914071018,
 'domains__food__genre__sports': -1.108071298744935,
 'domains__food__genre__sports_na': -0.7352123835209675,
 'domains__food__genre__story': 0.7305239925406735,
 'domains__food__genre__story_na': 0.5340481199515265,
 'domains__food__genre__strategy': -0.09843254844787117,
 'domains__food__genre__tabletop': -0.35662949549626494,
 'domains__food__genre__tabletop_na': -0.6073840331602864,
 'domains__food__topics__action': 1.8788949092400289,
 'domains__food__topics__adventure': -0.300169337042335,
 'domains__food__topics__comedy': 0.496826535288399,
 'domains__food__topics__drama': 1.7198897845090584,
 'domains__food__topics__fantasy': 1.2387500069580462,
 'domains__food__topics__horror': -0.13954202182239636,
 'domains__food__topics__mystery': 2.030473404042455,
 'domains__food__topics__realistic': 0.9178915797060282,
 'domains__food__topics__romance': -2.134666355737751,
 'domains__food__topics__sci_fi': -0.008296525837228653,
 'domains__health_ASC': 0.2558527973109941,
 'domains__health__age': -0.9070224670904342,
 'domains__health__behaviors__chill': 1.4947032024313884,
 'domains__health__behaviors__collect': 0.36329593367651253,
 'domains__health__behaviors__combat': -0.11674422829204614,
 'domains__health__behaviors__compete': -0.5537438445788403,
 'domains__health__behaviors__complete': -0.4969532929728873,
 'domains__health__behaviors__cooperate': -1.2859320506458702,
 'domains__health__behaviors__destroy': 1.3948229710853202,
 'domains__health__behaviors__discover': 0.5065961500317956,
 'domains__health__behaviors__empower': 0.25103932432422554,
 'domains__health__behaviors__experiment': 1.4159412756382121,
 'domains__health__behaviors__express': 0.38343664142698536,
 'domains__health__behaviors__immerse': 0.7616433846506224,
 'domains__health__behaviors__plan': 1.2342876481457983,
 'domains__health__behaviors__react': -0.11387694086727934,
 'domains__health__behaviors__solve': -1.194360762784669,
 'domains__health__genre__arcade': -1.011789431062746,
 'domains__health__genre__building': -0.4918639543782186,
 'domains__health__genre__building_na': -0.7445608776667819,
 'domains__health__genre__casino': -0.01050251757308446,
 'domains__health__genre__combat': 0.05070860216002004,
 'domains__health__genre__driving': -1.6465262105191152,
 'domains__health__genre__driving_na': -1.5040845303573898,
 'domains__health__genre__education': -1.1586073495595324,
 'domains__health__genre__education_na': -1.3532311077829802,
 'domains__health__genre__idle': -1.4951074237576514,
 'domains__health__genre__idle_na': -0.9560455035635523,
 'domains__health__genre__match': 0.6113191253909663,
 'domains__health__genre__party': 2.848475948854955,
 'domains__health__genre__party_na': 0.6605610505935293,
 'domains__health__genre__puzzle': 2.939018594637421,
 'domains__health__genre__rpg': -0.49814989077252114,
 'domains__health__genre__simulation': 0.5835354350898815,
 'domains__health__genre__sports': 0.9502789933549344,
 'domains__health__genre__sports_na': -0.6711176370453535,
 'domains__health__genre__story': 1.2374183972132833,
 'domains__health__genre__story_na': 0.44633377675333935,
 'domains__health__genre__strategy': -0.24910396540055216,
 'domains__health__genre__tabletop': -2.0029586139789557,
 'domains__health__genre__tabletop_na': -2.1707504627929475,
 'domains__health__topics__action': 0.4548279034586779,
 'domains__health__topics__adventure': -1.8510847805317128,
 'domains__health__topics__comedy': 0.11495113941076118,

# Postprocess & save data

In [28]:
GENRE_NA_COLS = [
    'genre__building_na',
    'genre__driving_na',
    'genre__education_na',
    'genre__idle_na',
    'genre__party_na',
    'genre__sports_na',
    'genre__story_na',
    'genre__tabletop_na'
]

In [29]:
mechanic_coefs = pickle.load(open("mechanic_coefs_2.p", "rb"))
entity_coefs = pickle.load(open("entity_coefs_2.p", "rb"))
role_coefs = pickle.load(open("role_coefs_2.p", "rb"))
enviro_era_coefs = pickle.load(open("enviro_era_coefs_2.p", "rb"))
focus_domain_coefs = pickle.load(open("focus_domain_coefs_2.p", "rb"))

In [30]:
all_coefs = {**mechanic_coefs, **entity_coefs, **role_coefs, **enviro_era_coefs, **focus_domain_coefs}

In [31]:
{x: y for x, y in all_coefs.items() if 'gender' in x}

{}

In [32]:
# replace _ASC with __base
all_coefs = {(x[:-4] + '__base' if x.endswith('_ASC') else x): y for x, y in all_coefs.items()}

In [33]:
coefs_df = pd.DataFrame(all_coefs, index=['value']).T.reset_index()
coefs_df = coefs_df.rename(columns={'index': 'combined_col'})
coefs_df

                           combined_col     value
0                        core__4x__base -0.288217
1                         core__4x__age -0.269079
2            core__4x__behaviors__chill -0.721520
3          core__4x__behaviors__collect -0.445766
4           core__4x__behaviors__combat  0.591848
...                                 ...       ...
9736     focus__weapons__topics__horror  0.911709
9737    focus__weapons__topics__mystery  0.296231
9738  focus__weapons__topics__realistic -0.598322
9739    focus__weapons__topics__romance -1.859022
9740     focus__weapons__topics__sci_fi  2.726362

[9741 rows x 2 columns]

In [34]:
coefs_df['feature'] = coefs_df.combined_col.apply(lambda x: '__'.join(x.split('__')[:2]) if '___' not in x else ('__'.join(x.split('__')[:2])) + '_')
coefs_df['user_col'] = coefs_df.combined_col.apply(lambda x: '__'.join(x.split('__')[2:]) if '___' not in x else ('__'.join(x.split('__')[2:]))[1:])
coefs_df

,combined_col,value,feature,user_col
0,core__4x__base,-0.288217,core__4x,base
1,core__4x__age,-0.269079,core__4x,age
2,core__4x__behaviors__chill,-0.721520,core__4x,behaviors__chill
3,core__4x__behaviors__collect,-0.445766,core__4x,behaviors__collect
4,core__4x__behaviors__combat,0.591848,core__4x,behaviors__combat
...,...,...,...,...
9736,focus__weapons__topics__horror,0.911709,focus__weapons,topics__horror
9737,focus__weapons__topics__mystery,0.296231,focus__weapons,topics__mystery
9738,focus__weapons__topics__realistic,-0.598322,focus__weapons,topics__realistic
9739,focus__weapons__topics__romance,-1.859022,focus__weapons,topics__romance
9740,focus__weapons__topics__sci_fi,2.726362,focus__weapons,topics__sci_fi

In [35]:
coefs_df.user_col.unique()

array(['base', 'age', 'behaviors__chill', 'behaviors__collect',
       'behaviors__combat', 'behaviors__compete', 'behaviors__complete',
       'behaviors__cooperate', 'behaviors__destroy',
       'behaviors__discover', 'behaviors__empower',
       'behaviors__experiment', 'behaviors__express',
       'behaviors__immerse', 'behaviors__plan', 'behaviors__react',
       'behaviors__solve', 'genre__arcade', 'genre__building',
       'genre__building_na', 'genre__casino', 'genre__combat',
       'genre__driving', 'genre__driving_na', 'genre__education',
       'genre__education_na', 'genre__idle', 'genre__idle_na',
       'genre__match', 'genre__party', 'genre__party_na', 'genre__puzzle',
       'genre__rpg', 'genre__simulation', 'genre__sports',
       'genre__sports_na', 'genre__story', 'genre__story_na',
       'genre__strategy', 'genre__tabletop', 'genre__tabletop_na',
       'topics__action', 'topics__adventure', 'topics__comedy',
       'topics__drama', 'topics__fantasy', 'topics__horror',
       'topics__mystery', 'topics__realistic', 'topics__romance',
       'topics__sci_fi'], dtype=object)

In [36]:
coefs_p_df = coefs_df.pivot(
    index="feature", columns="user_col", values="value"
)

coefs_p_df.index.name = None
coefs_p_df.columns.name = None

coefs_p_df = coefs_p_df[['base', 'age'] + BEHAVIOUR_COLS + GENRE_COLS + GENRE_NA_COLS + TOPIC_COLS] #gender_female
coefs_p_df

,base,age,behaviors__chill,behaviors__collect,behaviors__combat,behaviors__compete,behaviors__complete,behaviors__cooperate,behaviors__destroy,behaviors__discover,...,topics__action,topics__adventure,topics__comedy,topics__drama,topics__fantasy,topics__horror,topics__mystery,topics__realistic,topics__romance,topics__sci_fi
core__4x,-0.288217,-0.269079,-0.721520,-0.445766,0.591848,-0.273289,-0.045995,-0.087741,0.056898,0.317867,...,0.150128,0.133865,-1.158049,0.074926,0.821655,0.088780,0.276168,0.238102,1.050658,0.866008
core__agriculture,-2.095988,3.149500,4.223846,-2.130348,0.783652,-0.829428,6.280429,-3.217267,-0.366344,-1.695354,...,0.519221,-4.713135,-1.636614,-3.874839,-3.050578,3.238996,2.405990,-1.588836,5.940052,2.355202
core__artillery,0.221650,2.887373,1.055477,-2.779875,-0.982867,0.113594,-2.203189,-0.130615,0.599708,1.345202,...,2.522744,-0.506594,-0.247778,-1.433856,3.924468,-0.402212,-2.738111,1.748354,2.228789,0.243054
core__asymetric,0.077696,-1.169540,0.064858,0.683366,2.218087,1.994487,-1.111897,-0.855222,1.077095,-1.093263,...,-1.965813,-1.915937,-1.082739,1.394624,-0.274317,0.822699,2.357365,2.005242,-0.012946,1.058445
core__auto_chess,-0.346815,0.567837,0.053205,-0.104938,-0.045398,-0.246239,-0.779069,0.047883,0.438725,-1.213328,...,0.565337,-0.101891,-0.784482,0.267178,0.526424,0.027829,-0.083057,1.073358,0.693864,0.375522
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
roles__rebel,0.751686,0.655068,0.184663,0.388596,0.351097,0.395381,0.229533,0.632679,0.518670,1.676821,...,-0.108339,0.380862,0.107868,-0.267716,0.193756,0.896328,0.462004,0.208374,0.489269,0.707283
roles__solver,0.964600,0.152337,0.557487,-0.272942,0.456544,-0.111690,-1.631243,0.885063,0.456824,1.582681,...,-0.942705,0.028290,-0.328575,-0.853055,0.579779,-0.121151,1.504823,0.578005,0.138080,1.540291
roles__team,0.083764,1.284258,0.855827,1.302641,-0.454301,0.618478,-0.389286,1.107102,0.398236,0.174405,...,0.472611,0.880932,-0.011424,0.392401,0.850078,0.750251,-0.137671,0.413312,-0.937953,0.661336
roles__villain,-1.135686,0.228337,0.659040,-0.136965,0.639805,0.467726,-1.251640,0.705736,0.448906,0.870515,...,-0.050766,0.743828,-0.389327,0.475194,0.991958,1.296251,-0.264078,0.341225,0.356898,1.390100
roles__warrior,-1.290862,1.254385,0.020261,0.599831,0.515461,0.363505,-0.805958,1.243899,0.167656,1.654446,...,0.069823,0.264920,-0.762622,-0.615061,1.271305,1.521173,-0.029274,0.000764,-0.020722,1.282671

In [37]:
coefs_p_df.reset_index()

,index,base,age,behaviors__chill,behaviors__collect,behaviors__combat,behaviors__compete,behaviors__complete,behaviors__cooperate,behaviors__destroy,...,topics__action,topics__adventure,topics__comedy,topics__drama,topics__fantasy,topics__horror,topics__mystery,topics__realistic,topics__romance,topics__sci_fi
0,core__4x,-0.288217,-0.269079,-0.721520,-0.445766,0.591848,-0.273289,-0.045995,-0.087741,0.056898,...,0.150128,0.133865,-1.158049,0.074926,0.821655,0.088780,0.276168,0.238102,1.050658,0.866008
1,core__agriculture,-2.095988,3.149500,4.223846,-2.130348,0.783652,-0.829428,6.280429,-3.217267,-0.366344,...,0.519221,-4.713135,-1.636614,-3.874839,-3.050578,3.238996,2.405990,-1.588836,5.940052,2.355202
2,core__artillery,0.221650,2.887373,1.055477,-2.779875,-0.982867,0.113594,-2.203189,-0.130615,0.599708,...,2.522744,-0.506594,-0.247778,-1.433856,3.924468,-0.402212,-2.738111,1.748354,2.228789,0.243054
3,core__asymetric,0.077696,-1.169540,0.064858,0.683366,2.218087,1.994487,-1.111897,-0.855222,1.077095,...,-1.965813,-1.915937,-1.082739,1.394624,-0.274317,0.822699,2.357365,2.005242,-0.012946,1.058445
4,core__auto_chess,-0.346815,0.567837,0.053205,-0.104938,-0.045398,-0.246239,-0.779069,0.047883,0.438725,...,0.565337,-0.101891,-0.784482,0.267178,0.526424,0.027829,-0.083057,1.073358,0.693864,0.375522
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,roles__rebel,0.751686,0.655068,0.184663,0.388596,0.351097,0.395381,0.229533,0.632679,0.518670,...,-0.108339,0.380862,0.107868,-0.267716,0.193756,0.896328,0.462004,0.208374,0.489269,0.707283
187,roles__solver,0.964600,0.152337,0.557487,-0.272942,0.456544,-0.111690,-1.631243,0.885063,0.456824,...,-0.942705,0.028290,-0.328575,-0.853055,0.579779,-0.121151,1.504823,0.578005,0.138080,1.540291
188,roles__team,0.083764,1.284258,0.855827,1.302641,-0.454301,0.618478,-0.389286,1.107102,0.398236,...,0.472611,0.880932,-0.011424,0.392401,0.850078,0.750251,-0.137671,0.413312,-0.937953,0.661336
189,roles__villain,-1.135686,0.228337,0.659040,-0.136965,0.639805,0.467726,-1.251640,0.705736,0.448906,...,-0.050766,0.743828,-0.389327,0.475194,0.991958,1.296251,-0.264078,0.341225,0.356898,1.390100
190,roles__warrior,-1.290862,1.254385,0.020261,0.599831,0.515461,0.363505,-0.805958,1.243899,0.167656,...,0.069823,0.264920,-0.762622,-0.615061,1.271305,1.521173,-0.029274,0.000764,-0.020722,1.282671

### Check coefs for all users

In [38]:
coef_cols = []

for col in coefs_p_df.index:
    coef_col = pd.Series([coefs_p_df.loc[col, 'base']]*len(user_df), name=col)
    
    for user_col in coefs_p_df.columns[1:]:
        user_col_min = user_df[user_col].min()
        user_col_max = user_df[user_col].max()
        
        # min-max scaling -> 0-1
        coef_col += ((user_df[user_col] - user_col_min) / (user_col_max - user_col_min)) * coefs_p_df.loc[col, user_col]
    
    coef_cols.append(coef_col)

In [39]:
test_df = pd.concat(coef_cols, axis=1)
test_df['survey_instance'] = user_df['survey_instance']

In [40]:
test_df['gender_female'] = user_df['gender_female']

In [41]:
gender_df = test_df.groupby('gender_female').mean().T
gender_df['category'] = gender_df.index.to_series().apply(lambda x: x.split('__')[0])
category_df = gender_df.groupby('category').mean()
category_gender_boost_dict = (category_df[0] - category_df[1]).to_dict()

In [42]:
category_gender_boost_dict

{'core': 0.4592130914385406,
 'domains': 1.05912611533794,
 'entities': 1.3250699504754553,
 'environment': 0.7538794755434801,
 'eras': 1.0339127471304197,
 'focus': 1.132667886078633,
 'roles': 1.1079398004491734}

In [43]:
coefs_p_df['gender_female'] = gender_df.category.apply(lambda x: category_gender_boost_dict[x])

In [44]:
coefs_p_df

,base,age,behaviors__chill,behaviors__collect,behaviors__combat,behaviors__compete,behaviors__complete,behaviors__cooperate,behaviors__destroy,behaviors__discover,...,topics__adventure,topics__comedy,topics__drama,topics__fantasy,topics__horror,topics__mystery,topics__realistic,topics__romance,topics__sci_fi,gender_female
core__4x,-0.288217,-0.269079,-0.721520,-0.445766,0.591848,-0.273289,-0.045995,-0.087741,0.056898,0.317867,...,0.133865,-1.158049,0.074926,0.821655,0.088780,0.276168,0.238102,1.050658,0.866008,0.459213
core__agriculture,-2.095988,3.149500,4.223846,-2.130348,0.783652,-0.829428,6.280429,-3.217267,-0.366344,-1.695354,...,-4.713135,-1.636614,-3.874839,-3.050578,3.238996,2.405990,-1.588836,5.940052,2.355202,0.459213
core__artillery,0.221650,2.887373,1.055477,-2.779875,-0.982867,0.113594,-2.203189,-0.130615,0.599708,1.345202,...,-0.506594,-0.247778,-1.433856,3.924468,-0.402212,-2.738111,1.748354,2.228789,0.243054,0.459213
core__asymetric,0.077696,-1.169540,0.064858,0.683366,2.218087,1.994487,-1.111897,-0.855222,1.077095,-1.093263,...,-1.915937,-1.082739,1.394624,-0.274317,0.822699,2.357365,2.005242,-0.012946,1.058445,0.459213
core__auto_chess,-0.346815,0.567837,0.053205,-0.104938,-0.045398,-0.246239,-0.779069,0.047883,0.438725,-1.213328,...,-0.101891,-0.784482,0.267178,0.526424,0.027829,-0.083057,1.073358,0.693864,0.375522,0.459213
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
roles__rebel,0.751686,0.655068,0.184663,0.388596,0.351097,0.395381,0.229533,0.632679,0.518670,1.676821,...,0.380862,0.107868,-0.267716,0.193756,0.896328,0.462004,0.208374,0.489269,0.707283,1.107940
roles__solver,0.964600,0.152337,0.557487,-0.272942,0.456544,-0.111690,-1.631243,0.885063,0.456824,1.582681,...,0.028290,-0.328575,-0.853055,0.579779,-0.121151,1.504823,0.578005,0.138080,1.540291,1.107940
roles__team,0.083764,1.284258,0.855827,1.302641,-0.454301,0.618478,-0.389286,1.107102,0.398236,0.174405,...,0.880932,-0.011424,0.392401,0.850078,0.750251,-0.137671,0.413312,-0.937953,0.661336,1.107940
roles__villain,-1.135686,0.228337,0.659040,-0.136965,0.639805,0.467726,-1.251640,0.705736,0.448906,0.870515,...,0.743828,-0.389327,0.475194,0.991958,1.296251,-0.264078,0.341225,0.356898,1.390100,1.107940
roles__warrior,-1.290862,1.254385,0.020261,0.599831,0.515461,0.363505,-0.805958,1.243899,0.167656,1.654446,...,0.264920,-0.762622,-0.615061,1.271305,1.521173,-0.029274,0.000764,-0.020722,1.282671,1.107940

In [46]:
test_df

,core__4x,core__agriculture,core__artillery,core__asymetric,core__auto_chess,core__automation,core__backtracking,core__ball,core__baseball,core__basketball,...,roles__explorer,roles__follower,roles__mystic,roles__rebel,roles__solver,roles__team,roles__villain,roles__warrior,survey_instance,gender_female
0,2.754849,1.041384,1.068867,0.946033,1.147250,0.141344,2.237014,1.824652,0.589785,-2.872531,...,1.933209,1.602612,2.145300,1.671991,1.220235,1.121867,1.606129,1.855041,33cbe449-af6a-484b-a521-6a4d08f73454,1
1,2.518849,6.859815,1.514870,4.370928,3.450785,-0.408321,4.274114,2.172749,3.731515,8.392953,...,3.924299,2.051001,3.591273,2.847747,2.371497,2.031164,2.554284,2.151207,5db16995-594b-4b4e-9151-e502b85d6ff3,0
2,-0.550507,-10.337764,6.668011,-5.697838,0.873933,3.758818,-1.163995,1.418757,4.971516,-1.615916,...,-1.257699,0.432299,0.643819,-1.969505,-0.380333,0.648706,0.637378,0.786648,9722c487-9a13-4a9d-8599-577b69805034,1
3,3.316473,17.242549,3.187699,3.523599,2.622949,3.321279,3.233665,3.085486,-5.487018,11.536411,...,3.222076,2.880099,4.002295,3.790279,3.523843,2.752532,2.958466,4.576350,7094ec2f-88d4-4642-90f6-f12b41eca4f1,0
4,2.680931,2.961865,5.807817,3.795726,1.878644,-1.659182,3.523439,3.714703,3.400149,3.641580,...,3.884730,2.199074,2.534741,2.178480,1.961275,2.752727,2.156843,3.298265,eb6a4d45-c680-4eaf-bef7-aebe5edb7ce0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1965,4.178016,5.803082,1.591647,1.916382,3.616533,4.585763,2.480446,3.108865,-0.935953,-3.349519,...,2.996723,2.147984,3.180166,2.668171,2.455445,2.268175,2.543349,2.300299,35fc0bbf-cef7-4ad9-b0c7-8bfb50043cc3,0
1966,1.439444,1.221211,-6.904302,0.046238,-0.216698,0.367566,2.663422,0.420181,0.656237,-0.663239,...,-0.305527,-1.340316,-1.606243,-0.021790,0.546096,0.020058,0.422941,-0.349778,b11b6d9c-f739-478a-ab26-d26d11825827,0
1967,3.113234,3.424641,-3.125021,-0.246251,0.938250,1.390719,1.381462,2.269673,-2.976818,1.837184,...,2.626441,2.044420,1.601704,2.251623,3.599893,1.862688,2.282003,3.300912,e9c3e858-826f-479e-a85d-6ea3b0e4e43a,0
1968,1.377966,-3.902136,2.224523,-5.089354,1.928476,3.213606,2.594824,1.194597,-8.501987,2.497875,...,1.479377,0.860811,1.901919,2.053584,0.296282,2.680320,1.678849,3.574843,b6e5ec83-0b04-4f2d-8d54-1bc0d6785adc,0
1969,-0.086918,2.010470,1.177598,3.867110,0.603260,0.601850,2.434525,1.400435,8.461650,3.687591,...,3.029352,1.337409,1.824479,2.113941,2.462225,0.880872,1.553192,1.578079,8ec75988-2510-4d41-b5da-456e237c2574,0

In [56]:
coef_cols = []

for col in coefs_p_df.index:
    coef_col = pd.Series([coefs_p_df.loc[col, 'base']]*len(user_df), name=col)
    
    for user_col in coefs_p_df.columns[1:]:
        user_col_min = user_df[user_col].min()
        user_col_max = user_df[user_col].max()
        
        # min-max scaling -> 0-1
        coef_col += ((user_df[user_col] - user_col_min) / (user_col_max - user_col_min)) * coefs_p_df.loc[col, user_col]
    
    coef_cols.append(coef_col)

In [57]:
test_df = pd.concat(coef_cols, axis=1)
test_df['survey_instance'] = user_df['survey_instance']

In [50]:
test_df['gender_female'] = user_df['gender_female']

In [55]:
with pd.option_context('display.max_columns', 500):
    display(test_df.groupby('gender_female').mean())

,core__4x,core__agriculture,core__artillery,core__asymetric,core__auto_chess,core__automation,core__backtracking,core__ball,core__baseball,core__basketball,core__betrayal,core__bingo,core__blackjack,core__blast,core__board,core__brain,core__branched_story,core__brawl,core__bubble,core__bullet_hell,core__cards,core__caring,core__ccg,core__chess,core__coloring,core__combos,core__connect,core__construct,core__control_time,core__cover_fire,core__crafting,core__crush_bricks,core__dare,core__dating,core__deathmatch,core__design,core__dialogue_tree,core__dice,core__differences,core__domino,core__dress_up,core__escape_room,core__esports,core__fighter,core__fishing,core__flying,core__football,core__full_motion_video,core__golf,core__grow_wealth,core__guess,core__hand_to_hand,core__hidden_object,core__hockey,core__hunting,core__jigsaw,core__karaoke,core__klotski,core__lane,core__legion,core__life,core__linear_story,core__loftto,core__luck_battle,core__mahjong,core__manage_inventory,core__management,core__martial,core__match_tile,core__maze,core__melee,core__merge,core__minesweeper,core__mini_games,core__mmo,core__moba,core__moral_choices,core__move_blocks,core__nonogram,core__okey,core__open_world,core__parkour,core__physics,core__platformer,core__poker,core__push_coin,core__racing,core__random_loot,core__restore,core__rhythm,core__road_driving,core__roguelike,core__royale,core__runner,core__sailing,core__sandbox,core__shark,core__skating,core__skill_tree,core__slicing,core__slots,core__sniper,core__soccer,core__solitaire,core__sort water,core__stealth,core__sudoku,core__summon,core__survival,core__swapping,core__switch,core__tactical,core__taming,core__telekinesis,core__tennis,core__time_attack,core__time_loop,core__tower_defense,core__trading,core__trivia,core__upgrading,core__vehicular,core__word,domains__art,domains__business,domains__crime,domains__family,domains__fashion,domains__food,domains__health,domains__luxury,domains__military,domains__mythology,domains__nature,domains__politics,domains__religion,domains__rights,domains__sports,entities__adult,entities__alien,entities__animal,entities__celestial,entities__elder,entities__human,entities__kid,entities__microbe,entities__monster,entities__plant,entities__robot,entities__super_,entities__zombie,environment__alternality,environment__aquatic,environment__rural,environment__space,environment__suburban,environment__urban,environment__virtuality,environment__wilderness,eras__ancient,eras__industrial,eras__medieval,eras__modern,eras__near_future,eras__prehistoric,eras__renaissance,eras__retro,eras__timeless,focus__actors,focus__bases,focus__cities,focus__events,focus__interiors,focus__levels,focus__objects,focus__self,focus__solutions,focus__structures,focus__vehicles,focus__weapons,roles__authority,roles__carer,roles__creator,roles__explorer,roles__follower,roles__mystic,roles__rebel,roles__solver,roles__team,roles__villain,roles__warrior
gender_female,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,1.913623,2.288986,2.039414,0.901697,1.562333,1.288123,1.828587,1.714475,-2.335257,1.534117,-1.517954,1.827774,2.035344,2.082371,1.868619,2.076658,3.846240,1.870364,2.164456,1.554646,0.916450,1.677375,2.315219,1.821980,0.255419,1.497009,2.122965,1.474276,1.667517,1.468424,1.691395,1.603547,2.078026,0.007089,2.209160,1.893465,2.605522,3.379457,1.820804,1.795178,0.316120,2.179821,1.837648,1.465432,1.226890,2.180447,2.697344,6.343316,0.930127,2.635924,4.399781,1.836525,1.810475,1.613560,1.298913,1.676347,3.629652,1.921278,1.818499,1.739633,2.025198,2.989233,1.559443,3.465340,4.403665,1.499283,1.984165,0.322203,2.030280,1.880257,1.116858,2.316742,1.175651,2.925398,1.338443,1.323269,15.234529,1.855331,1.764527,1.301345,2.166382,1.779508,1.836115,1.733423,2.096029,2.042813,-9.240824,2.033297,3.633605,1.582601,3.851346,0.435413,1.363227,1.787261,-2.580843,2.732433,1.786756,2.391542,1.953518,1.168545,2.084195,1.738572,1.639853,1.635656,1.581944,1.714158,2.097030,1.661708,1.432350,1.084663,2.179786,1.651114,1.201427,1.434595,1.412314,2.604066,1.467140,1.749137,4.579495,7.014124,2.072748,1.745397,2.093792,1.694128,1.749054,2.471035,1.896942,0.975176,0.928138,1.446143,1.795189,2.294813,2.161675,1.881154,1.037929,0.786159,1.822277,1.275096,1.527114,1.850410,1.711889,1.708270,1.445915,2.161118,0.753775,1.097513,2.172177,0.88603,1.593048,2.535569,1.856353,1.904408,1.683346,1.213588,1.743577,1.551015,1.755801,1.494704,1.650338,2.117486,1.527064,1.747019,2.117504,2.162641,1.341742,1.743975,1.730172,1.661671,2.003800,2.259359,2.531909,2.147392,1.746890,2.316526,2.234323,1.847859,2.012434,2.629031,2.075952,2.538661,1.486856,1.577048,1.507710,1.867951,1.176697,1.618536,1.471815,1.376746,1.228379,1.722702,1.866488
1,1.613636,2.603954,0.924129,0.404153,1.791978,1.857721,1.691886,1.769967,-2.929269,1.237392,2.326559,2.358757,2.040482,2.078791,0.820734,2.403078,6.374881,1.739712,2.450401,0.948160,1.928822,2.191580,5.014244,2.045822,0.122087,2.179741,2.437994,1.981570,1.604833,1.599712,2.371434,1.841881,1.458649,0.399242,2.464117,2.746072,3.806222,4.409109,2.144257,1.203643,1.233375,2.196562,2.119328,1.233267,0.627535,1.673729,2.463366,9.486676,0.851776,1.619084,3.266651,0.768822,2.270162,2.015796,0.408401,2.271753,2.186526,2.202938,1.246783,1.339932,2.009127,2.405084,1.748601,4.011006,3.332295,1.522332,0.978382,0.965857,2.279797,1.794622,0.151827,2.356566,0.827281,2.620954,1.703786,0.438543,11.483753,1.796096,1.963119,1.414138,2.092779,1.709240,1.332772,1.134126,2.223219,2.288001,-5.610113,2.206819,2.846832,1.641994,2.640089,-0.519925,0.478859,1.941365,-2.437940,1.607135,1.428577,2.639327,2.133422,1.440027,2.345642,1.521287,2.131198,4.067603,1.681744,1.457153,1.972672,1.369411,0.453146,1.291380,2.318007,1.469371,0.753279,1.298428,1.720499,2.755412,1.414226,1.328656,2.574254,5.116755,1.906009,0.982392,2.452305,1.730318,1.688733,2.761599,2.247499,2.047957,1.677998,1.903992,2.039760,0.373632,2.198108,2.239147,0.420369,0.283553,1.690320,0.911922,2.038447,1.408988,2.194317,1.513787,1.321816,2.958047,1.309160,1.414959,1.526569,1.33374,0.896062,2.133784,1.249505,1.587701,1.738647,1.431122,1.485526,1.610501,1.619801,1.666454,1.857027,2.125051,1.404176,1.942993,2.102103,1.694729,1.312365,1.662447,1.877505,2.027906,2.062195,2.026856,3.013952,2.575921,1.434142,2.456784,2.741839,2.127097,2.081214,2.540626,2.003427,1.280084,1.726503,1.591412,1.916495,2.026303,1.243464,1.648228,1.291494,1.224805,1.373747,1.451227,1.407252

In [58]:
# df_guid = '057c206c-42b5-4f6d-915d-4f772f13e761'
# df_guid = 'be8b281a-5fa9-4308-8b23-0f1ff92f1070'
df_guid = '0ce01ac6-d0b0-4b79-b89c-a68f4c7a783b'

In [64]:
write_df_to_db(conn, test_df, df_guid)

In [65]:
conn.close()

In [72]:
test_df.mean().to_dict()

{'core__4x': 1.7024892484165792,
 'core__agriculture': 2.5886451886238535,
 'core__artillery': 1.8015088940091166,
 'core__asymetric': 0.6030392729400657,
 'core__auto_chess': 1.543783499788681,
 'core__automation': 1.5088269251738249,
 'core__backtracking': 1.4606976421753353,
 'core__ball': 1.5433171668091503,
 'core__baseball': -10.558695286787964,
 'core__basketball': 0.8492632946642641,
 'core__betrayal': -3.2205453719609975,
 'core__bingo': 2.094342594593271,
 'core__blackjack': 1.9992802769711997,
 'core__blast': 1.9063204632896393,
 'core__board': -1.9265158861488378,
 'core__brain': 2.2940678343952174,
 'core__branched_story': 0.9492715399813214,
 'core__brawl': 1.4896816496463638,
 'core__bubble': 2.206965953559486,
 'core__bullet_hell': 1.2738227995311642,
 'core__cards': 1.5011162122865584,
 'core__caring': 1.805482057149928,
 'core__ccg': 3.0438508251479925,
 'core__chess': 3.890170351039853,
 'core__coloring': -0.40890082057816735,
 'core__combos': 2.089763097713083,
 'core__connect': 2.1637464092788083,
 'core__construct': -3.335301311885065,
 'core__control_time': 1.415100650442821,
 'core__cover_fire': 1.433992636995654,
 'core__crafting': 1.9345231589055119,
 'core__crush_bricks': 1.580186653594636,
 'core__dare': 1.4745644714648447,
 'core__dating': -0.4602219145368065,
 'core__deathmatch': 2.517922727424219,
 'core__design': 2.3980536197280746,
 'core__dialogue_tree': -1.60156370195569,
 'core__dice': 2.976005214155123,
 'core__differences': 1.8728138469200628,
 'core__domino': -6.210080886270865,
 'core__dress_up': 0.8633520031334485,
 'core__escape_room': 2.1905803310533947,
 'core__esports': 3.444249129630608,
 'core__fighter': 1.0050449823347258,
 'core__fishing': 0.5065573009553853,
 'core__flying': 5.713427010569332,
 'core__football': 0.11149760020839494,
 'core__full_motion_video': 8.502131606901514,
 'core__golf': -0.010654165121832107,
 'core__grow_wealth': 1.4642893542528745,
 'core__guess': 4.500135789928521,
 'core__hand_to_hand': 1.5188887372028417,
 'core__hidden_object': 2.0409907143440407,
 'core__hockey': 0.346589058360564,
 'core__hunting': 0.3801430319351593,
 'core__jigsaw': 1.8955697919580845,
 'core__karaoke': 8.832032021609004,
 'core__klotski': 1.9686696644108908,
 'core__lane': 1.2893915349263105,
 'core__legion': 1.2515552185998122,
 'core__life': 2.0532271200071825,
 'core__linear_story': 2.251101603596546,
 'core__loftto': 1.474142893409297,
 'core__luck_battle': 7.218833571797205,
 'core__mahjong': 4.307617724307196,
 'core__manage_inventory': 1.212963121958568,
 'core__management': -0.1619480113261803,
 'core__martial': -1.706547490008568,
 'core__match_tile': 2.1298131906699598,
 'core__maze': 1.7025857119963472,
 'core__melee': -0.10997283113070191,
 'core__merge': 2.222447025213752,
 'core__minesweeper': 0.6126412967233598,
 'core__mini_games': 3.408897318929788,
 'core__mmo': 0.8982257665977883,
 'core__moba': 0.5337198180454464,
 'core__moral_choices': 4.486894898749628,
 'core__move_blocks': 1.7492807188842248,
 'core__nonogram': 1.7717568869947955,
 'core__okey': 1.106116240502392,
 'core__open_world': 2.0907605498260264,
 'core__parkour': -1.680379993426731,
 'core__physics': 1.3538089377694686,
 'core__platformer': 1.208038642411947,
 'core__poker': 2.0355110596546577,
 'core__push_coin': 2.0981489533433297,
 'core__racing': -4.204877532043385,
 'core__random_loot': 2.217734572253916,
 'core__restore': 2.6490214356052,
 'core__rhythm': 1.3646978235773195,
 'core__road_driving': 3.7496731275847903,
 'core__roguelike': -0.719373385412368,
 'core__royale': 0.21761997352242604,
 'core__runner': 1.7746389805260234,
 'core__sailing': -4.107525504702343,
 'core__sandbox': 2.005280132821229,
 'core__shark': 1.4550389752866042,
 'core__skating': 1.3121806517953982,
 'core__skill_tree': 1.946672631363855,
 'core__slicing': 1.0909094230782814,
 'core__slots': 2.2241987339380827,
 'core__sniper': 1.2950154801417035,
 'core__soccer': 1.3160078234577428,
 'core__solitaire': -3.1918346900825885,
 'core__sort water': 1.3867252865081618,
 'core__stealth': 1.812364508231659,
 'core__sudoku': 1.9831035282529126,
 'core__summon': 1.312090206028967,
 'core__survival': 0.7399439746715818,
 'core__swapping': 0.7929744554681156,
 'core__switch': 2.125906028401811,
 'core__tactical': 1.3638351057831213,
 'core__taming': 0.48250416625244724,
 'core__telekinesis': 1.1009516414427658,
 'core__tennis': 2.397494341895786,
 'core__time_attack': 3.1052298384700445,
 'core__time_loop': 1.222149424597763,
 'core__tower_defense': 1.3065093600063953,
 'core__trading': 1.8520223812117143,
 'core__trivia': 9.824841807279121,
 'core__upgrading': 1.8927058174827756,
 'core__vehicular': 0.8996344999045892,
 'core__word': 2.3371947242970617,
 'domains__art': 1.232721186138478,
 'domains__business': 1.1870063627037208,
 'domains__crime': 2.133400227506989,
 'domains__family': 1.5342810522785264,
 'domains__fashion': 0.997067883155195,
 'domains__food': 0.7993930771616924,
 'domains__health': 1.11937191138686,
 'domains__luxury': 1.350965902447429,
 'domains__military': 0.7026500062969846,
 'domains__mythology': 1.6408869929153258,
 'domains__nature': 1.5464578613052393,
 'domains__politics': 0.1826216425351006,
 'domains__religion': 0.02137626756094698,
 'domains__rights': 1.2582793785358282,
 'domains__sports': 0.5554021215846835,
 'entities__adult': 1.1248595916440625,
 'entities__alien': 0.9407890660273486,
 'entities__animal': 1.2895595056174263,
 'entities__celestial': 0.9362888095845265,
 'entities__elder': 0.7010619696539637,
 'entities__human': 1.889570543450932,
 'entities__kid': 0.3615131676384069,
 'entities__microbe': 0.5875244409227396,
 'entities__monster': 1.1820730137601072,
 'entities__plant': 0.4394482424853813,
 'entities__robot': 0.5711644308412424,
 'entities__super_': 1.6598510063248526,
 'entities__zombie': 0.8742009273363102,
 'environment__alternality': 1.3759805065080521,
 'environment__aquatic': 1.3326456539333427,
 'environment__rural': 0.9433010869917259,
 'environment__space': 1.2301811855708962,
 'environment__suburban': 1.2032647470242588,
 'environment__urban': 1.3073914903302342,
 'environment__virtuality': 1.1843765924535485,
 'environment__wilderness': 1.3586359335504317,
 'eras__ancient': 1.5978583457295243,
 'eras__industrial': 0.949015734295877,
 'eras__medieval': 1.3329631171310201,
 'eras__modern': 1.5755601649936968,
 'eras__near_future': 1.41296756959523,
 'eras__prehistoric': 0.8013255783696662,
 'eras__renaissance': 1.1960804031746077,
 'eras__retro': 1.270116863235161,
 'eras__timeless': 1.3282872661747225,
 'focus__actors': 1.5031540933104863,
 'focus__bases': 1.5967267289179543,
 'focus__cities': 2.2108526089207285,
 'focus__events': 1.8022432376752313,
 'focus__interiors': 1.0338581337263046,
 'focus__levels': 1.81936519443786,
 'focus__objects': 1.9359074737206585,
 'focus__self': 1.3645026821165167,
 'focus__solutions': 1.5064691247555486,
 'focus__structures': 2.0460505159675226,
 'focus__vehicles': 1.477943528542924,
 'focus__weapons': 1.3015020986914592,
 'roles__authority': 1.02354691592494,
 'roles__carer': 1.0257078215165214,
 'roles__creator': 1.163067986199475,
 'roles__explorer': 1.3807634458313491,
 'roles__follower': 0.6468108344973269,
 'roles__mystic': 1.061785078476423,
 'roles__rebel': 0.8161205149449412,
 'roles__solver': 0.7447054618932641,
 'roles__team': 0.7388020456863151,
 'roles__villain': 1.01259148807023,
 'roles__warrior': 1.06707501544044}

In [73]:
test_df.std().to_dict()

{'core__4x': 1.6023195395664127,
 'core__agriculture': 4.038787846063806,
 'core__artillery': 5.156294753562237,
 'core__asymetric': 3.4036516192031456,
 'core__auto_chess': 1.5615137341315917,
 'core__automation': 4.145596343959279,
 'core__backtracking': 1.8883715533110081,
 'core__ball': 1.656460314441771,
 'core__baseball': 16.050280969275118,
 'core__basketball': 13.305495388072883,
 'core__betrayal': 21.68240958444509,
 'core__bingo': 0.8722477114527342,
 'core__blackjack': 1.2478444370280077,
 'core__blast': 1.3040943602362864,
 'core__board': 18.892831974338986,
 'core__brain': 1.0692101280519934,
 'core__branched_story': 5.7182815741425035,
 'core__brawl': 2.7308743239487856,
 'core__bubble': 0.7444383787271265,
 'core__bullet_hell': 3.3824291862166085,
 'core__cards': 11.171155003648808,
 'core__caring': 3.0398483119434156,
 'core__ccg': 7.594419659105374,
 'core__chess': 7.606160804189169,
 'core__coloring': 16.374273888076576,
 'core__combos': 4.824936916449704,
 'core__connect': 0.7817938691186798,
 'core__construct': 9.02464167792327,
 'core__control_time': 1.6457160315253272,
 'core__cover_fire': 3.015839113954653,
 'core__crafting': 1.8671117474450096,
 'core__crush_bricks': 1.5184281425019517,
 'core__dare': 8.074866259184981,
 'core__dating': 4.035132700931259,
 'core__deathmatch': 2.057301222656002,
 'core__design': 14.517558608464391,
 'core__dialogue_tree': 17.84772114104813,
 'core__dice': 12.878058174977973,
 'core__differences': 1.2190813895176205,
 'core__domino': 14.856679774880787,
 'core__dress_up': 3.174016625910273,
 'core__escape_room': 1.6376360985316576,
 'core__esports': 6.0963607795137715,
 'core__fighter': 1.889937241677385,
 'core__fishing': 7.203458327774241,
 'core__flying': 12.27677382424832,
 'core__football': 15.033701239523875,
 'core__full_motion_video': 21.421231477636994,
 'core__golf': 20.923612830608718,
 'core__grow_wealth': 6.894705518982641,
 'core__guess': 9.152391830823923,
 'core__hand_to_hand': 2.4645653418946707,
 'core__hidden_object': 1.0937239528136484,
 'core__hockey': 2.2321536295502833,
 'core__hunting': 5.273796125650033,
 'core__jigsaw': 1.6200278087986206,
 'core__karaoke': 16.499790451080184,
 'core__klotski': 1.6672022648127083,
 'core__lane': 2.284574680823807,
 'core__legion': 1.8273054864048877,
 'core__life': 1.548887729272956,
 'core__linear_story': 10.347975038783646,
 'core__loftto': 1.1059091391038893,
 'core__luck_battle': 20.03086535372616,
 'core__mahjong': 7.9342124499502225,
 'core__manage_inventory': 2.346916399421139,
 'core__management': 10.591734882003443,
 'core__martial': 14.456317071520754,
 'core__match_tile': 1.0387262630050815,
 'core__maze': 1.7922641637616494,
 'core__melee': 4.319900454948101,
 'core__merge': 0.9527291400060465,
 'core__minesweeper': 2.8792517584912436,
 'core__mini_games': 15.089956896963834,
 'core__mmo': 2.3445964807048085,
 'core__moba': 3.1389104913913153,
 'core__moral_choices': 18.02971998368227,
 'core__move_blocks': 1.8576476592115887,
 'core__nonogram': 1.5099097839540772,
 'core__okey': 1.7200032433860282,
 'core__open_world': 1.3281078753334634,
 'core__parkour': 8.5121223431848,
 'core__physics': 2.4510573187563005,
 'core__platformer': 1.7702148898226946,
 'core__poker': 1.0966457829767182,
 'core__push_coin': 0.9111425855037735,
 'core__racing': 35.906477389091265,
 'core__random_loot': 1.2787370416523776,
 'core__restore': 4.73761677822168,
 'core__rhythm': 1.59754366837935,
 'core__road_driving': 8.647158253218564,
 'core__roguelike': 3.4960674548474873,
 'core__royale': 4.104907618382798,
 'core__runner': 1.138827846234456,
 'core__sailing': 13.522935437368815,
 'core__sandbox': 3.114851001297037,
 'core__shark': 1.7667885905419556,
 'core__skating': 2.1209623839201037,
 'core__skill_tree': 1.3147929825176685,
 'core__slicing': 1.7963527393727134,
 'core__slots': 0.6686902502759348,
 'core__sniper': 2.9700246029380186,
 'core__soccer': 6.127719440187767,
 'core__solitaire': 17.172038003917077,
 'core__sort water': 1.5854302952883763,
 'core__stealth': 2.663956985221489,
 'core__sudoku': 1.5213385045431704,
 'core__summon': 1.7919604516096101,
 'core__survival': 2.580139648171286,
 'core__swapping': 2.25291057499243,
 'core__switch': 0.9411017581524567,
 'core__tactical': 2.4786559755101596,
 'core__taming': 4.544059624700074,
 'core__telekinesis': 2.3798310142317844,
 'core__tennis': 6.089905858458006,
 'core__time_attack': 12.256901208799508,
 'core__time_loop': 2.1421159380519628,
 'core__tower_defense': 1.7944814970981646,
 'core__trading': 13.256888054399834,
 'core__trivia': 13.514945470911808,
 'core__upgrading': 1.46172221384355,
 'core__vehicular': 3.079352057772798,
 'core__word': 1.314065497720073,
 'domains__art': 2.4374953724660324,
 'domains__business': 2.091599931411246,
 'domains__crime': 2.457013038529488,
 'domains__family': 2.369960274207578,
 'domains__fashion': 2.7128380544567365,
 'domains__food': 2.250637990046774,
 'domains__health': 2.0636091088209954,
 'domains__luxury': 2.0681692283235455,
 'domains__military': 3.5731057619371183,
 'domains__mythology': 2.547251628015254,
 'domains__nature': 2.7716690079723407,
 'domains__politics': 2.987782896203816,
 'domains__religion': 2.934466944722378,
 'domains__rights': 2.536856461174647,
 'domains__sports': 3.070894262077206,
 'entities__adult': 1.967880085479104,
 'entities__alien': 2.484519285094085,
 'entities__animal': 1.7733834727847655,
 'entities__celestial': 2.3322790369158946,
 'entities__elder': 2.1713305682475035,
 'entities__human': 1.5908221256028272,
 'entities__kid': 1.8163437892687713,
 'entities__microbe': 1.8025750559974925,
 'entities__monster': 2.5961584555833235,
 'entities__plant': 2.2678431313147738,
 'entities__robot': 2.4843372655467575,
 'entities__super_': 2.4254838689705562,
 'entities__zombie': 2.3153519474805893,
 'environment__alternality': 1.9284754687561545,
 'environment__aquatic': 1.7352095192913348,
 'environment__rural': 1.8878405442076667,
 'environment__space': 1.999544351854263,
 'environment__suburban': 1.6834525982923194,
 'environment__urban': 1.8744162994222442,
 'environment__virtuality': 1.9009854800903205,
 'environment__wilderness': 1.5288404701204605,
 'eras__ancient': 1.9905061732498932,
 'eras__industrial': 1.8590540421664092,
 'eras__medieval': 1.7953841889925464,
 'eras__modern': 1.9145849355896376,
 'eras__near_future': 2.1744379387458936,
 'eras__prehistoric': 2.1792682782369943,
 'eras__renaissance': 1.7568985898920673,
 'eras__retro': 1.809115822679565,
 'eras__timeless': 1.9207384757434138,
 'focus__actors': 2.6384272724434887,
 'focus__bases': 3.104149508056796,
 'focus__cities': 2.051456699531788,
 'focus__events': 2.0164578151139856,
 'focus__interiors': 2.5007710676581425,
 'focus__levels': 2.6622428567071137,
 'focus__objects': 2.68733335080438,
 'focus__self': 2.9604401026002587,
 'focus__solutions': 2.8689193748847743,
 'focus__structures': 2.400732684891739,
 'focus__vehicles': 2.194407021125969,
 'focus__weapons': 2.7280067605674425,
 'roles__authority': 1.5958899523615506,
 'roles__carer': 1.8222474780363245,
 'roles__creator': 1.6136623136627246,
 'roles__explorer': 2.0007696207688324,
 'roles__follower': 1.7891592552210471,
 'roles__mystic': 1.8637521781870272,
 'roles__rebel': 1.818892905155879,
 'roles__solver': 1.8674700968652007,
 'roles__team': 1.7134452265390365,
 'roles__villain': 1.9201863656040317,
 'roles__warrior': 2.021371182386961}

### Save data

In [63]:
credentials = {
  "user": "external.data.user",
  "password": "wIfQxcjgZ5!gA*FWgi1z$Kj9",
  "host": "35.208.148.42",
  "port": 3306
}

conn: MySQLConnection = mysql.connector.connect(**credentials)

In [61]:
def write_df_to_db(conn: MySQLConnection, df: pd.DataFrame, guid: str):
    buf = io.BytesIO()
    df.to_feather(buf)
    buf.seek(0)
    b = buf.read()

    cur = conn.cursor()
    cur.execute("""
    DELETE FROM external_data.dms WHERE guid = %s
    """, [guid])
    cur.execute("""
    INSERT INTO external_data.dms (guid, data) VALUES (%s, %s)
    """, [guid, b])
    cur.close()
    conn.commit()

In [13]:
df_guid = '7de9c732-cb01-421c-b2ac-c77a88d9f965'

In [102]:
write_df_to_db(conn, coefs_p_df.reset_index(), df_guid)

In [103]:
conn.close()